### ISSUE TITLE
Display issues in Chrome

### ISSUE THREAD

**Issue by PeterFragon** [sabnzbd/sabnzbd#1008]
Pictures say it all...

![image](https://user-images.githubusercontent.com/19196692/29630179-ef8a9bbe-8800-11e7-8fe1-9f42e10f5448.png)

![image](https://user-images.githubusercontent.com/19196692/29630211-090d60c6-8801-11e7-819f-222f97437756.png)

**Comment by Safihre** [comment]
Right click somewhere on the page, click Inspect, click Network-tab.
Refresh the page. Check why some files are not being loaded. 
Since you posted the address, I tested it myself and for me it works. So probably it's one of your plugins.

![image](https://user-images.githubusercontent.com/5703454/29630372-4ba5c794-883c-11e7-8c4f-b001e7b91d50.png)

**Comment by PeterFragon** [comment]
![image](https://user-images.githubusercontent.com/19196692/29632176-c894c618-8807-11e7-8e99-c705c59be2a7.png)

**Comment by Safihre** [comment]
`Blocked:origin` means that it is indeed one of your plugins blocking it.

**Comment by PeterFragon** [comment]
Weird started working after inspecting and looking at the security tab...

**Comment by Safihre** [comment]
👍  Good news
