### ISSUE TITLE
Error 482 Download limt exceeded does not trigger "Optional" ignore

### ISSUE THREAD

**Issue by krylonx** [sabnzbd/sabnzbd#1009]
Based on my testing with 2.2.0

sabnzbd gets hung up on a server that throws this error and does not move to another server with lower priority

**Comment by Safihre** [comment]
The error code 482 is not defined as a real NNTP status code, usenet servers just misuse it to their will. Some use it for download limit exceeded, others for failed logins. We have had various reports before with different usages for the same code:
https://github.com/sabnzbd/sabnzbd/issues?utf8=%E2%9C%93&q=is%3Aissue%20482

Currently when we find `482` we check for keywords what it could possibly mean. We detect the word `exceeded` we think it is talking about account login number exceeded. And thus we reduce the number of connections, no blocking. Since usually those login errors resolve, we wait for the server to come back.
Not sure what to do about this...

**Comment by krylonx** [comment]
check keyword Download or Quota 
Along with Exceeded
If both exist, then block

**Comment by Safihre** [comment]
Yes, I can do that. But it will still try again 10 minutes later, but at least it won't block your downloads.

**Comment by Safihre** [comment]
Will be in 2.2.1RC2, let me know if it works.
