### ISSUE TITLE
Can't enable systemd service using sabnzbd@username

### ISSUE THREAD

**Issue by Justinzobel** [sabnzbd/sabnzbd#1023]
How can a user enable this service to start at boot using a specific username?

**Comment by Safihre** [comment]
Are you on Ubuntu/Debian using the PPA? It says how to do it on the Wiki: https://sabnzbd.org/wiki/installation/install-ubuntu-repo

**Comment by Justinzobel** [comment]
That's not for systemd.

**Comment by Safihre** [comment]
I have no clue, but Google shows me this: https://bbs.archlinux.org/viewtopic.php?id=162297

**Comment by defkev** [comment]
Without knowing anything about your environment it pretty much boils down to;

1. Create `/usr/lib/systemd/system/sabnzbd\@.service` with:
```
[Unit]
Description=SABnzbd
After=network.target

[Service]
Type=simple
ExecStart=/etc/sabnzbd/SABnzbd.py # change this as needed
User=%i

[Install]
WantedBy=multi-user.target
```
2. Create the user you want sab to run as (e.g. `sabuser`)
> [root@box] # useradd sabuser
3. Enable the service at boot
> [root@box] # systemctl enable sabnzbd@sabuser
4. And finally start it
> [root@box] # systemctl start sabnzbd@sabuser

Sab's working directory (logs, config, scripts) will be `/home/sabuser/.sabnzbd`

Cheers

**Comment by Justinzobel** [comment]
The systemd service already exists as part of the install, the issue is the @ in the service name. No matter if I try `sudo systemctl enable sabnzbd@justin` or as root `systemctl enable sabnzbd@justin` I get `Failed to execute operation: No such file or directory`

I can start the service using `sudo systemctl start sabnzbd@justin` and it works fine, just not able to enable it at startup.

**Comment by defkev** [comment]
Post the output of `sudo systemctl status sabnzbd@justin`

**Comment by Justinzobel** [comment]
```
sudo systemctl status sabnzbd@justin
Password: 
● sabnzbd@justin.service - SABnzbd binary newsreader
   Loaded: loaded (/opt/sabnzbd/linux/sabnzbd@.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
     Docs: https://sabnzbd.org/wiki/

```

**Comment by defkev** [comment]
Odd unit file location ... i suppose something's wrong with the link preventing systemctl from finding and linking it to `/etc/systemd/system/multi-user.target.wants`

Where did you put the symlink for `/opt/sabnzbd/linux/sabnzbd@.service` ?

**Comment by Justinzobel** [comment]
I'm not following, the symlink is created automatically by systemd when invoked with systemctl enable servicename

**Comment by defkev** [comment]
Yup, this is how it works.

`systemctl enable servicename` will symlink the `servicename` unit file (`*.service`) to whatever location is listed in the `[Install]` section (e.g. `WantedBy=multi-user.target`) of said unit file.

Matter of the fact is this should've been done by the install progress of your package manager as `vendor preset` is `enabled`

Now since i have no idea what repo or distribution you are using i can only vaguely guess what your unit file looks like.
Assuming it does look like mine posted early, i'm running sab from git though, you can try creating the symlink yourself like this:
`sudo ln -s /usr/lib/systemd/system/sabnzbd@.service /etc/systemd/system/multi-user.target.wants/sabnzbd@justin.service`

This either works or at least returns some meaningful error helping to pinpoint whats wrong.

**Comment by Justinzobel** [comment]
OK looks like I'll have to fix this up in the package, we need the sabnzbd@.service file in /usr/lib/systemd/system. Thanks for your help!
