### ISSUE TITLE
Improve Server Graphs

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1028]
https://forums.sabnzbd.org/viewtopic.php?f=4&t=22955

> The range toggles (Month) should affect all graphs)
> The graphs should all use the same scale. I realise this might mean one main graph and others all creep along the x axis but graphs are meant to provide info at a glance, not need you to decipher the scales (unless you're trying to sell skin care products or the like.

**Comment by pgdownload** [comment]
Realised there was one more change needed to make them 'useful':

Graphs should show cumulative data for the period (i.e. not 2Gb on Monday and 6 Gb on Friday but rather 2Gb so far then 8Gb so far etc.

Regards

Peter Gillespie

**Comment by Safihre** [comment]
Is that different from what is listed in the text? Where it says per day/week/month.

**Comment by pgdownload** [comment]
It would be the same. However the text shows just the current level since the last reset. The graphs seem to show history divided by months. The question is (and maybe you have a different answer) how best to provide instant visual comparisons of usage between servers. IMO bumps in the graph of data daily usage doesn't give great comparison info.

Again IMO the graph would start at 0 Gb each month and step up (the latest month would show the same total as the text). A yearly view (starting at 0) could also be interesting. Not sure if it would be worth incorporating the QUOTA RESET DAY (if active) in SETTINGS so a users 'month' would show along this period?

Anyway, this is all getting a bit far ahead. Did think the graphs looked good.

Regards

Peter Gillespie

**Comment by Safihre** [comment]
![image](https://user-images.githubusercontent.com/5703454/32991349-007680ea-cd3a-11e7-8605-3c58de33409e.png)
