### ISSUE TITLE
Question: how to make sabyenc more mainstream, just like other mainstream python pacakages? (Ubuntu, Debian, Linux)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1046]
Pinging @jcfp 

How can we get sabyenc more "mainstream", so that it appears in https://packages.ubuntu.com and https://www.debian.org/, just like other packages that are needed, for example python-yenc ?

Now you need pip or the PPA, which is more work and more difficult than installing "python-yenc".

**Comment by Hellowlol** [comment]
Isn't pip pre install in the python package on Linux?

**Comment by thezoggy** [comment]
its part of sab-addons ppa

**Comment by Safihre** [comment]
> Isn't pip pre install in the python package on Linux?

No, not by default. Only python is included, not pip.

> sabyenc -- its part of sab-addons ppa

That's not what @sanderjo is asking. The question is if it's possible to also have it in the official repositories, not just in the custom PPA.

**Comment by sanderjo** [comment]
Let me explain:

SAB 2.0.0 started using sabyenc.

So **before** SAB 2.0.0, installing SAB on Ubuntu and Debian (and possible other linux platforms), was just one command:
```
sudo apt-get install sabnzbdplus
```
That took care of all dependencies, including par2, rar, and python-yenc, python-cryptography, python-dubs and other needed python packages.

With SAB 2.0.0 and higher, `sudo apt-get install sabnzbdplus` is not enough anymore: you need the python package sabyenc. 
So, after your install, you have to use one of the methods described on https://sabnzbd.org/wiki/installation/sabyenc.html, so pip or PPA (with an additional PPA source) and only on Ubuntu (as installing Ubuntu _binaries_ on Debian is not adviced). That is about 4 extra commands. Error prone. Not user friendly. 

If sabyenc  can become a mainstream python package (just like python-yenc, so maybe "python-sabyenc"), installation will be again one command.  

And that is my question to @jcfp

**Comment by thezoggy** [comment]
the apt-get method only works if the os is actually including up to date packages (rare for sab) or user uses ppa...  while i understand your argument about trying to make things easier and treating linux users like osx/windows users with binaries (where we gift wrap everything for them)..  users can get this by using ppa/their package builder..

people arent being forced to use sabyenc.. and if we did.. we could just integrate it part of sab but then that would require a toolchain to compile it.. since we dont need it for python.

**Comment by jcfp** [comment]
@sanderjo that has been a work in progress since august. [Sabyenc](https://packages.qa.debian.org/p/python-sabyenc.html) was _finally_ accepted in debian unstable over the weekend, after an eternity in [new queue](https://ftp-master.debian.org/new.html). Long enough that I'm going to have to update it yet again before finally getting some recent sab version in there.

Being python2-only also [doesn't help](https://lintian.debian.org/tags/new-package-should-not-package-python2-module.html) these days, won't be too long before distros start phasing that out.

**Comment by thezoggy** [comment]
python2 just wont be included natively just like python3 wasnt included forever until recently..  but honestly the included version of python2 is always out of date on ubuntu.. you pretty much haver to end up going ppa if you want anything recent..  so I kinda view it the same as sab. if you care about having the latest and greatest, you are more than likely going to need to install from source (the true linux way?) or just do ppa and let someone else dictate it for you.

**Comment by sanderjo** [comment]
@jcfp Thank you for your work!

Related: do you understand why Ubuntu 17.10 is still on SAB 1.1.1 (which was released in nov 2016). And why Debian Testing is also still on SAB 1.1.1?

**Comment by jcfp** [comment]
@sanderjo That's because I forgot about these unpredictable delays for all-new packages. Work on sab 2.2.1 was complete in August at the same time sabyenc was uploaded.

> python2 just wont be included natively just like python3 wasnt included forever until recently

Sometime around 2020 python devs will end support for 2.x. I expect the distros to start removing it, culling anything that still relies on it then. If only to avoid the maintenance burden.

> this creates a package sync mess with stuff getting added at different times.. why I personally feel we should just do x version or greater and not exact match

I agree. Might well patch the next sab upload to that effect.

**Comment by Safihre** [comment]
> I agree. Might well patch the next sab upload to that effect.

SABYenc is a bit volatile development in terms of backwards/forwards compatibility and I want people on the right version when I change things. It's indeed a bit inconvenient but seems so far people have managed. As long as the repo's keep the right sync, then the only problem would be people installing SAB from repo but SABYenc via pip, something that I assume is less likely. 

Nice to see a newer version will be part of the main repos soon 👍

**Comment by sanderjo** [comment]
All clear thanks to @jcfp's effort and explanation https://github.com/sabnzbd/sabnzbd/issues/1046#issuecomment-335271869

Closing ... 3 2 1

**Comment by jcfp** [comment]
@Safihre I fully understand why devs like it this way, but with official repos I simply don't have that level of control. Could be days or even weeks between new versions of sabyenc and sab, causing all kinds of issues for end users.
