### ISSUE TITLE
System notification for RSS download

### ISSUE THREAD

**Issue by unknown--** [sabnzbd/sabnzbd#1049]
I see that email has the option to notify for every download that gets added via RSS but there doesn't appear to be one for regular system notifications.

Please consider adding the option.

**Comment by Safihre** [comment]
What about using `Added NZB / Pause / Resume`?

**Comment by unknown--** [comment]
Well then you would be notified of a few things rather than one specific event.

**Comment by Safihre** [comment]
This option is special to email because most other supported notification services only work well for short notifications. The RSS notification is long, it has all the names of the downloads in them.

Would it be usefully to have a notification "RSS Jobs added" with text "8 jobs were added from RSS-feed Feed1"?

**Comment by unknown--** [comment]
If there was more than one job added then yeah it would be fine to display the relevant title and number of jobs. Otherwise a notification with the job name would do. Maybe something like this:
![screen shot 2017-10-12 at 1 07 29 am](https://user-images.githubusercontent.com/7199527/31445436-c6621b3a-aee9-11e7-8e60-4e6fac920da1.png)

**Comment by unknown--** [comment]
Alternatively you could add an extra parameter to the pre-queue script feature that passes on a value to say how the NZB was added (RSS or manually) and from there the user can create their own notification using whatever method they choose.

**Comment by Safihre** [comment]
I think the adding of the new notification shouldn't be a problem.
Also wanted to split the `Added NZB / Pause / Resume` action into `Added NZB` and `Pause / Resume` since it makes no sense that these 2 are grouped.
But this are "breaking-changes" so I'm reserving them for the next major release, which will probably be 3.0.0. So might still be some time for this to happen..

**Comment by Safihre** [comment]
Decided not to implement a separate RSS notification, for reasons mentioned above. 
In the next release after 3.0.0, so probably 3.0.1, you can select the "Added NZB" and "Pause/Resume" notifications separately.
