### ISSUE TITLE
Adding nzb file hangs on upload, straight to orphaned jobs

### ISSUE THREAD

**Issue by mobtekl** [sabnzbd/sabnzbd#1058]
sabnzbd version: 2.3.0
OS X 10.13.0
python  2.7.10

The loading animation stays over other elements, check on server and server process is hung.
Refreshing the page clears the uploading element but nzb job are how in the orphaned queue.
Deleting jobs from the queue results in jobs going straight back in the orphaned queue again. Restarting the server or rebuilding the queue results in the same.
Killing the sabnzbd process and then restarting the server jobs are working again.
Then after another couple of downloads same issue again.
Couldn't find anything interesting in the logs.

**Comment by Safihre** [comment]
Can you try a different browser for the uploading problem?
It almost seems like a permissions problem, since sabnzbd can't even delete things. 
Maybe you can switch logging to Debug in the Status window, pause any ongoing downloading  and try again? Then share the last bits of the log here? (the part before the settings)

**Comment by Safihre** [comment]
@mobtekl any news on this? Did you try any of the suggestions above?
