### ISSUE TITLE
Feature Request: For each category have respective "Unwanted extensions"

### ISSUE THREAD

**Issue by snifflezak** [sabnzbd/sabnzbd#1060]
It would be great for automated setups if we could set "Unwanted extensions" respective to each category. I can set ".iso, mt2s, etc.." to abort _all_ downloads with this extension detected but if I want to download an iso later on then I have to remove that from the field.

What I propose is to have "unwanted extensions" for each respective category, which would have the effect of the user being able to filter and flag out files which they either don't want in their automation setup (like .iso extensions under plex), or otherwise are unsupported by automation software(radarr gets stuck on .iso, mt2s). This would also allow users to circumvent the filter by merely triggering a download without a category.

**Comment by snifflezak** [comment]
Sorry I just realized there's scripting functionality already under categories.

**Comment by Safihre** [comment]
While I understand your specific use-case, making it Category-specific will only be usefull for a very few people while requiring a more complicated settings-window, so I don't think we will do that.

You can use scripting to remove these files _after_ download completes, but isn't that too late? 
There is indeed no variable for the file names that result from the extraction (since they can be 1 or many), these you would have to list yourself within a script from the `SAB_COMPLETE_DIR` folder variable.

**Comment by Safihre** [comment]
Here is a post-processing script that would do what you want, in case anyone else is thinking about this.
https://gist.github.com/Safihre/8fda8c55c589fb8234072dfeadb881a4

**Comment by FrancisHG** [comment]
I would also very much appreciate this feature, my example case: abort downloads for ISO under Movies category, however, permit this extension under a manual category. This is to prevent my automated setup from downloading ISOs, while allowing manual downloads of ISO files.
