### ISSUE TITLE
Unpause if force pause because of full disk and space becomes available.

### ISSUE THREAD

**Issue by Hellowlol** [sabnzbd/sabnzbd#1083]
I ran a backlog scan and a couple of tbs was queued. My issue is that the my drive is kinda small (1 tb). It would be nice if sabnzbd unpaused if self if it was forced pause because of missing diskspace and it suddenly has enough diskspace. This way i dont need to manually unpause the sabnzbd after the postprocessing has catched up. (one file server is very slow...)

So i know this is kinda specific so i can add this feature myself. I just wanted check if this is something you would be interested in before i start.

**Comment by thezoggy** [comment]
user interaction is generally required if you have no disk space.. because that's usually a sign that space is miss managed/user error/unwieldy app. things that are generally outside sab's control.

now the best thing to do is people actually put in a value for:
`Minimum Free Space for Temporary Download Folder`

and have sab set to notify you.. so that way you know about the event rather than stumbling upon it.


now if you have limited space, there are things you can do to prevent sab workflow from being the issue.
have sab set to only work on top queue entry `Only Get Articles for Top of Queue` & `Pause Downloading During Post-Processing`, so that way your sab instance is only downloading/working on the one entry..  let it clean things up before moving on. 
while you could turn off  `Download all par2 files` to reduce space needed during download, but usually its minimal enough not to be a deal breaker (unless your talking 4k uhd rips).

now ways to work around running out of space but sab/some other app moved things out and now you want to sab to continue..  could have a notification script that just tells your sab to resume. or you just use the scheduler and say to resume at some interval. but there is going to be some sort of delay between the event and when it starts.

the problem with just watching the free space and acting on it.. over and over.. you have the potential to email/notification bomb about it.

personally if i had a small drive and a big drive, i would just segment the download folder for a category to use one or the other.. that way you can assign that app/category to the big drive if you know its downloads are going to need that space. while everything else hits the smaller drive. and if this isnt an app, you could always just have a pre-queue script that sorts it.

**Comment by Hellowlol** [comment]
Thanks for the feedback @thezoggy 
````Only Get Articles for Top of Queue```` and ```Pause Downloading During Post-Processing``` are off the table since i want to to be as efficient as possible.

Im not worried by the email bomb. I dont use the email settings and i know why i would get the email.

If this doesnt get get accepted ill take the thrid suggestion. I loads of old 1 tb drives laying around. I could always install them in my desktop.

**Comment by Hellowlol** [comment]
Closing this as it easy to add a script that handles this.

**Comment by Safihre** [comment]
It's a tricky topic and requested before a couple of times #391, @thezoggy described the reasoning very well.
We could consider adding this in some newer release as an Advanced option.
