### ISSUE TITLE
Security Issues (DNS Rebinding, Clickjacking)

### ISSUE THREAD

**Issue by beardog108** [sabnzbd/sabnzbd#1092]
Hi,

Sabnzbd does not properly filter HTTP host names, which makes it vulnerable to DNS rebinding attacks. 

This means that when not using authentication (which is off by default), any website a user visits while running Sabnzbd on their computer can view & modify their downloads, steal their Usenet server's login info, and execute arbitrary system commands (by setting the download directory to some place where executables exist, enabling overwriting of files, and then downloading a malware payload from Usenet) and perform other malicious activity.

Along with this, Sabnzbd does not set x-frame-options header, making it vulnerable to click jacking (not a huge deal, but easy to fix).

This is similar to a recent exploit in Transmission (the bittorrent client): https://github.com/transmission/transmission/pull/468

Thanks

**Comment by Safihre** [comment]
Yes we know: https://www.reddit.com/r/usenet/comments/7qscob/comment/dst1509

As also described there, we are not sure of a good solution just yet. Simply implementing a whitelist with `localhost` on it would break all the remote controlled setups that auto update via PPA or Docker.

**Comment by beardog108** [comment]
My bad. I searched here, but didn't think to check on /r/usenet first. I'll keep this issue open, but if you want to close it, then whatever.

**Comment by Safihre** [comment]
Issue here is good :)

Should we just hard enforce a whitelist and then similar to Transmission show a page with link to Wiki page why it happens and how to fix it? Suggested by some users. 
(also @sanderjo)

**Comment by beardog108** [comment]
Yeah, that would be the best route in my opinion. I found a DNS rebinding in 2017 in qBittorrent (well before the Transmission CVE), and that is what they ended up doing.

![screenshot from 2018-01-24 02-49-21](https://user-images.githubusercontent.com/4501392/35322842-44cd4a26-00b1-11e8-8a19-bb2f3ed6f42e.png)

This way users can have the convenience of not needing a login on localhost, but still be secure.

As for the other thing i mentioned in this thread, clickjacking, would be able to be fixed without breaking any workflows that I can think of.

**Comment by sanderjo** [comment]
> Should we just hard enforce a whitelist and then similar to Transmission show a page with link to Wiki page why it happens and how to fix it? Suggested by some users.
(also @sanderjo)

Just checking (because I don't understand the 'hard enforce'): my suggestion is to not change/burden default users with narrowed settings or extra access requirements, and just offer extra protection facilities for those who want that.

**Comment by jeffgeorge** [comment]
So, @beardog108 do you agree with what @Safihre described in the reddit post, that this would be _quite_ difficult to actually exploit to the point of arbitrary code execution? _Technically_ an attacker could scrape for the API key, change your download path to your script path, queue some malicious post on usenet containing the arbitrary code to execute, and then queue a second post to run with the new script . . . . except we require scripts to explicitly be marked as executable, and ensure nothing downloaded gets flagged as executable.

Assuming arbitrary code execution is off the table, all an attacker could do once they scrape your API key is monkey with your configuration and queue nzbs. Stealing credentials shouldn't be possible, because credentials aren't readable via the web UI or API.

Setting a whitelist that defaults to 'localhost' would break anybody who has SABnzbd running on a NAS, and not enabling a whitelist by default would mean it would likely not be used. Furthermore, as I understand it, users running SABnzbd on a NAS wouldn't be vulnerable to this attack, as SABnzbd isn't available via localhost.

As @Safihre mentions in the Reddit post, enforcing (or, _strongly encouraging_) a login/password may be the least-disruptive path to mitigating this issue. So, what if we pop a one-time modal dialog explaining this risk to users who both don't have a login/password set and are running SABnzbd on localhost?

Totally agree we should add the clickjacking protection, though. That's a low-impact no-brainer.

**Comment by beardog108** [comment]
@jeffgeorge Yes, this would be difficult to get code exec out of

> Assuming arbitrary code execution is off the table, all an attacker could do once they scrape your API key is monkey with your configuration and queue nzbs. Stealing credentials shouldn't be possible, because credentials aren't readable via the web UI or API.

Well, I wouldn't exactly consider it off the table. And yeah, it appears you're right, you can't get the password from the UI.

> Furthermore, as I understand it, users running SABnzbd on a NAS wouldn't be vulnerable to this attack, as SABnzbd isn't available via localhost.

I believe it would be exploitable against a NAS, if the NAS was responding to any HTTP hostname with Sab. This would be harder to exploit, as the attacker would need to know what IP it is running on, but this is possible to discover using a timing attack and response metadata. Anyway, its not as likely to be exploited as localhost.

> As @Safihre mentions in the Reddit post, enforcing (or, strongly encouraging) a login/password may be the least-disruptive path to mitigating this issue. So, what if we pop a one-time modal dialog explaining this risk to users who both don't have a login/password set and are running SABnzbd on localhost?

Yeah, this could work, strongly encourage a password & show a modal to new and existing users.

**Comment by Safihre** [comment]
@jeffgeorge Don't forget the Windows situation that I also describe on Reddit, here there is no prevention of execution so easily exploited.

So how do reverse proxies work? Would users have set it to `localhost`? So could we deduct from that if they might use custom hostnames?

Or: enable white list automatically for new users and existing users that have no username and password set?

**Comment by jeffgeorge** [comment]
Fair point re: Windows arbitrary execution. Not a whole lot we can do there apart from blocking the DNS rebinding attack.

I think a reasonable path forward would be:

1) Create a new optional whitelist, defaulting to localhost, defaulting to disabled
2) Once the whitelist is confirmed as a successful means of mitigating a DNS rebinding attack, document all of this in the Wiki
3) Create a means to pop a one-time modal dialog on the Web UI
4) Pop a one-time modal dialog if:
    - Web UI is bound to localhost
    - username/password are unset and/or DNS Whitelist is disabled
5) Explain in this dialog that to mitigate DNS Rebinding Attacks, they should either enable a username/password (Link to Config) or enable the DNS Whitelist (Link to Config), or accept the risk, and link to the Wiki page for more details.
6) . . . also set the anti-clickjacking flag.

Regarding NASes or other instances where the Web UI isn't bound to localhost, I don't know if we really need to do anything there. Brute forcing every possible local network IP or hostname and port a SABnzbd instance could be running on is unreasonable for an attacker to pull off, unless you can think of some sort of shortcut.

In my personal local SABnzbd instance I run on a local server, on a nonstandard port, and a nonstandard local network IP. I don't bother with a login/password because it's only available on my local network. How would an attacker brute force their way in via DNS rebinding? Iterate over every 192.x / 10.x IP? Iterate over all 65536 ports per IP? And do all that just to maybe be able to do arbitrary code execution if you're lucky enough that they're running Windows?

Then again, we could just remove the qualification of "Web UI is bound to localhost" for the modal, and in such an instance I'd just accept the risk because I know how _incredibly_ unlikely it would be to be exploited.

**Comment by Safihre** [comment]
Regarding `X-Frame-Options`, is `SAMEORIGIN` the option we should use?

**Comment by beardog108** [comment]
>Regarding X-Frame-Options, is SAMEORIGIN the option we should use?
Yes

**Comment by Safihre** [comment]
I implemented it similar to Transmission and verified it using @sanderjo's URL that resolves to `127.0.0.1`: http://safihre.appelboor.com:8080/

Now we need to write the wiki-page for it https://sabnzbd.org/hostname-check

**Comment by Safihre** [comment]
What happens if you remove `dfw`?

**Comment by thezoggy** [comment]
same thing, no warning

**Comment by sanderjo** [comment]
> question, if I have sab 2.3.3 setup on: http://dfw.custom_domain.net:8080/ and the whitelist has dfw why am I not getting the warning? does it just validate because it starts with it?

I can NOT confirm; SAB works for me:

`2018-04-23 10:34:20,911::WARNING::[interface:326] Refused connection with hostname "nanopineo2.blabla.com" from: ::ffff:a.b.c..90 (X-Forwarded-For: 192.168.8.179)>Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.181 Safari/537.36`

with
`host_whitelist = nanopineo2`

**Comment by thezoggy** [comment]
Yes, a username and password is set.

**Comment by Safihre** [comment]
In that case we don't check, because even if DNS-rebinding is performed, they can't really access anything but the login page.

**Comment by thezoggy** [comment]
ok that makes sense..  it wasnt clear form the doc that it would only check if a pw wasnt set.. just says to add a pw at the end

**Comment by Safihre** [comment]
@thezoggy made it into a list!
https://sabnzbd.org/wiki/extra/hostname-check.html
