### ISSUE TITLE
Make X-Frame-Options HTTP-header optional

### ISSUE THREAD

**Issue by h45rd** [sabnzbd/sabnzbd#1118]
Hi,

2.3.3 Beta 1 breaks portal web applications like Muximux for me and while there is nothing in the debug log (are clickjacking attempts logged?), I strongly suspect the X-Frame-Options HTTP-header to be the culprit.
Any chance you could make this new security feature optional and give users the possibility to opt-out?

**Comment by Safihre** [comment]
@beardog108 what do you think?
I know of multiple other media manager portals that work similar like this. 
Is this extra header really worth breaking that?

**Comment by beardog108** [comment]
@Safihre I'm pretty sure it is an x-frame-options issue as well.
You could add a config option, but if that's not worth your time, then remove it if you want.

**Comment by Safihre** [comment]
Trying to investigate if it's actually applicable for SABnzbd to include the header.
What kind of click-jacking would be used and to do what?

**Comment by beardog108** [comment]
Mess with settings and trick users into giving up data (via frame slicing, which is different from phishing since it uses fake captchas). 

Honestly neither are that big of a risk

https://samy.pl/quickjack/

**Comment by jeffgeorge** [comment]
[Muximux’s docs](https://github.com/mescon/Muximux#important-note-regarding-https) specifically call out [this chrome extension](https://chrome.google.com/webstore/detail/ignore-x-frame-headers/gleekbfjekiniecknbkamfmkohkpodhe), which disables X-frame-based security functionality. So that’s one option.

I also wouldn’t be opposed to feature-flagging this, so long as it defaults to enabled. Opt-in security may as well not exist. Portals like Muximux are typically distributed via docker stuff that pulls in all the services included, right? If so, shouldn’t they be able to pre-set such a config variable?

**Comment by aroundmyroom** [comment]
using it in a proxy state (proxypass) can solve this
I am using muximux and organizr (as test)
when using reverse proxy it can work under at least Muximux (just did it) 
so now I have a 

secure page https://myintranet.domain.com
with https://myintranet.domain.com/sabnzbd
it is running under muximux
