### ISSUE TITLE
Unar as rar file handler

### ISSUE THREAD

**Issue by PHoSawyer** [sabnzbd/sabnzbd#1120]
Could we leave unrar behind and move to unar ? It seems to be the FOSS supported unrar file handler. As long as the feature set is there obviously.

**Comment by jeffgeorge** [comment]
Moving to The Unarchiver would likely be a non-trivial implementation for rar unpacking, because last I checked we depended very heavily on detecting very specifically formatted output from ‘unrar-nonfree’, which is why we can’t just recommend using the free package ‘unrar’. Updating all that would be a pain.

Additionally, The Unarchiver is in a bit of a questionable place right now as it’s been sold to a new software company. There’s no telling if the new owners are going to keep the cli side of The Unarchiver maintained, or if they plan on focusing on the macOS GUI exclusively.

If we felt so inclined, we’d probably be better off switching fully to use the 7zip suite to cover all our extraction needs. But I don’t think anything is significantly *broken* about our unpacking processes right now, so I don’t think it’s very high on the list of stuff that needs refactoring. (Unless you’d like to dig into this, we love pull requests.)

**Comment by PHoSawyer** [comment]
No worries, thought it would be good to get away from unrar. 7zip would also be a good contender, sounds like it would be better than using unar also. Didn't see any other issues so thought I'd raise it as a wish-list item. I'll have a bigger look at 7zip and see if it's plausible. Would be an easier install also as it's in most major repo's.

**Comment by Safihre** [comment]
I don't really get the problem with UnRar, I don't even understand why it's not considered fully open-source since the source is freely available and you can use all command-line functionality without paying anything.

But that's probably a different discussion, as the most important question for this issue is:
Is it really not available for some platforms? That would really surprise me, as such a widely used tool.

**Comment by Safihre** [comment]
>  unrar-nonfree, a closed-source proprietary project from RARLABS (WinRAR), 

But I can just download the source of `unrar-nonfree` [here](https://packages.ubuntu.com/source/trusty/unrar-nonfree). And anyone can just download the source from rarlabs and compile. I don't see a problem, besides it being a matter of principle.

**Comment by jeffgeorge** [comment]
Licensing Hell. Official Unrar has [a bizarre and unique license](https://github.com/tony2001/unrar/blob/master/license.txt) which has been interpreted to be not GPL-compatible. Further complicating the issue, looks like we can't just use 7zip either, because on some distros (at least Debian / Ubuntu), you have to explicitly request `p7zip-rar` to get the non-free rar module, otherwise you get the free one which is crap. That situation puts us right back to where we might as well use official RARLABS' `unrar-nonfree`.

**Comment by PHoSawyer** [comment]
....freeware......*shudder*

Ok well I'll close this as it really doesn't make any sense after having some input from other people
