### ISSUE TITLE
hostname .local always accepted

### ISSUE THREAD

**Issue by fraternl** [sabnzbd/sabnzbd#1149]
I just read the changelog 2.3.3 -> 2.3.4 and I'm not sure what is meant here.
You don't need to login if the sabnzbd gets a request with a hostname ending in .local?
That seems to me like a security leak.

With a standard browser I can tell in proxy settings that it needs to direct all its traffic to a certain IP.
It then doesn't matter which hostname you enter and those requests will all end up at the sabnzbd server.

If the sabnzbd server then sees .local it will let it pass without credentials (or at least lower security)?

That can't be right.
Please explain when you think I'm wrong or misunderstood something.

**Comment by Safihre** [comment]
This only applies to the hostname-verification introduced in 2.3.3. 
Since it was introduced to mitigate the DNS-rebinding attacks, it relies on the attacker letting `sab.evil.com` point to `127.0.0.1` so it can avoid CORS-protection.
Since `.local` is a protected local range it can't be used from regular DNS servers.
Also, attackers can't use it because `sab.evil.com.local` will not pass the CORS-protection.

Maybe I should have written it better in the changelog!

**Comment by Safihre** [comment]
So it is independent to the login being shown, it's always shown if setup.

**Comment by fraternl** [comment]
Ah ok...
DNS rebinding protection...  Yes, that's good...
Maybe then add .lan too

Cheers

**Comment by Safihre** [comment]
Will try to be better with my changelogs next time 👍
