### ISSUE TITLE
glitter - sort or filter by category

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1158]
i noticed that d/ls in a certain category were having issues and because I dont use it all the time.. it made it a pain to go through the history to find examples. If I could have searched for that category or sort by category.. it would have made things easier.

**Comment by Safihre** [comment]
Was looking into this and wondering if anyone knows a library that can easily parse user-queries? 
Things like `age>6d cat:movies`
I couldn't find it really..

**Comment by thezoggy** [comment]
datejs / sugar are two i know of that can do the relative date stuff if you were wanting just that.. 

with mottie's tablesorter all that kinda stuff is supported in the filter widget (you can see how he coded it):
https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-filter.js

examples:
https://mottie.github.io/tablesorter/docs/example-pager-filtered.html
https://mottie.github.io/tablesorter/docs/example-widget-toggle-tablesorter.html

**Comment by Safihre** [comment]
Aaah, so to filter at the front-end? I imaged doing it at the backend. But I now see the NZBGet also filters at the front-end.

**Comment by DrEVILish** [comment]
I'd like to add my support to this.

One issue with doing this on the front end is that the current API calls to the backend are configured "Queue item limit" in the Web Interface settings, which means that any front-end filtering would only apply the first #n items of the original list in the limit. This would require to change and jQuery call to request more line data to fill the list to the "Queue item limit" is reached by the filter. This approach would require many more API calls for the filter to seem responsive, i.e. update upon keyup of inserted information.

Personally I think:
In order to reduce the number of API calls, on page load, the server should send the list of all items in the Queue, as a big list. I only see this being an issue with 1000's of queued items.
This then enables the client-side renderer to paginate the results while allowing for effective filtering.

The updates then could be established by small websocket events fired from the server upon update rather than polling the server (reducing further overhead), falling back to an API call every X seconds if the websocket connection fails.



A sorted table would be a little confusing for the Queue order. Either a new column Queue ID would have to be added in order to keep track of the actual sort order of the item.

Anyway that's my 2 cents, as usual, isn't just a simple change to add what seems to be a simple feature.

**Comment by thezoggy** [comment]
This was about the history page not queue. Queue order you don't really want to try and mess with on client side because it will dictate job processing order.

**Comment by Safihre** [comment]
I found a simple client side Javascript parser that with a few minor changes can also be used without `npm`.
https://github.com/nepsilon/search-query-parser

Then we can easily parse `cat:tv blabla`, just need to add API-support for some additional parameters.
Next step would be adding option to exclude things `-cat:tv`. 
And maybe add support for multiple items, since my initial version I only want to support 1 per filter (so not `cat:tv,movies`).
Another one could be to add simple support for completion date `completed:>6d`.

**Comment by Safihre** [comment]
Added it, for now only for filtering history on category.
Want to improve this more, so keeping it separate for 3.7.0.
https://github.com/sabnzbd/sabnzbd/tree/feature/historysearch

**Comment by Safihre** [comment]
Added filtering for Queue (category, priority) and History (category).
Allows also for multiple: `category:tv,movies`.
