### ISSUE TITLE
sab // control amount of jobs being processed

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1167]
person on irc asking how to limit how many things sab is unpacking at one time. As they noted sab began to slow down as sab decided to unpack 50 things at once. i directed them on how to turn off direct unpack or enable `Pause Downloading During Post-Processing`. I've personally never seen anyone else complain this however.

**Comment by Safihre** [comment]
It has a limit of 10 DirectUnpackers. So worst case it will be 11 (10+1 normal unpack) at once.
However, that doesn't mean it's actually doing 11 write-operations at once since there's usually only 1 or 2 jobs actively downloading, only those jobs add new rar-files to be extracted and the rest of the unrar-processes are just in paused states. 
So only mega-slow systems shouldn't be able to handle it, but on those our DirectUnpack speed-test wouldn't have enabled DIrectUnpack in the first place.

**Comment by Safihre** [comment]
Closing this, assuming I answered the question in a satisfactory way.
