### ISSUE TITLE
Empty nzo_id should report an error

### ISSUE THREAD

**Issue by Redundant1** [sabnzbd/sabnzbd#1198]
Original discussion thread:  https://forums.sabnzbd.org/viewtopic.php?f=2&t=23833&sid=15c5f37cb75190a6b838cdbc1cca4c4d

SAB only gives nzo_id if it was successfully added, while success:true is just to report that the adding was successful.

The issue with this is clients interpret the success:true as the grab being successful.  In actuality, the grab failed, so SAB should report success:false or otherwise report some sort of error to the client.  This will inform the clients that the grab failed and they should search for another release.

**Comment by markus101** [comment]
Hey @Safihre it's here: https://forums.sonarr.tv/t/same-releases-downloaded-again-after-being-blacklisted/20350

We shouldn't have an issue handling the current response with some changes on our side, but would there be any way to know why it failed? We can assume it's because it's a dupe, but will that always be the case?

**Comment by Safihre** [comment]
@markus101 Well, it doesn't have to be a dupe. It can also be rejected by user's pre-processing script, an empty/incomplete NZB-file or (worst case) a crash in the NZB-importing code. For some ancient-code reason there's no real feedback what happend, it just throws an exception.. Sigh.
In any case, not getting an `nzo_id` always indicates that the NZB was not added to the queue.

**Comment by Safihre** [comment]
@markus101 How should we proceed with this one? Can you make the changes to Sonarr to support the current SABnzbd behavior?
