### ISSUE TITLE
py3 unpacking not working... 

### ISSUE THREAD

**Issue by OutOfGears** [sabnzbd/sabnzbd#1224]
2019-01-21 14:36:28,313::ERROR::[newsunpack:534] Error "startswith first arg must be bytes or a tuple of bytes, not str" while running rar_unpack on removed.720p.HEVC.x265-MeGusta

**Comment by OutOfGears** [comment]
I can confirm setting Popen(encodig="utf-8") fixed alot of the bytes not str issues
how ever it might break something further down the line

**Comment by Safihre** [comment]
It took me a day of tinkering, but now both Direct Unpack, regular Unrar and Par2 seem to work. Even managed to test some unicode-downloads.

### For future reference:
- We have to use `platform_btou` with `Popen` because we cannot use `encoding` parameter, which was only added in Python 3.6 and we also want to support Python 3.5
- One could also suggest to use the `universal_newlines`/`text` of `Popen` (parameter was renamed) and set it to `True`, but this doesn't seem to work for unicode downloads. For some reason it breaks on special outputs.
