### ISSUE TITLE
Feature Request: Update from source built into software

### ISSUE THREAD

**Issue by richardlhughes** [sabnzbd/sabnzbd#1229]
Are you able to update from source files in the build of the software? I am using a synology build and the software  doesn't get updated frequently. It would be a nice to have to be able to update from source. 

I am currently on SABnzbd version: 2.3.5 and looks like 2 releases behind current.

**Comment by sanderjo** [comment]
I'm a synology user too, and I experience the same.

> Are you able to update from source files in the build of the software?

You can try: unpack the source package on your Synology, and run it. It might work as SABnzbd is a python program.


> Update from source built into software

 ... that sounds like Baron von Münchhausen pulling himself out of the swamp. Impossible, or at least hard and/or dangerous.

The problem is the not-up-to-date SAB package on Synology. I've heard the underlying reason is that updating the package is hard / difficult (because of the different Synology platforms?)

If you have a Synology that can run Docker, that is the solution: Docker images are uptodate because they do not depend on the Synology packaging system.

**Comment by richardlhughes** [comment]
This sounds like a good workaround. I will try to give the container a go about.

I suppose there is possibly a magic way to port the config files into the container.
