### ISSUE TITLE
sab - folder_max_length / win32 detection

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1233]
folder_max_length being set to 128 for windows.. due to basic test of os.name.
which gets used for all windows... but win xp vs win10 are different beasts. and shouldnt be viewed the same... 

on sab startup it looks to see if os.name = 'nt' for windows and if so sets win32 to true
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/__init__.py#L47

which then is used to define the `DEF_FOLDER_MAX ` variable
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/cfg.py#L58

folder_max_length then gets used for the name,
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/misc.py#L373

which will cut off things prematurely and wreck automation tools from being able to parse a release due to a partial name.

just helped someone on irc that had this set to 50 for some reason.... had them change to 128 which is default for them. but then was curious why 128 is used and not 256.

if i recall correctly we did 128 for max length because of multiple subfolders (2x job name) and overhead..
win10 that artificial limit of 260 can be removed if the user opts in:
https://docs.microsoft.com/en-us/windows/desktop/fileio/naming-a-file#maximum-path-length-limitation

to be clear I'm not saying we really should change the default limit (just perhaps detect stuff better to prevent user error).
we have a min value of `20` which i feel is a bit too low to be any good..

**Comment by Safihre** [comment]
The limit should only apply to the Incomplete-folder path as a whole, while for the Complete folder-path it's only applied to the parts of the path. So only on huge foldernames, it get's clipped for the final names.

The reason it's still there is because even on Windows 10 the max path length is still 260, unless a user manually opts in to have long path support.
Our `folder_max_length` limit is 128, because the limit is only for the _folder_. So when the files inside have a long length, it can still extend beyond 260 and fail. 
I linked it also in the code: https://github.com/sabnzbd/sabnzbd/pull/771#issuecomment-278019060, but `unrar` is the most important reason since it is called from within the Incomplete folder.
> - `Unrar`: Does not understand `\\?\` or `\\.\` for path to RAR, but does understand and it for the extraction path.

**Comment by Safihre** [comment]
Maybe we could remove the limit from the final folder name. Would have to test.

**Comment by thezoggy** [comment]
The issue is that the cut off job name due to the limit results in a shorten name reported in the history/API. So for the example last night it resulted in sonarr parsing a release with a partial name.. it cut off at the 1080p part (108) which resulted in the app thinking the release was s01e08

**Comment by Safihre** [comment]
I changed it for Py3 version, no more limiting the final folder. UnRar is now fine with it.
