### ISSUE TITLE
Feature request: cancel hanging post-download script in case it hangs.

### ISSUE THREAD

**Issue by Filechaser** [sabnzbd/sabnzbd#1271]
See title :-)

**Comment by thezoggy** [comment]
i've yet to see anyone report a hung post download.. usually its rar that crapped out. but thats been a thing of a past with switching to multipar...   so honestly i dont really see a point of this request. also how do you determine if something is hung or just slow machine/bad hdd?  also for the script to fire off.. the d/l has to finish. so right now you cant really do a watchdog style script like you want

**Comment by Safihre** [comment]
It makes sense this request, sometimes people have a post-processing script that for example calls ffmpeg. Right now you have the option to cancel it though, but it's only triggered when the script write to the console. Since we only check the cancelled-state when we get any output from the script.
@Filechaser You did see the ⬛ button in the Glitter skin? Does this solve your problem?

**Comment by fryfrog** [comment]
Would it be crazy to just ask people to use the `timeout` command in their own scripts?

**Comment by sanderjo** [comment]
Note: what is a reasonable timeout: 1 minute, 5 minutes, or 1 hour (if you run `ffmpeg` on a slow NAS) ... ?

And SAB waits for a pp script to end, before it starts other scripts / downloads, right? That can be annoying.
Furthermore, maybe a sign of life, is that the pp script is writing to output. Or, more general: how do you know a script is still actively running ... ?
