### ISSUE TITLE
ipv6_servers = 0 still uses IPv6 servers

### ISSUE THREAD

**Issue by emilbes** [sabnzbd/sabnzbd#1276]
I tested with a server that uses the same subdomain for both A and AAAA records. I have an Asus RT-AC66 router that uses a Hurricane Electric 6in4 IPv6 tunnel (my cable provider does not provide native ipv6). Using sab 2.3.8 on a win10 box.

1) Traffic moving through IPv6 is comparatively slow so very obvious when it is happening. with `ipv6_server = 1` I was maxing out at 7MB/s.
1) I changed the value to `0`, rebooted sab, and downloaded again. No difference, still capping at 7MB/s.
1) I disabled IPv6 in my router, verified that `ping6 ipv6.google.com` now gave 100% packet loss, and sab went up to 28MB/s (which is about the full width of my pipe).

This is also testable with a completely separate 2nd provider that has _different_ ipv4 and ipv6 dns subdomains. using the ipv6 entires I max at 7MB/s, and using their ipv4 domain I get 28MB/s.

The Asus router also gets colossally laggy and my entire LAN becomes unresponsive pushing 7MB/s through that 6in4 IPv6 tunnel. Using IPv4 at 28MB/s there is no noticeable lag or other effect on my network, which is another sign that IPv6 is-or-is-not in use at any given moment.

Is there perhaps something happening at a higher level in the OS or router, out of sab's control, that is converting ipv4 requests _back_ into ipv6 requests?

**Comment by Safihre** [comment]
Could you enable `+Debug` in the Status and Interface settings and then check what it says for `Connecting to address`?
Does it show a IPv4 or IPv6 address?

**Comment by sanderjo** [comment]
Can you change the setting for /sabnzbd/config/switches/#load_balancing to the first resp second option, and test both cases?

**Comment by emilbes** [comment]
@Safihre I always have +Debug enabled, but I never see IPv4/6 addresses, I only see the resolved domain names in the logs (and no IP info on the Connections tab). The logs look like:

`DEBUG::[downloader 721] Thread 5@news.usenetprovider.com: Article....`

@sanderjo There we go, I re-enabled IPv6 in the router and left `ipv6_server = 0`:

1) `Allow load-balancing with optimization for IPv6`: 7MB/s
1) `Allow load-balancing`: 28MB/s

So looks like that load-balancing setting is getting priority over the `ipv6_server` setting? Not sure which way is correct, I'd assume if you choose to completely disable IPv6 with the latter setting...you'd expect it to actually disable IPv6 :)

Regardless, I get top speed now by configuring those 2 settings as mentioned. Thanks a million!

**Comment by sanderjo** [comment]
OK, good that the workaround works for you.

Here's some background, as I developed HappyEyeballs (the "load-balancing with optimization for IPv6") into SABnzbd.

In home network setups, IPv6 should be as fast as or even faster than IPv4: IPv6 is NAT-less, whereas IPv4 is NATed which takes some processing time. (SAB measures the connect time, and sees IPv6 is indeed faster, and uses that. So that is the proof.)

However, your setup is a bit special with you IPv6 tunnel: 

- you have IPV4-NAT which takes processing power and time. To handle that, modern home routers have NAT optimization (possible even in the hardware). Your router (or line) can handle 28MB/s IPv4 before it reaches the limit.
- you have IPv6 via a tunnel, handled by your router ... however (de)tunneling takes **more** processing power than NAT; a tunnel is more difficult than NAT. The effect is that at 7MB/s IPv6 traffic, your router's CPU is at its max.

So that explains what you experience.

At the moment I wrote the HappeEyeballs implementation in SAB, the expectation was that IPv6 tunnel would start fading away because ISPs would take up their task and would provide native IPv6. For example, for that reason SixXS ceased operations 2017 (SixXS::Sunset 2017-06-06).

The effect above should also happen in Chrome when you download a file from a IPv6 & IPv4 enabled website.

Can you download, after eachother, the following URLs/Files, and measure the time, and report it back here.

http://ftp.belnet.be/ubuntu-releases/19.04/ubuntu-19.04-desktop-amd64.iso
http://193.190.67.98/ubuntu-releases/19.04/ubuntu-19.04-desktop-amd64.iso
http://[2001:6a8:3c80:2::21]/ubuntu-releases/19.04/ubuntu-19.04-desktop-amd64.iso

**Comment by thezoggy** [comment]
@emilbes are you using stock firmware or Merlin?  I had crap speeds and random site connectivity with HE tunnelbroker myself (known issues with it) but no problems with actual native v6.
