### ISSUE TITLE
Better user interface 

### ISSUE THREAD

**Issue by Timexx** [sabnzbd/sabnzbd#1280]
Hi guys, I think your UI is better than many others but I think you can improve it even more. Because it's easier to perceive and operate. I created two mockups for you. Maybe you want to set up the UI again.  
If you are interested, I can give you the specifications. 

Best regards 

![Dark](https://user-images.githubusercontent.com/9610437/57077303-02689200-6cec-11e9-9bd6-b71708ebdb15.jpg)
![White](https://user-images.githubusercontent.com/9610437/57077304-03012880-6cec-11e9-99f2-94b60bc93e3d.jpg)

**Comment by Safihre** [comment]
It's an interesting development! Very different, but I can see the appeal.
Would you be able to implement it?

**Comment by Timexx** [comment]
Unfortunately I can't really help with the implementation if you want good code ^^
My special field is the planning and design of user interfaces. Nevertheless, I would be happy if there would be a possibility to realize this.

**Comment by wtfnzb** [comment]
I think its good as it is ;) but just my opinion ...

**Comment by jeffgeorge** [comment]
Historically the way we've handled theme implementation / overhauls is for someone to bring a functioning responsive HTML/CSS/JS prototype, which we'd then assist in implementing it as an alternative template (since we can't expect everyone to immediately grok our template system). Without a functioning prototype this will unfortunately _probably_ not get much traction, but we greatly appreciate your suggestions.

**Comment by Safihre** [comment]
@Timexx Unfortunately we can't incorporate new designs if there's nobody to actually implement it. Right now the Python 3 work takes most of the little time there is.
Closing for now, unless anyone wants to pick this up and implement it :)
