### ISSUE TITLE
Error importing<NzbFile: filename= …

### ISSUE THREAD

**Issue by pjmeli** [sabnzbd/sabnzbd#1281]
I get this error on some downloads, appears to be those with many missing articles:

> Error importing <NzbFile: filename=9e80a05814894d00b0d2d17cf65c91ce.vol31+04.par2, type=None>

The error repeats for each part, usually 20 or so errors and then the job fails as expected and is removed from Queue and History.

As I said jobs in the Queue without missing articles appear to process normally.

I've read through the related threads and they do not seem to address this particular behavior.

Running v2.3.8 [83ccc0a] on Raspian Stretch on a Raspberry Pi Model B+

Regards,
Paul

**Comment by sanderjo** [comment]
`Error importing NzbFile: filename=9e80a05814894d00b0d2d17cf65c91ce.vol31+04.par2`

See that file extension? par2? par2 is not a NZB file, so that error is correct.

Now you have to find out  why/who/what is feeding par2 into SABnzbd as NZB. Could be watch folder pointing to download or NZB backup folder.

If you can find it, start from scratch by renaming sabnzbd.ini and sabnzbd.ini.bak

**Comment by Safihre** [comment]
@sanderjo that's not correct, although the name might suggest `NzbFile` is an NZB object, it's actually a "file inside an NZB". So it can't load the database with articles.

There's some reasons for it, usually indeed relating to high job traffic situations. Here it can occur that deleting a job from the history actually also deletes some queue data because the folder names are the same. 
I've also seen it happen on Windows when there's download activity when Windows is shutting down and it just kills SABnzbd instead of performing a nice shutdown. Although not the case here of course. 

@sanderjo's suggestion might still be good: what if you start from scratch with your settings. Do you maybe use the setting "Check before download"? 

Otherwise, you could enable Debug logging in the Status window and then after it happens again we can check the logs. Although enabling Debug is heavier load for the small raspberry.

**Comment by pjmeli** [comment]
I was using the setting "Check before download".

I unchecked it and the error messages stopped. 

Sabnzbd still aborts bad downloads fairly quickly (which it should because I only got the messages on downloads doomed to fail) so that switch must have another purpose than what I thought.

Is it meant to display error messages, or is something else amiss?

Don't know if it's relevant but I'm running Sabnzbd from a git repository in my home folder

**Comment by Safihre** [comment]
This can happen due to file-locking issues, where SABnzbd is already cleaning up a failed download but the pre-check is still going. Indeed we advice nowadays not to use the pre-check because there's these kind of wonky errors in there.
We could fix them, but the more reliable quick-fail is doing it's job nowadays!
