### ISSUE TITLE
"Check Before Download" results in duplicate backed-up NZB file

### ISSUE THREAD

**Issue by hl2guide** [sabnzbd/sabnzbd#1289]
If the switch "Check before download" is enabled and a "Watched Folder" is set, it results in a duplicate NZB file in the ".nzb Backup Folder" (if set).

The duplicate NZB file has a shortened name (31 characters).

Is this a bug or the intended outcome?

**Comment by Safihre** [comment]
What do you have set for `folder_max_length` in Config Specials?

**Comment by hl2guide** [comment]
128

**Comment by hl2guide** [comment]
To be clear, by duplicate I mean a duplicate .nzb file.

**Comment by Safihre** [comment]
I was mistaken before, this is not controlled by `folder_max_length` but by the limitation that the whole Incomplete folder path should be max 72 characters (arbitrary length). Otherwise UnRar get's upset when there's really long Rar-filenames. 
Maybe we just shouldn't save the file again when re-adding after pre-check.
