### ISSUE TITLE
Zip bomb

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#1311]
https://www.vice.com/amp/en_us/article/597vzx/the-most-clever-zip-bomb-ever-made-explodes-a-46mb-file-to-45-petabytes

How to protect against?

**Comment by jeffgeorge** [comment]
I'd think protecting against zipbombs would be better handled in the tools doing the unzipping, rather than pre-processing. Like, does 7zip protect against zipbombs at all?

According to [this answer](https://stackoverflow.com/a/1459154) we may be able to look for anomalous data in the headers, but as the comments state, we'd have to deal with the issue of recursion, since things like `42.zip` expand so large via recursion. Worse, the [shiny new zipbombs](https://www.bamsoftware.com/hacks/zipbomb/) depend on even more weirdness (overlapping) which would also not likely be detectable.

Interested to see what that header-analyzing snippet of python does vs these new terrors. Might try it on a spare RPi later so if it goes wrong it doesn't obliterate a disk I care about.

**Comment by thezoggy** [comment]
Yeah just was tossing it up for discussion since infinite recession and disk bombs are something that I've never seen so far. Not sure what we can do on our side or if anything has already been down on the utilities side

**Comment by Safihre** [comment]
I indeed don't think we can do much on our side..
