### ISSUE TITLE
Email Notifications: Digest

### ISSUE THREAD

**Issue by chrismaki** [sabnzbd/sabnzbd#1313]
I recently enabled email notifications but promptly disabled it due to such a large number of emails. Please consider adding a daily-digest option for both completed jobs and errors.

Thanks.

**Comment by Safihre** [comment]
While I understand the request, it is unlikely we will implement this within a reasonable timeframe. The email notifications are only used by a low number of people that so far seem to have been fine with multiple emails.
Because of this I will close this issue for now. We can re-open if there's multiple requests!

**Comment by thezoggy** [comment]
if you dont care to know about stuff when it happens.. perhaps just use the history or push it to something that can provide some aggregation (notification services)
