### ISSUE TITLE
Feature request: Automatically lower priority of slow downloads / percent of missing articles

### ISSUE THREAD

**Issue by fryfrog** [sabnzbd/sabnzbd#1326]
Occasionally I'll queue up anywhere from a few to a *lot* of *old* downloads which have questionable availability. I'd *love* to be able to automatically lower the priority of those downloads based on a percentage or threshold related to the cancelation. For example, if 10% missing would cancel a download, perhaps 1% missing would reduce it to low priority so other downloads could be attempted first.

**Comment by thezoggy** [comment]
just use the sort by age feature and newer stuff will be higher in the queue? as generally you see a correlation with age and completness (assuming propagation is not the issue - if so, set that delay as well).

**Comment by fryfrog** [comment]
![Screen Shot 2019-09-04 at 2 24 24 PM](https://user-images.githubusercontent.com/87748/64292654-b6d72680-cf1f-11e9-9677-ea6302229c11.png)

Sort by age actually goes the other way, putting *old* things first. I already use this option. I'm not really trying to prioritize old or new... more like just fastest over slowest. And slow downloads are usually the ones w/ missing articles from tier 0 servers.

**Comment by Safihre** [comment]
While I can see where you are coming from, this is really an advanced feature that would confuse people. Already the Sort by Age is something people select and forget, and then create posts on the forum asking us why their queue is randomly sorting.
So I think it's safe to close this feature-request since there's almost no chance we'll implement it.
