### ISSUE TITLE
IPv6 server through HE tunnel broker

### ISSUE THREAD

**Issue by h3llrais3r** [sabnzbd/sabnzbd#1352]
I'm having a strange behaviour after upgrading from windows 8.1 to windows 10.
I'm running Sabnzbd as a windows service with a configured ipv6 server.
It has been working for ages, but since the upgrade to windows 10, sabnzbd cannot connect to it anymore... it always gives the following error: 
 ```
[Errno 10049] Address not available 
Check for internet or DNS problems
```
Only solution seems to be the following:

- login on my server
- ping the ipv6 server
- restart sabnzb

After this, the hostname is resolved and the connection works.

Any idea what could cause this?

**Comment by thezoggy** [comment]
since you did not provide any logs/configs or anything useful to actually troubleshoot we have to make some assumptions here.

it sounds like you have broken v6 locally and probably dont have v6 from your isp.. so you rely on the HE tunnel. your local dns or adapters cant bind to it until after the tunnel is established..   or sab is trying to bind but cant (not allowed as the service user).

you prob need to update your order of operations or fix service permission/allowance.
(not really anything to do with sab itself).

**Comment by h3llrais3r** [comment]
@thezoggy 
You're right, I'm using HE tunnel because I don't have native ipv6 from my isp.
I already enabled debug logging and checked it, but I couldn't find anything in it related to ipv6 problems. If you want I can share some logs.
The strange thing is that it works after a restart and a ping (only restart or ping doesn't fix it...  strange) so it's indeed most likely not related to SABnzbd itself.
Because I couldn't find much info on it on the internet, I just wanted to post it here in the hope that someone else also experienced this issue and perhaps have a possible solution for it. 😉

**Comment by h3llrais3r** [comment]
Workaround is launching Sabnzb via a bat file in which I wait for 30 seconds, ping the server myself and then start Sanzbd. So I have the impression that since the upgrade to Windows 10 the service is started too early and the ipv6 connectivity is not yet available.
Although I still find it strange that the ping is needed, without it, it doens't work either...

**Comment by Natteverf** [comment]
Try changing the service to "automatic - delayed start"?

**Comment by h3llrais3r** [comment]
@Natteverf, I did try that, but it didn't work. 😞
