### ISSUE TITLE
Final Python 2 Sab release

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1355]
From https://www.python.org/dev/peps/pep-0373/

2.7.18 code freeze January, 2020
2.7.18 release candidate early April, 2020
2.7.18 mid-April, 2020

Out of curiosity will there be a final Python 2 version of Sab, like 2.3.9.1 or 2.4.0 using the final Python 2.7 release due in April, while Sab 3.0 on Python 3 is finalized?

Best regards

**Comment by thezoggy** [comment]
we dont really care about the python2 release cycle (unless there was some sort of bug fix/security thing in it). a new sab build happens because there is new sab code. now for those that rely on compiled binaries (instead of doing it themselves or just running from source) it may or maynot use a new python2 version depending whats on the build server. so the answer is maybe?

**Comment by Safihre** [comment]
I wasn't planning on it :)
Will try to make a 3.0.0-Alpha release very soon.
However, the first one will be without macOS support because I will need to actually get myself a Mac. I do have a Hackingtosh VM but it's crazy slow and impossible to fix the problems on. Spend the whole Christmas holidays trying to get it to work or make a new one. 
Plus Apple now requires you to do two-factor authentication/verification using an Apple device (no sms or 2-factor apps) before you can do code-signing.
