### ISSUE TITLE
smarter re-extraction after error

### ISSUE THREAD

**Issue by sjpotter** [sabnzbd/sabnzbd#1360]
if an archive fails to extract because of an error, sabnzbd puts it back into the queue to download par2 files, repairs, and does an extraction again.  However, it seems to do the extraction from the beginning.  It would be smarter to extract into the same location, with overwrite turned off.  If the initial extraction would delete any file that failed to extract successfully, this shouldn't be a problem.

**Comment by sanderjo** [comment]
As they say "meten is weten", so do you measurements of: 
* unrar-extraction with faulty rar
* unrar-extraction with repaired rar, from scratch
* unrar-extraction with repaired rar, with overwrite turned off

**Comment by sjpotter** [comment]
I can just speak from experience.  an unrar of a 50GB rarset, even on a 48GB of ram machine takes a very long time, especially when the disk one is writing to is overloaded with iops as it is.

**Comment by sanderjo** [comment]
> I can just speak from experience. an unrar of a 50GB rarset, even on a 48GB of ram machine takes a very long time

SMART, please. So ... very long time = how many seconds? Minutes?

**Comment by sjpotter** [comment]
I have an unrar that's been running for about 2 hours (and probably for 2 hours before, as it had to repair then restart).

**Comment by thezoggy** [comment]
Or just enable par download by default?

**Comment by sjpotter** [comment]
I download pars and repair by default, but if it can direct unpack, that's much better.  so that's what usually happens unless it runs into an error.

**Comment by sjpotter** [comment]
Let's give examples: I download a 50GB rar set, after 75% of it is direct unpacked, an error occurs.  so it downloads finshes downloading, downloads pars and fixes itself, and then unpacks the whole thing again.

to me this seems like a lot of wasted work.  Of course if that 75% was a single file, there's nothing one can do.

An even smarter method might be if one is in a direct unpack to check individual files before the extraction is continued to it and if a file is bad, to wait until it an repair the archive and continue the existing extraction  (in that case, one won't lose the 75% of work one did)

**Comment by albino1** [comment]
If your unpack is taking 2-4 hours, even with repair, then I think you have larger problems than inefficient extraction.

Looking at my SAB history right now I have several 40-50gb NZBs that all extracted in less than 2 minutes, mostly via direct unpack.  One required a repair where the verification + repair + extraction total was less than 5 minutes.

![sab-repair](https://user-images.githubusercontent.com/12164957/74092015-a2b9c700-4a73-11ea-9d59-668c820cd1e8.jpg)

Instead of trying to make the SAB extraction process fractionally more efficient, I would figure out what's wrong with your setup.  Upgrade to an SSD, don't use a raspberry pi, don't extract over network or to a USB drive, get more backups so you have less missing blocks, etc.

**Comment by sjpotter** [comment]
going after the speed is a red herring and avoiding the issue.  

yes, my destination disk is very overloaded during this issues (it's a raid5 of spinning disks, and is doing about 100 continious read streams, which exhaust most of its iops), so yes, its possible my workflow could be better, but that's not really the point, the question is can sabnzbd be smarter about how it extracts to avoid having to redo work.
