### ISSUE TITLE
Can you please make a Flatpak? Having problems with the Snap.

### ISSUE THREAD

**Issue by alextrayanov** [sabnzbd/sabnzbd#1471]
The snap just stopped working. It refuses to open. Tried uninstalling and installing again with no luck. 
It's not the only snap that became unusable (I have one more snap app) after I updated the system.
Never had problem with Flatpak apps. They load faster and work better.
Please consider creating a Flatpak version for the rest of us.
I really appreciate your hard work and love the client but the snap version is not good and it's snap's fault.

**Comment by Safihre** [comment]
Oh Linux... So instead of 1 system, of course they came up with 15 ones that all have drawbacks and they all have their own quirks.. 
If we support Flatpack, why not also AppImage another user will ask..

But: if you can create a pull request that adds Flatpack support, I'm willing to reconsider. This is also how we got snap support, because someone else did the work 😎

**Comment by TuxyKey** [comment]
To @Safihre 
i realize it's a hassle al those Linux distro's and as soon as you put the effort for one someone else is complaining that you didn't cover their specific distro.. Personally i would cover Ubuntu and Fedora that will take care of every distro that is based of Ubuntu and those based of fedora like centos,rhel and so on..
And when talking about packaging systems i would say it's also only two  Flatpack and snaps..
But to be frank there is no need to bother with flat or snap when you already have ubuntu and fedora covered..

i just migrated from Apple OSX and did not want to use windows so i looked in to the biggest and most known distro's.
And tried Ubuntu derivative and eventually landed on fedora..

i tried installing from source but got all sorts of error's in short a no go..
tried installing from nuxref repo ..but they only have an old version.. 3.1.1 ..

ps.
As a last resort i would use snaps. i would prefer flatpack because snaps make a mess of my system with all those loop devices. 
i hope this awesome project will reconsider and cover two distros fedora and ubuntu...

**Comment by Safihre** [comment]
We cover ubuntu using our ppa: https://sabnzbd.org/wiki/installation/install-unix
And of course there's also Docker always :)

**Comment by thezoggy** [comment]
hey why isnt my <insert package manager / nas / os> supported!?
the answer as safihre noted, its because no one has shown interest and submitted the stuff for it, or offered to maintain it.

the ppa method while legacy is what most people use for the main distros.
if you want the newer 'user friendly' packages then thats somwhat left to the community to handle (unless one of us just happen to get a device/interest to do it).

@Safihre we might want to get some verbiage added to https://sabnzbd.org/wiki/installation/install-unix about 'if you dont see your package here, feel free to contribute' type thing

**Comment by TuxyKey** [comment]
> hey why isnt my <insert package manager / nas / os> supported!?
> the answer as safihre noted, its because no one has shown interest and submitted the stuff for it, or offered to maintain it.
> 
> the ppa method while legacy is what most people use for the main distros.
> if you want the newer 'user friendly' packages then thats somwhat left to the community to handle (unless one of us just happen to get a device/interest to do it).
> 
> @Safihre we might want to get some verbiage added to https://sabnzbd.org/wiki/installation/install-unix about 'if you dont see your package here, feel free to contribute' type thing

To be 100% honest with you, my first reaction to reading your comment / reply was. Why do mac and windows users get the white glove treatment and when your in Linux your on your own feel free to contribute.. 
almost sounds like , he dude want to user our software ok roll up your sleeves man.. work for it..

Then i asked a friend that has bin using Linux desktop for way longer then i. and he said no man it's not that way at all.  Linux is project based and it's normal that people ask for contribution as that's how a project grows true the effort of people. and on Linux people are expected to be able to do this..

Well that i do understand. I'll see if i can help.. don't really know how to start.. But my initial install from source did not go well. 
Prior to this install i did an install using the nuxref repo i saved the install log and went true it finding all sort of dependencies.
that were not mentioned in the Sabnzbd wiki. As i don't know what each package does i can't really comment on the wiki an say what should and should not be installed.. 

finally i had everything installed even got the sabyenc installed via pip.. (new one for me).
looking at my install logs it's a hot mes failures after failures sifting true it all i can't make any sense of it.. 
like i mentioned eventually it all turned out good.. until i started sabnzbd... Seems i got version 3.3.6 of sabyenc and i needed  4.0.0 
this was the error i got:
SABYenc module... NOT found! Expecting v4.0.0 - https://sabnzbd.org/sabyenc

My friend told me to package it my self. ..
Well that's a new one...for me.. where do i even get all the correct dependencies ..pfff

He told me to start reading about "Fedora Packaging Guidelines"
https://docs.fedoraproject.org/en-US/packaging-guidelines/

and about "Creating RPM packages"
https://docs.fedoraproject.org/en-US/quick-docs/creating-rpm-packages/

i told him i prefer flatpak over snaps i that doesn't make a mess of my system with loop devices mounted .
His suggestion was ok try creating a flatpak hahah..

ill see if i can get my current install to work.. otherwise i'll migrate my system to feodra 34.. see about getting virtualization going and get familiar with snapshot on Linux vm's (bin using vmware fustion for too long).. 
And then do a new install of sabnzb en see if i can't figure it all out. 

That is if i have the time.. to do so..really hope and want to help out as much as i can.. bin using Sabnzbd for years on mac and i love it.. my migration to Fedora seems to be harder than i thought it would be..

**Comment by thezoggy** [comment]
so on linux/windows/mac you could install from source. that means you are responsible for getting the source + install dependencies. one step up for linux is ppa which wraps the whole getting source+dependencies together so you just install that and it kinda does the rest. on win/mac the similar thing is the binaries (app/exe) packages we build.  now going another step like docker or custom packages for a nas/specific os implementation is a bit more and may require custom installer/updater logic or non-standard methods to control dependencies because of the system.. that is where it really falls on the community of that system.

**Comment by sanderjo** [comment]
@TuxyKey  

I can't help you with flatpak or snap, nor with discussions about who should provide what, and differences between Windows MacOS and Linux.

But ... I can help with installing SABnzbd from source on Fedora. I just tried on a Fedora docker image, and ... just 6 commands and SABnzbd works.

If you want that help, open a github thread with "install SABnzbd from on Fedora" and I'll try to guide you.

**Comment by TuxyKey** [comment]
> @TuxyKey
> 
> I can't help you with flatpak or snap, nor with discussions about who should provide what, and differences between Windows MacOS and Linux.
> 
> But ... I can help with installing SABnzbd from source on Fedora. I just tried on a Fedora docker image, and ... just 6 commands and SABnzbd works.
> 
> If you want that help, open a github thread with "install SABnzbd from on Fedora" and I'll try to guide you.

Hi there Sanderjo thanks for your help..
i did as you recommended.. 
and opened a new issue hope this is the correct way to do it..if not please let me know what to do things like Assignees and such are empty don't know how or what to put there..
here is the link:
https://github.com/sabnzbd/sabnzbd/issues/1899

Thanks again.

**Comment by thezoggy** [comment]
@sanderjo aye, ppa for Ubuntu / rpm for others etc. Thr point I was making was just the whole talk about mainstream package (seems like rpm would be the one he wants on Fedora?) But then there are these newer packages like snap/flat which have a small userbase compared to the rest and little interest until this thread (not to say others wouldn't benefit from it just none of us seem to really use.it)

**Comment by francoism90** [comment]
I'm interested in creating a Flatpak package. Just take a look at Fedora Silverblue and other distro's using Flatpak, it would be a great addition.

**Comment by Safihre** [comment]
If you are able to create a PR with the code and other steps I need to take to publish, I can review the maintenance burden :)

**Comment by Safihre** [comment]
That json look like a nightmare to maintain if it has to be done manually..

**Comment by francoism90** [comment]
@Safihre I think it has been generated. I'll wait till I get a response from the creator.
