### ISSUE TITLE
[FR] Fullwidth page

### ISSUE THREAD

**Issue by reloxx13** [sabnzbd/sabnzbd#1473]
Using a limited center webpage is outdated.
Nowadays displays/monitors in 16:9 have enough width.

I would like to request full width display or a switch to change between fullwidth and centered.

**Comment by thezoggy** [comment]
right now glitter uses fixed with depending on screen size. fluid while is great for those that dont have 4k screens (or multi-monitors) it becomes comical otherwise. perhaps a good solution is to offer some sort of toggle to switched from fixed to %.. but also people can easily solve this on their side by modifying the css manually or using stylish or something similar

**Comment by reloxx13** [comment]
I use `Glitter - Night`

![grafik](https://user-images.githubusercontent.com/14855001/83312517-dbdc9980-a212-11ea-8c7f-8f057bf686a9.png)

And yep, im using stylish already, but v3 is going on so maybe you consider to add this to use and show more infos.

**Comment by albino1** [comment]
I have a 32" 4K monitor and I just switched SAB from 1700px wide to 3400px wide and it's significantly harder to read IMHO.  You literally have to move your head from left to right to read a single line instead of being able to see all of the information with a quick glance.  If you guys decide to implement this, definitely make an option to disable it like thezoggy suggested.

**Comment by Safihre** [comment]
The current system works well because it implements predictable steps (especially on smaller sizes) and stretches to a crazy 1700px on huge screens. 
Already on my 1080p display it just looks too stretched when not adding the borders on the side.
