### ISSUE TITLE
Sabnzbd doesn't delete failed downloads after a code 1 from a external script

### ISSUE THREAD

**Issue by PotatoQuality** [sabnzbd/sabnzbd#1587]
Hi all,

I'm using Radarr in combination with Sabnzbd on an unraid server.
Both are in a docker container. After the last update to 3.0.0. I discovered that my rename python script doesn't work anymore.
I suspect that the script isn't supported on the new python version and throws exitcode 1 to sabnzbd.
Radarr send a delete action to Sabnzbd and selects a new version.

Strangely, SABnzbd doesn't delete the downloaded movie in the folder. So after a while, my download folder was full of movies that wasn't deleted.

Is this normal behavior from sabnzbd? If a script fails, normally sabnzbd delete the files in the folder if radarr sends a delete action.
 

Current Sabnzbd version: 3.0.1

**Comment by Safihre** [comment]
In which folder? Your Incomplete or your Complete folder?
SABnzbd has never deleted files from the Complete folder, only Incomplete.

**Comment by PotatoQuality** [comment]
Hi @Safihre thanks for you're quick to respond.
Its get stuck in the folder what is configured in the categorie settings. 

For exemple, movie goes to /path/to/movies

**Comment by Safihre** [comment]
Yes, exactly. This is because after we have repaired, we remove the par2 files. After we have unpacked, we remove the source (rar) files. Only then we start the post-proc script.
So if the post-proc script returns a failure and we would remove the complete-folder, there would be no way for the user to manually still use it's files.
