### ISSUE TITLE
Drop Python 3.5 support 

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1607]
I just added typing hints to some of the source code, which makes it a lot easier for me to develop because tools like Pycharm now correctly identify many of our custom classes and objects.
However, this isn't supported in Python 3.5.
I saw that Python 3.5 is end of life from python.org at the end of this month.
Would there be anything against dropping 3.5 support for 3.1.0?
I saw somewhere that some old Ubuntu LTS version is locked to 3.5. Is this something we should consider? @jcfp probably knows!

**Comment by sanderjo** [comment]
> I saw that Python 3.5 is end of life from python.org at the end of this month.

If Python 3.5 is indeed EoL, and no new version released, I'm in favor of dropping support, by issuing a warning saying so.

(Ubuntu 16.04 ("Xenial") is supported till April 2021, and has Python 3.5 ... so how is Canonical goging to do that?)

And how about Windows versions that are not supported by Microsoft, so Windows 7 and Windows 8? A warning too?

**Comment by thezoggy** [comment]
I'm all for dropping py3.5.

**Comment by jcfp** [comment]
> I saw somewhere that some old Ubuntu LTS version is locked to 3.5. Is this something we should consider?

The only release affected would be 16.04, for which support only lasts another some 7 months or so. And that already doesn't have any sab version past 2.3.9 on the PPA because it came across too many issues with all the libs that needed backporting. Feel free to ignore when dropping py3.5.

> (Ubuntu 16.04 ("Xenial") is supported till April 2021, and has Python 3.5 ... so how is Canonical going to handle that?)

No upstream support doesn't mean you can't do targeted fixes for CVEs. Just a bit more work writing patches.

> And how about Windows versions that are not supported by Microsoft, so Windows 7 and Windows 8? A warning too?

Not our business, the risk of running an out-of-date operating system doesn't increase by using sab.

**Comment by Safihre** [comment]
Thanks for the input. I'll put a warning for now and drop support after 3.1.0. Probably too fast to drop it already.

**Comment by sanderjo** [comment]
Root cause: par2-only post, with all the articles not available on the server(s).

@Safihre 's patch works ... no more crash.

**Comment by thezoggy** [comment]
saw this, thought it was neat to visually show how old some of the py3.x versions are: https://python-release-cycle.glitch.me/
