### ISSUE TITLE
Out of memory: Killed process 724546 (sabnzbdplus)

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#1723]
Situation: 20-30 items in queue, each of size 10-40GB.
Linux decided to kill SAB. Three times in a night. Seems to happen after pausing SAB.

From /var/log/syslog:
```
Dec 27 22:54:41 brixit kernel: [220712.451806] Free swap  = 0kB
Dec 27 22:54:41 brixit kernel: [220712.451807] Total swap = 2097148kB
Dec 27 22:54:41 brixit kernel: [220712.451807] 999882 pages RAM


Dec 27 22:54:41 brixit kernel: [220712.452141] oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=/,mems_allowed=0,global_oom,task_memcg=/system.slice/sabnzbdplus.service,task=sabnzbdplus,pid=724546,uid=1000
Dec 27 22:54:41 brixit kernel: [220712.452199] Out of memory: Killed process 724546 (sabnzbdplus) total-vm:3940444kB, anon-rss:1767992kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:3772kB oom_score_adj:0
Dec 27 22:54:41 brixit kernel: [220712.585785] oom_reaper: reaped process 724546 (sabnzbdplus), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB
```
... I'll start by increasing my swap space, and raising swappiness from 10 to 60 again.

**Comment by Safihre** [comment]
And lower your article cache settings?
How much memory does it say SABnzbd was using?

**Comment by sanderjo** [comment]
> And lower your article cache settings?

Done: now lowered from 936.4 M to 500 M

> How much memory does it say SABnzbd was using?

`total-vm:3940444kB, anon-rss:1767992kB` So: 3.9 GB shared memory, and 1.7GB real unique memory

It's a pity stuff in the queue still eats memory.

**Comment by Safihre** [comment]
That's a crazy amount.. I have no clue where that is coming from, maybe a memory leak indeed.
This is 3.1.1 or 3.2.0-develop?

**Comment by sanderjo** [comment]
I would say it came from the queue: I had 30 items of mean size 20GB each in the queue. I can repeat that process, and see what happens.

3.1.1 from PPA

**Comment by puzzledsab** [comment]
Is this issue the same after the gc.collect() change discussed in #1736? Are any of the servers ahead of others, so that a lot of articles are loaded into memory?

I'm looking into #973, but that won't help this issue if the articles aren't loaded. In my tests the file objects uses ~15% of the memory and the articles ~80%. I've tried pickling the files instead of the article list and replacing them with a named tuple containing a few vital attributes so that manipulating the queue in the browser still works. It could save RAM but there isn't much that can be done without the files having to be de-pickled.

**Comment by puzzledsab** [comment]
I tried adding a queue of 1.1 TB of stuff under Windows while SAB was paused so that no articles were loaded. The memory usage stopped increasing fairly early, at about 150 MB. The last 500 GB didn't increase the memory usage at all. Is it the same on other platforms? If so, it is probably enough to be able to pickle the articles while they are not needed.

**Comment by sanderjo** [comment]
I can try that on my SAB (3.2.0 beta1 on Linux)

BTW: At the moment you unpaused, did memory usage go up?

**Comment by puzzledsab** [comment]
When I unpause the memory usage starts bouncing up and down between ~165 - 185 MB. When I delete the queue it only falls to 155 MB immediately, and then later to 96 MB. It doesn't seem to fall more than that, so that's ~50 MB more than when I start SAB without any articles.

I also tried setting up a primary server with 1 day retention. The memory usage will increases to 700 MB+ while it adds itself to the Try list. When I deleted the queue it first fell to ~450 MB, and then to 105 MB after a while. I assume it's because of the gc.collect().

**Comment by sanderjo** [comment]
Results:

Sabnzbd 3.2.0 dev, on Linux, set to PAUSED, uploading 10 NZBs, total 800 GB, sitting in the queue doing nothing ... and SAB's real memory usage is ... **638 MB**

![image](https://user-images.githubusercontent.com/1273502/104777256-aa054c80-577b-11eb-973c-7c4217c3f558.png)

Check via `top`: 8.1% of my 8GB RAM = 648MB RAM usage.

```
$ top

top - 21:52:58 up 7 days, 23:54,  1 user,  load average: 2,74, 1,91, 1,62
Tasks: 327 total,   1 running, 326 sleeping,   0 stopped,   0 zombie
%Cpu(s):  9,5 us,  3,6 sy,  0,0 ni, 86,2 id,  0,2 wa,  0,0 hi,  0,5 si,  0,0 st
MiB Mem :   7847,3 total,    183,1 free,   6517,8 used,   1146,4 buff/cache
MiB Swap:   2048,0 total,      0,2 free,   2047,8 used.    404,9 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                             
 193201 sander    20   0 4940576 123124  63256 S  11,9   1,5   1:36.46 chrome                                                                                                                              
 206540 sander    20   0 2502820 653424  32156 S   5,9   8,1   1:58.70 SABnzbd.py                                                                                                                          
  12028 sander    20   0  932212 234604 120068 S   5,3   2,9 405:07.41 chrome                  

```

**Comment by sanderjo** [comment]
Result with actual downloading: 700+ MB RAM usage

So downloading or not: stuff in the queue eats memory. But I thought we already knew that?

![image](https://user-images.githubusercontent.com/1273502/104779756-edfa5080-577f-11eb-89cd-31216b9a953c.png)

**Comment by Safihre** [comment]
It's just a lot of memory 🤯
