### ISSUE TITLE
Subject naming pattern can cause 0 character filenames 

### ISSUE THREAD

**Issue by racquemis** [sabnzbd/sabnzbd#1768]
The naming pattern RE_SUBJECT_BASIC_FILENAME, seems to need some work, it does not handle subjects in a sensible matter when the filename in the subject ends with the ] character. This results in zero character filenames. 

Example:
``` [PRiVATE]-[WtFnZb]-[Video_(2001)_AC5.1_-RELEASE_[TAoE].mkv]-[1/23] - &quot;&quot; yEnc  1234567890 (1/23456)```

**Comment by Safihre** [comment]
Agreed, it should at least have a single character for the filename.
So in this case it should just fall back to using the whole subject as a filename since this case is just too exotic. For a human it's easy to see that `[TAoE]` is part of the filename, but for a regex that's too much. It's only purpose was basic cases of this weird naming format...
If only the just put the filename between the `&quot;&quot;` as it should be..
