### ISSUE TITLE
Download Speed Issues

### ISSUE THREAD

**Issue by strikeru97** [sabnzbd/sabnzbd#1847]
Since the new SABNZBD version, the connection is very unstable. I have tried the NZBGET software as a test and there the problems do not exist. So that I can exclude my PC & my provider as a source of error. If LOG files are needed or similar please indicate where I can find them so I can upload it.

**Comment by thezoggy** [comment]
your issue is pretty vague and there is a whole slew of various things that could explain it (from how you have things to configure / the os/software running on it / where you are downloading or just how to read the numbers). 

not sharing what os/sab version/etc doesnt really help anyone even begin to look at the issue.
i would recommend going to sab forums to post the general issue where you can share details as github is mainly for code specific issues or requests.
