### ISSUE TITLE
Create docker image on hub.docker.com

### ISSUE THREAD

**Issue by discordianfish** [sabnzbd/sabnzbd#188]
Hi,

first of all, I'm working for Docker, so I'm obviously biased.
But I like sabnzbd and contributed the Dockerfile. Now it would be awesome if you could add a automated build on hub.docker.com so we always get up-to-date sabnzbd docker images on every push to this repo.

If you don't want to, just close this issue again.

**Comment by domibarton** [comment]
Hi there.

I'm already using SABnzbd inside a Docker container and I've created an image for it:

* [https://hub.docker.com/r/dbarton/sabnzbd/](Image on Docker hub)
* [https://github.com/domibarton/docker-sabnzbd](Git Repository)

Have a look at the README. The image is self-updating and supports fast switching between branches / tags. I also compile `par2` manually to support the `-N` flag and added 7Zip support.

If you like we can use the same Dockerfile and start script. The only thing I would change is the UID/GID part. I would update it to use something more dynamic like [this image here](https://github.com/confirm/docker-mysql-backup) where the UID / GID can be set by environment variables.

**Comment by domibarton** [comment]
Btw. if I'm not completely wrong then you're already working with a "proper" git workflow and you're tagging on the `master` branch right?

So what I would do on Docker hub is creating build settings to create all branches and tags. Then mapping the `master` git branch to a `latest` Docker tag. This is quite common on Docker.

If you want I can create the Dockerfile and appropriate start script for you guys and send you a PR. What do you think?

**Comment by domibarton** [comment]
And of course a `docker-compose.yml` file ;)

I would create a new git repository because:

* you can create a proper `README.md` for Docker only
* Docker Hub won't have to build images all the time you're pushing your commits

Let me know if you need a volunteer, I'd love to help. I can make a proposal or you can create a new `sabnzbd/docker` repo me. Whatever you like :)

**Comment by discordianfish** [comment]
@domibarton I already submitted a PR to include a Dockerfile, so all this is there. Somebody with the right permissions just needs to add this repo to the docker hub.

PS: I don't work for docker anymore, so not biased and still think it's a good idea. Docker Hub has it's issues but it's fastest to setup. Of course you could also build the images on some build server and push it to some registry though.

PPS: I disagree with separating the Dockerfile from the repo since then you'll have to manually track when to rebuild.

**Comment by domibarton** [comment]
@discordianfish I just had a look at your Dockerfile. I think we can improve that quite a bit, because you're "forcing" the user to work with your "predefined" settings like UID/GID, ports, etc. 

Especially when you're working with SickBeard an CouchPotato, you've to make sure SickBeard and CouchPotato can move your files. So we should give the user the ability to change the permissions or it's gonna be a bit of a hazzle.

I think you didn't understand me correctly. I love Docker and their Hub and I would absolutely push everything to the hub. I would not recommend to push built images to the hub, I would go for the Automated Builds as well.

But: I think the Dockerfile should not reside in this repo. It doesn't make any sense if you rebuild the whole image just because you changed some bits somewhere in your code, which might be a description update or something else. The other problem is that the README is automatically parsed if you're using Automated builds, and therefore your README lands on hub.docker.com, which isn't very clever. To Docker user wants to know how to "use" the Docker image and doesn't have to know how to resolve dependencies or running SABnzbd manually. IMHO it's quite confusing for Docker users.

I already built a proper SABnzbd image and update it right now for dynamic UID/GIDs. When the image is built (which is Docker Hub with automated builds), every dependency will be installed (even the newest `par2` from source and 7Zip) and the SABnzbd repo will be cloned. The image is self-updating which means:

* `docker restart sabnzbd` restarts your container and updates it to the latest version
* `docker run ... -e VERSION=devel` runs your container with bleeding-edge source
* `docker run ... -e VERSION=0.8.0Beta4` runs your container with the SABnzbd 0.8.0Beta4 tag

So its a lot easier and you don't have to update / push your Docker image all the time. You can use the latest stable version, bleeding edge or make use of version pinning by pointing at a tag. Rebuilding the Docker image is no longer required, except if you want to update the dependencies. Of course you've also a reduced overhead, because the update only needs to download the diffs (git pull) and not the whole Docker image again.

So as long as we've the "self-updating" Docker image / container, we don't need to track anything manually (except new requirements on the OS / Python layer).

P.S.: It's also nice for developers, because they can easily mount their working copy in the container and restart it to test things.

**Comment by domibarton** [comment]
@shypike Can you have a look at the [Docker Hub](https://hub.docker.com/r/sabnzbd/sabnzbd) and [git repository](https://github.com/domibarton/docker-sabnzbd)?

If you're fine with that we could probably create a new repo for your "official" Docker image. Of course only if you're fine with it. I reserved the `sabnzbd` namespace on the Docker Hub, but if you can give me your username I'll add use as owner.

**Comment by discordianfish** [comment]
@domibarton I'm not sure I can follow, but how is your Dockerfile different when it comes to '"forcing" the user to work with your "predefined" settings like UID/GID, ports, etc.'? It looks like you're doing the same.
I also have to disagree about your remarks around auto-updates vs rebuilding of images. Building immutable images from a specific version of code is actually one of the core design goals of Docker, autoupdating breaks that. Beside that, every update in during the runtime increases the size of the container (which is also why it's discouraged to run `apt-get upgrade` and similar things in a container or layer).
The setup can also easily break if there is a change in how sickbeard handles state, like schema or metadata changes which is why your approach of just running `git pull` to update is dangerous.

**Comment by shypike** [comment]
@domibarton I've decided to spend all my availalble time on the fixes needed to make a final release of 0.8.0. For me, this goes to the medium term to-do list.
Other than that, I tend to agree with @discordianfish, there should be a Docker release per official release of SABnzbd, not a "dynamic" one. The latter is too hard to support.

**Comment by domibarton** [comment]
@discordianfish Thanks for your response. You're right with the increase of the size, so it might makes sense to skip the whole self-updating stuff. Of course `git pull` is dangerous if you're looking to migrations and alike. However, SABnzbd and Sickbeard users do the same thing today with their non-containerized installations. They just execute the Python script and point to the existing config / datadir. IMHO updates will made exactly like that. Users stop their SABnzbd/Sickbeard, replace it with the new version and start it again while pointing to the existing config. There's no "migration" script or alike they call. So SABnzbd/Sickbeard already have to catch that today. I think Sickbeard already uses a `git pull` to update itself (if you've activated that in your config) so this isn't exactly a "new feature" in their case. However, I agree with you, automatic updates breaks the "immutable" image thingy in case of SABnzbd and you can't use "controlled updates". Didn't think of that, sorry! In term of UID/GIDs: No I don't do the same. Yes, I create a user/group in the Dockerfile but you can switch UID/GIDs via environment vars in your container. Have a look at the README or init script.

@shypike Thanks anyway for your time! Pretty awesome! Sounds OK to me to build a Docker tag per official SABnzbd release. Though, I would still suggest:

__Documentation__

The current Docker image isn't documented at all. I don't think Docker users are happy to "reverse engineer" the Dockerfile to find out how they can run their own Docker instance. It also seems a bit confusing when Docker users on the Hub are faced with stuff like 

> SABnzbd has a good deal of dependencies you'll need before you can get running.

So IMO we should update the README for Docker usage and try do document it instead of letting users in the dark. 

__Existing configs__

I think people also want to move from their existing setup, so their should be a small topic about how to use the existing config.

__UID/GIDs__

As already mentioned, if users are forced to a given UID/GID they've to tinker a lot. Other containers (e.g. SickBeard, CouchPotato) might need to work with the same data as well and if they've no write-access it gets kinda annoying :) 

__Tags__

As you already using gitflow I would configure the git `master` tree as `latest` and build the rest of it (other branches & tags) with its origin names.

Let me know if you need help, I can try to set everything up and send you a PR. 
Thank you @shypike and @discordianfish for your support :)

**Comment by Safihre** [comment]
Dear @discordianfish @domibarton, is there something we still need to do from our side? It seems to me the docker is up and running and updating?
I'm a little lost what *we* should do.. 
Do we even need this https://github.com/sabnzbd/sabnzbd/blob/develop/Dockerfile? Or does it update itself?

**Comment by discordianfish** [comment]
Ah nice,  looks good and should update on pushes. (if not, check webhooks in gh)
