### ISSUE TITLE
Movie Sorting feature broken in 3.4.0Beta1

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#1928]
With sorting, using %dn.%ext as sort string as far as I know, 
Sab is supposed to unpack to a temporary folder named "Jobname", then rename the resulting file with the same name as "Jobname" and move it out of the temporary folder, in 3.3.1 is worked perfectly. 

In 3.4.0 Beta 1 is skips the rename process entirely and leaves the video file inside a folder named "Jobname".

Without changing config, I simply rolled back to 3.3.1 and it restored the previous behavior.

Most likely related to this change: https://github.com/sabnzbd/sabnzbd/commit/b2cbb8c8d0ab7172c05bd99b08ae51c5c41919d0

This is on macOS, but I really doubt it changes anything.

**Comment by Safihre** [comment]
Just to be able to check, what is an example of a Jobname that you used?

**Comment by Cpuroast** [comment]
I fail to see how this is relevant, sab 3.4.0 Beta 1 is basically skipping the rename operation and is leaving the file in a folder, when it should be renaming it to the name of the parent folder and moving the file out when done.

**Comment by Cpuroast** [comment]
Maybe something relevant to add, all completed folders in affected categories end with * to prevent permanent job folder creation.

**Comment by Cpuroast** [comment]
What happened in 3.3.1 and older:

1.Completed/_Unpack_JobName/Somefile.ext -> JobName.ext
2.Completed/JobName.ext

What happens in 3.4.0 Beta 1:

1.Completed/JobName/_Unpack_JobName/Somefile.ext
2.Completed/JobName/Somefile.ext

**Comment by Cpuroast** [comment]
Here's the relevant section of the debug log where sorting is supposed to do something:

`
INFO::[postproc:431] Unpacked files ['/Completed/_UNPACK_JobName/SomeFile.ext']
INFO::[filesystem:319] Checking if any resulting filenames need to be sanitized
INFO::[postproc:435] Finished unpack_magic on JobName
DEBUG::[filesystem:767] Moving (overwrite: 0) /Temporary/JobName/SomeOtherFile.txt => /Completed/_UNPACK_JobName/SomeOtherFile.txt
DEBUG::[filesystem:877] Renaming "/Temporary/JobName/SomeOtherFile.txt" to /Completed/_UNPACK_JobName/SomeOtherFile.txt"
DEBUG::[filesystem:584] Applying permissions 0o755 (octal) to /Completed/_UNPACK_JobName
DEBUG::[filesystem:584] Applying permissions 0o644 (octal) to /Completed/_UNPACK_JobName/SomeOtherFile.txt
DEBUG::[filesystem:584] Applying permissions 0o644 (octal) to /Completed/_UNPACK_JobName/SomeFile.ext
INFO::[postproc:1063] Removing unwanted file /Users/CpuroastXP/Movies/TV/_UNPACK_JobName/SomeOtherFile.txt
DEBUG::[filesystem:913] [sabnzbd/postproc.py.cleanup_list] Deleting file /Completed/_UNPACK_JobName/SomeOtherFile.txt
DEBUG::[filesystem:877] Renaming "/Completed/_UNPACK_JobName" to "/Completed/JobName"
DEBUG::[filesystem:920] [sabnzbd/postproc.py.rename_and_collapse_folder] Removing dir /Completed/_UNPACK_JobName
DEBUG::[sorting:598] Initial guess for SomeFile.ext is MatchesDict([('title', 'SomeFile'), ('container', 'SomeContainer'), ('mimetype', 'SomeMimeType'), ('type', 'SomeType')])
`

**Comment by Safihre** [comment]
@jcfp?

**Comment by Cpuroast** [comment]
After chatting with @jcfp , mystery solved, I was using the "Movie Sorter" for everything.
3.3.1 and older's implementation basically made the movie sorter act as a fallback when no other sorter was active.
The previous generic sorter didn't do any matching.
And since jobname actually matters for matching with the new version, the appropriate sorter has to be active.

Once I enabled the tv sorter with the same %dn.%ext sort string and enabled the required categories, it behaved as 3.3.1 did.

I would assume not too many people were using it like I was.

**Comment by reallyuniquename** [comment]
@Safihre @jcfp
I've just upgraded to 3.x and I'm so confused. 

So, I enable movie sorting. I set affecting categories to `movies` and set sorting string to `%dn.%ext`. Then I put `Its.a.totally.TV.Show.S09E10.nzb` in the queue. I double check its category set to `movies`. File is being downloaded and unpacked. 

Then SABnzbd suddenly decides it's a tv show and completely ignores my category choice and its sorter. And since tv sorting is not enabled nor defined no additional renaming or sorting is applied. And this is considered expected behaviour. Am I getting this right?

How do I make sure movie sorting settings applied to everything I tag as `movies`?

**Comment by thezoggy** [comment]
a movie wont have S#E# thats a tv series

**Comment by Safihre** [comment]
Your download is not a movie, so it won't sort that as such.
We should probably introduce a General sorter for cases like these where you don't care what type it is.

**Comment by thezoggy** [comment]
unless forced, the sorter tries to guess the content ( https://github.com/sabnzbd/sabnzbd/blob/3.5.x/sabnzbd/sorting.py#L327 )  to figure out which sorter to use (date/movie/tv). debugs show that logic and why it did what it did.

**Comment by albino1** [comment]
I'm having this problem as well.

I have every category set to `%dn.%ext`, and if you have the sort setup as `%dn.%ext` then *no matter what the filename is* it should work.  I don't know why it cares if it's a TV show, movie, or whatever, just rename the file to the job name, that's the whole point of setting it to `%dn.%ext` in the first place.

**Comment by Cpuroast** [comment]
The simplest way I found if all you care about is "Job Name as File Name(%dn.%ext)" is to enable "Series Sorting", "Movie Sorting" and "Date Sorting" with %dn.%ext as the "Sort String" and to select all categories you want it to affect.

The exact same config in all 3 sorters.

This effectively forces the sorted to use the same "Sort String" for every type.

**Comment by albino1** [comment]
I believe that's what I have:

![sab](https://user-images.githubusercontent.com/12164957/162069772-4d9021d6-f723-4968-9196-35c49809e9a3.jpg)

**Comment by Cpuroast** [comment]
no, look again, your "Affected Categories" are different.

**Comment by albino1** [comment]
Movies for Movies, TV for TV, no?

This has worked for literally years and years, so if something changed it's not on my end.  If it's a simple as just changing something though I would happily take that, although I still don't understand why it doesn't work in the first place.

**Comment by Cpuroast** [comment]
I know, but it has changed with Guessit that was added to sab
Guessit parses the file and then determines which sorter to use.
That's why if you simply select all categories for all sorters, regardless of what type Guessit determines the file is, will have the exact same sorting done to it.

**Comment by Cpuroast** [comment]
If you have a job incorrectly assigned to the movie category that guessit determines is a tv show, then that job won't be processed by the movie sorter, it would only be processed by the series sorter.

But as I said, if you aren't doing anything else than "Job Name as File Name(%dn.%ext)"
Just enabled all categories for all sorters with the same "Sort String" and call it a day.

**Comment by albino1** [comment]
Thank you for your help, that does indeed work and solves my problem.  I'm not sure why it works, but it does :)

If GuessIt says "this `movies` category is incorrect, this is in fact a TV show not a Movie" and then moves it (internally?) from the `movies` category to the `tv` category, then shouldn't the same `%dn.%ext` TV sort be applied to it that would be if `tv` was selected in the first place?

**Comment by Cpuroast** [comment]
Guessit doesn't care about categories, only what it identifies by parsing the name of the job/file.

**Comment by albino1** [comment]
Hmm, that seems messy since it's ignoring the intentionally specified user's choice.  If I say something that's named S01E01 is a movie then who is it to argue with me?  Regardless, thank you for the help, I'm just happy to have it working the way it was before.

**Comment by Cpuroast** [comment]
This is the workflow that modern sab does:

Job downloads -> guessit(type) -> series or movie or date -> is the job's assigned category(user tag) enabled for the required sorter, yes|no

if yes, get to work
if no, don't do anything

**Comment by albino1** [comment]
I suppose my question would be why even assign a category at all if GuessIt is just going to bypass it and do whatever it wants regardless of the assigned category.  That seems like unintended behavior.

Also, there appears to be no Special or Switch to disable GuessIt.  I honestly can't imagine a scenario where I would need it as either I'm intentionally choosing Job Name or Sonarr/etc is handling it without any input from SAB at all.  If you can disable Deobfuscate (which I have) then it would seem you should also be able to disable GuessIt so it doesn't contradict people's defined categories.

**Comment by thezoggy** [comment]
A category is used for various reasons, the main one is to segment downloads (api/folder/etc). The sorter stuff isn't forced on anyone (most actually don't use it in lieu of 3rd party apps). You can also apply said sorter per category or multiple categories. And the type of sorter is not the same thing as sab category.

**Comment by albino1** [comment]
Perhaps I'm misunderstanding.

The category is embedded in the NZB file, which is applied by the indexer, it's in the header metadata.  The NZBs come already pre-set with a category from most indexers.  Not all indexers do this, however, and that's what's leading to the problem, as I then manually give it a category myself.

My point is if there is no category set by the indexer, and thus no category in the NZB's metadata, it enters SAB with the category set to `Default`.  That's fine, that's correct.  However, if I then manually change it by hand from `Default` to `movies`, `tv`, `whatever`, it should respect that choice.

**Comment by thezoggy** [comment]
Sab category is on thing. It can be auto set by indexer category (tag) where you set for the sab category. The different sorters is set by sab category. Has nothing to do with the nzb indexer category

**Comment by albino1** [comment]
I'm talking about the category when you put it into SAB, which is pulled from the NZB.

If the NZB says:

`<meta type="category">Movies &gt; HD</meta>`

Then when you put into SAB you get a Sort category of `movies`:

![sab-cat](https://user-images.githubusercontent.com/12164957/162112990-708121da-2347-4e32-b858-d06331d09bc1.jpg)

SAB does that all by itself based on the NZB meta category, I'm not adding that, it's automatic.

**Comment by thezoggy** [comment]
You should read:
https://sabnzbd.org/wiki/configuration/3.5/categories

**Comment by albino1** [comment]
Which part of that says the category is ignored when GuessIt decides its wrong? :)

**Comment by thezoggy** [comment]
When you add a job to sab you can set the sab category. 
When you define your sab categories, beside setting what the name of the category and where to save files, there is the "Indexer Categories / Groups" field. This allows the user to set the sab category based off the indexer categories (which shows up in the nzb metadata). So in your case, it looks like you have a sab category `movies` and in that category you prob have "Indexer Categories / Group" set to "Movies", thus when the nzb metadata for category "Movies > HD" is parsed it knows to use the `movies` sab category. 

Now the job gets processed and the sab category processing/priority/folder etc all comes into play. 
Then once the job is done, if the user has sab's Sorting enabled, then that comes about.

Sab has different sorters, Series/Movie/Date sorting which can be enabled for various categories. I personally dont use sab sorting at all, so none of it is enabled.

For you, it sounds like you have one or more sorting enabled for your `movies` category?
Each sorter can have its own sorting pattern, and not all patterns have the same tokens.. 

If a category has multiple sorters enabled for it, then thats where guessit should be coming into play to know which of the sorters to use. Since you wouldnt want the 'date' sorter trying to be used for 'movie' type and so on. The sab category itself is irrelevant here in the sense that the name of the category could be named 'bob', sab wouldnt know what type of jobs 'bob' would have, from what I understand you told sab basically the category could have movies.. could have series.. could have date. So its doing its job on trying to figure out what.

make sense?

**Comment by thezoggy** [comment]
as i describe above was the usual workflow but taking a quick peak at latest code it does appear that when the guessit stuff was added it now just dicates the sorter type rather than being limted to the sorting types selected by the categories. this seems like an unintended consequence.

as a user i would expect that if I only have the movie sorter enabled and selected for a cat then it should be used. regardless of what guessit thinks. guessit should only come into play ideally when a category has multiple sorters enabled for it and it wants to figure out which one to use.

**Comment by reallyuniquename** [comment]
In the meantime can we get a way to either disable guessit completely or make it aware of whatever category I set my file to? 

The workaround has been posted here but would it cover everything? If I download `garbage.bin` which is not a movie nor a tv show I still want to be renamed to `%dn.%ext`.

**Comment by Safihre** [comment]
Why do you not use Deobfuscate Final Filenames?

**Comment by reallyuniquename** [comment]
Because I want control over the sorting string. I'm sure `Deobfuscate Final Filenames` eventually falls back to something like `%dn.%ext` but I can't be sure. And it still leaves a parent folder. Yes, I know I can set category path to `*` to avoid that too.

**Comment by Safihre** [comment]
I put the request and require refactor in #2143.

**Comment by thezoggy** [comment]
also to note, that the change this caused also causes issues for *adarr which do NOT want the user to have sorting enabled because its renaming the files out from under it.  we should add a note that if the user is using 3rd party apps they probably dont want to enable sorting, and if they do we need to make sure it doesnt actually fire off for the categories they dont have selected

**Comment by Safihre** [comment]
It doesn't fire if not selected. Additionally, *arr will show a warning if the user's has Sorting configured when adding SABnzbd as a Download Clieng. They query SABnzbd settings to make sure of that. Has been like that for a while.

**Comment by thezoggy** [comment]
It was brought up because the warning stopped working on *adarr side after the change
