### ISSUE TITLE
Sorter.detect() different in 3.4 vs 3.3

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#1963]
@jcfp The pre-3.4 `detect()` function would go past every Sorter and apply them if matched and enabled.
The 3.4 `detect()` method first uses `guessit` and only then proceeds to activate the relevant sorter.
So it can result in constructing a Series-sorter, only to realize it's not activated.

I assume this is on purpose, but maybe it's something we should document?
The pre-3.4 would allow sorting to work, even if the "wrong" type was active (Movie-sorting would work on a TV-job).

Triggered by https://forums.sabnzbd.org/viewtopic.php?p=126063#p126063 (and the posts below)

**Comment by jcfp** [comment]
In the old sorting code the movie category served as a fallback if neither date nor series sorting produced a match against a bunch of regular expressions (or were simply inactive), because it came without any 'entry requirements' of its own. That implementation detail is a bug for one user but a feature for another (as witnessed by earlier discussion on irc).

Without the need for backwards compatibility, the sorting would probably look more like the filters on an rss feed than the current split-up between date, series and movies. That would also allow for applying certain sorting strings to every job regardless of whether it fit any specific category, etc.

**Comment by Safihre** [comment]
> Without the need for backwards compatibility, the sorting would probably look more like the filters on an rss feed than the current split-up between date, series and movies. That would also allow for applying certain sorting strings to every job regardless of whether it fit any specific category, etc.

Yeah I was thinking that too. It can even keep backwards compatibility if implemented with a conversion to the new universal way.
