### ISSUE TITLE
Connection Failed with CIFS VFS errors

### ISSUE THREAD

**Issue by juan9999** [sabnzbd/sabnzbd#1965]
I'm having an issue with a docker install on ubuntu 20.04 with apparent conflict with network shares where I move my downloaded files to.

I have a docker stack that has openvpn, transmission, sabnzb, sonar (all routed through the vpn).

When the stack is not running, my mounted network share drive (where I save my downloads) works great. When the stack is running and sabnzbd is active, I get a bunch of server disconnects and get a bunch of CIFS VFS errors and slow response/time outs if I try to say do a ls on a NAS share.

When I delete that stack, suddenly the network share works fine again.

I created a new ubuntu docker host and copied the same config files and ran the stack and had the same issue.

Then I created an alpine docker host, with the same config files and the issue went away!
So I have no idea what the issue is, but it seems like a different unix distro either has a different implementation of docker, or CIFS.
how can I fix/troubleshoot and specifically what does sabnzbd do that could cause such behavior?

**Comment by thezoggy** [comment]
so you have issues with share when there is high load on the system with one docker vs another? sab wouldnt really have anything to do with this. you can prob troubleshoot this pretty easily stressing out various io (disk/network). also wherever you get the docker from they prob have a support area that you can talk to others that also run that docker (since its not something we maintain/control) to see if others have similar issue.
