### ISSUE TITLE
Systray flashing in Kubuntu 20.04

### ISSUE THREAD

**Issue by boscorama** [sabnzbd/sabnzbd#1970]
Finally upgraded to Kubuntu 20.04 latest with backports and sabnzbdplus PPA.

A strange thing happens with the systray when sabnzbd is running -- parts of it centered around the sabnzbd tray icon start to flash once a second.  (see image)
![flashing_systray](https://user-images.githubusercontent.com/2223795/139768740-38eb2142-f425-472c-b4ec-b936e8d4d415.gif)

I couldn't find any mention of anything similar in the other issues (though #1570 seemed close)

Traced it to XApp usage.  Obviously turning off `win_menu` worked but I still wanted the systray menu.  I tried a code change that adds a special switch to basically disable XApp usage in the tray [here](https://github.com/boscorama/sabnzbd/commit/c3c65b8bc38669c378ba52067b4463357691b46d)

It's not PR quality but gives an idea of what I did.

HTH.

**Comment by jcfp** [comment]
Given that the entire taskbar seems to be flashing, this is in all likelyhood a bug in gdk/gobject, whatever is behind the systray, or the window manager. In you run sabnzbdplus in the console, you might see some gdk error being printed every second.

Since we only added xapp because the gtk statusicon functions are deprecated and set to be removed in some future release, I don't think there's much of a point adding a special setting now to force using that very code. That said, I could add a patch on the ppa for 20.04 so the gtk statusicon gets selected over xapp.

**Comment by boscorama** [comment]
Seems entirely reasonable.  Thanks.
