### ISSUE TITLE
[API] Queue could use a total percentage

### ISSUE THREAD

**Issue by johman10** [sabnzbd/sabnzbd#198]
I'm working on a sideproject with Sabnzbd integration.
I was looking for a total percentage of the queue, but couldn't find it.
So I build it myself with:
```
var queueJson = JSON.parse(localStorage.getItem('SabnzbdQueue'));
percentage = Math.round(100-(parseFloat(queueJson.queue.mbleft)/(parseFloat(queueJson.queue.mb)/100))).toString() + '%';
```

Later I thought about adding a percentage for each queue slot and found there was a value for that.
So why not make a percentage for the total queue too?
It would make my code a bit better and cleaner.

Thanks in advance!

**Comment by thezoggy** [comment]
the user (coder) could just as well do this too

**Comment by johman10** [comment]
Yeah off course... but I just found it strange there isn't a percentage for the queue while there is a percentage for each slot. It would just be nice to have a percentage, to make it easier! ;)

**Comment by Safihre** [comment]
So I actually implemented this yesterday for Glitter and realized it's much more complicated than suggested in the first post.
The problem is: What is the 'start' of the queue? In order to give a percentage you need a total number of bytes. Say you download 2 files, after 1 file is finished the total queue percentage drops to 0% again.

You could 'remember' how much you downloaded since the last queue finish? 
But then every time a file gets added/delete you need to update this queue-total..

**Comment by johman10** [comment]
Yeah! I figured that one out too. I ended up using: "[downloaded]/[total queue]", which shows progress but not in percentage. ;)

Still think it would be awesome, it's just one hell of a job to implement.

If people want to check my project out:
https://chrome.google.com/webstore/detail/justab/ahfidkanlmlkhggdgencpoanjkokcfck
https://github.com/johman10/JusTab

I guess I can close this... I'm content with the solution I got, thanks for the comments! ;)
