### ISSUE TITLE
Improvement needed for the Retry()

### ISSUE THREAD

**Issue by TheGeneral007** [sabnzbd/sabnzbd#2042]
Scenario:
Server1 had problems and did not find all the articles needed for each file. 
If I disable Server1 and enable Server2 and use the Retry(), I assume Sabnzbd is just skipping files that are already there (they are incomplete however). It would be very conveniant to delete those files and start that file over again or append the articles to that incomplete file. 
![image](https://user-images.githubusercontent.com/82135186/151161028-de3ee50e-457a-4f7f-b10b-76cc324169de.png)

My workaround shows that this method is working great, when I am first deleting all the incomplete files where articles are missing. 
That was caused by Server1 in the first attempt. So now Server2 gets a real chance.
And then press the Retry(). Now it flawlessly completes the .nzb !!!

This could be a tip for anybody searching for the solution on how to solve this issue, but it would be far better when sabnzbd could be expanded with this improved Retry()-functionality.

**Comment by Safihre** [comment]
Yes, it doesn't work like that.
But it seems easier to just have Server2 set as priority=2 so it's used for all articles that fail on Server1?

**Comment by TheGeneral007** [comment]
Hi Safihre, 
thank you for answering. 

I have tried that as Server1 as prio=0 and Server2 as prio=1, but the results are like I said earlier. It is not filling any articles which are missing from the file and are for sure available on Server2, because I have tested this.

**Comment by Safihre** [comment]
That is the basic working of SABnzbd: if both servers are _active_ and configured as you described it will of course try Server2.
It could be that the post was not yet complete on Server2, if it was a very fresh post.

If you are sure that it is not trying Server2, please enable Debug logging and try the download again.
In the logs we can confirm if it tried Server2.

**Comment by TheGeneral007** [comment]
Ah, ok, very good idea. 
I have another file which wasn't completed and with every retry() it skips to append the articles to the file.

**Comment by albino1** [comment]
So far as I can tell, Retry only does something if you add another NZB to it that contains the missing parts.  Even if you enable previously disabled servers and hit Retry it doesn't actually attempt to download from them.  I've personally never successfully used the Retry option for anything, so I'm not entirely sure why it even exists or what the use case is.  It seems like a legacy feature tied to a behavior that is no longer applicable. 

The easiest way to do what you're asking is just to delete it from SAB all together and then re-add the NZB fresh.

**Comment by Safihre** [comment]
@albino1 is right. To actually really retry only the previously failed articles would be a lot of work for a feature that I don't think many would use that often. Nowadays it's so common for post to either be 100% or 0% available.

**Comment by TheGeneral007** [comment]
@albino1 is right indeed. Especially that it cannot be used to the full right now, because it should handle it a little smarter. 
You don't need an .nzb with only the files you are missing. You can use the same .nzb you have used before and it is smart enough to do only the files that are missing. 
I agree, that I also wasn't satisfied with the result of the Retry(). I tried various routines, but without any luck. 
That's why taking the broken ones out, will give you a succesfull result in the end. Otherwise it will give a FAILED again and again.

Believe me, that my method is much faster, because it doesn't have to download all the files. Only the broken ones. 

That is why I started the request for an improvement, so Sabnzbd will become even better. 

Everyone will profit from this.

If it is difficult to program this, you could for example have a Retry() and in the first window that appears, the ability to have a checkbox to remove/clearout any incompleted files from that subfolder, before the operation begins.

**Comment by Safihre** [comment]
Yes, that's an option.
But I want to get back to an underlying problem you seem to have: if you have *both* Server1 and Server2 enabled it fails, you say that if you repeat the download with just Server2 it succeeds. If that is true, we have a much bigger problem.
So again, the question to reproduce a whole download as described above with Debug logging. We also need to see the original download with both servers enabled.

**Comment by TheGeneral007** [comment]
There is a slight difference. To be able to see if Server2 will continue where Server1 failed to find everything, I will have to change my setup. With finding everything I mean also appending to a file which was found, but didn't get all packets/articles, so the files are smaller than they should be. 
I will have to do this another time/day.
And perhaps make it a different issue ? 

The current setup is ready to do a test and create a logfile, if that's more clear for the Retry(), but I rather hold the data ready to test an update to the program.

**Comment by Safihre** [comment]
I don't need a retry log:
I feel you are doing things with the settings that you shouldn't, and that's why you have to do these complicated steps that shouldn't be needed at all. 
So that's why I asked already multiple times for you to just have the 2 servers enabled when you download. That should do exactly what you want, and if not, then that's the bug we should be fixing. Not changes to Retry.

**Comment by TheGeneral007** [comment]
Well, you're the boss.

**Comment by TheGeneral007** [comment]
I have tried, but Sabnzbd had 25/25 connections with Server1 and was already using connections 7/50 from Server2, so was never in the circumstance where we could show/prove that Server1 had incomplete files. 
Because Server1 and Server2 were enabled and Server2 was a different provider which had the complete files, there was no problem to show.

I stated it differently before and I still do, that I had a lot of almost complete full files from Server1, just fragments were missing.
And like many others you then obtain blocks from a provider and fill the gaps with the data from Server2.
If it is too difficult to capture only the fragments of the files that are missing, then the second best way is to remove only the incomplete files and then continue taking data from Server2.

Above statement is still an oversimplified situation. Please keep in mind that I have tried this with Server1, Server2 being different providers and both had glitches in their files. So then there had to be a 3rd Provider. 

And then you need the improved Retry() as a lifesaver, to finish the job efficiently.

**Comment by thezoggy** [comment]
i think there just may be some confusion on the scope of what retry is doing?
>> config > switches > Maximum retries
if article is missing from provider, retry that provider for the maximum amount. with 'optional' for the server level coming into effect along with back off logic if its flakey.

now once we ran through all the articles missing we move onto next provider from the pecking order and repeat.

it sounds like what you want is logic to try the next provider rather than the same provider or be more async rather than sequential.  

while there prob is some speedups in trying to do things a bit more concurrently but that means more connections.. which can cause higher cpu and if people setup the same provider (like eu + us as different priority) then you can run into exceeding connections for usp due to it not being sequential. but all of that then adds to a bit more complexity which i'm not sure is worth the gain just because most people seem to like the base logic of try in order that way they can put blocks after their main and have a bit of control that way and only hit blocks when they really do need to.

**Comment by puzzledsab** [comment]
This may be related to the problem described [here](https://www.reddit.com/r/usenet/comments/q7cco5/retention_and_completion_differences_between/), where the server will sometimes return an article and sometimes say not found for the same article. A workaround could be to add the same provider multiple times at different priority levels so that missing articles are requested more than once. If the provider has several locations then a setup like this might work:
```
Pri | Server                | Connections
  0 | eu.usenetprovider.com | 30
  1 | us.usenetprovider.com | 9
  2 | eu.usenetprovider.com | 3
  3 | us.usenetprovider.com | 1
```
This should make the last servers lag behind, which is intentional. If the problem is that the articles need to be loaded into some kind of cache then the servers will have more time to do so before the next request. It also leaves the most connections for the primary server. You could add the same servers even more times but there are probably diminishing returns.

When it comes to retrying I agree that there should be a way to retry incomplete files. I never use it so I'm not entirely sure how it works but, if it retries all missing files then the easiest way is probably to automatically delete the incomplete ones. Possible ways of doing that are keeping a log over files with missing or bad articles or doing a par2 check and delete all broken files.

@thezoggy: The issue is about the retry option you can click on if a download has failed. The configurable number of retries is not related to this. Also, it's only used for servers that don't respond at all for some reason. If the server responds with not found then SABnzbd will not try again.

**Comment by Safihre** [comment]
@puzzledsab thanks for the link, it's indeed something we've run into before where users claim the SABnzbd fails to download something that reader X does download.

I also have some basic idea of how to implement improvements to Retry:
Based on the NZB we know from all files their expected size. If the file we already have is 10% or more smaller than indicated in the original NZB, we just try to download that file again. We could make that behavior optional in the Retry window.
And should the file on disc be deleted, or just kept next to the retried one?

**Comment by puzzledsab** [comment]
I agree that it would be better to keep broken files and add a .bad extension or something. That way they could be included in the next par2 repair in case they contain anything that fails on the retry.

I'm not sure about guessing file size, though. It wouldn't work for postings that haven't been put in a split archive like RAR or 7zip, or if there are multiple archive sets with different sizes. I also think requiring 10% missing is too much. I would prefer to retry everything that is missing anything at all to increase the chances. It's OK if it's configurable so I could set it to 100%.

**Comment by thezoggy** [comment]
if the server says article not found then why would we retry on the same server (as retry happens pretty shortly after previous, so its not like its going to have much impact if the sever was just having propagation delays or something). 

and yes, most of us setup the same provider in different region just because of the fact that different ones process dmca at different times so its more for that. but then also the inverse when it goes to populate from upstream (if poster isnt posting to that backend or if its a reseller). 

i personally dont see what your trying to 'fix' since from my pov sab seems to be doing very well. looking at my sab history, last time i had something failed to complete was 2017 :x

**Comment by albino1** [comment]
Many servers only backfill when the data is requested, so if you request something and they don't have it locally they then have to fetch it from Omicron/etc.  I'm not sure how they report it to the client, but it could be reported as unavailable only to then become available 30 seconds later after it's been retrieved.

**Comment by puzzledsab** [comment]
@thezoggy : As I said, even if it fails it might have it the next time it is requested. You wouldn't notice it if no downloads are failing or you don't retry but it's confirmed by several people, including the first comment from a person who has done extensive testing [here](https://www.reddit.com/r/UsenetTalk/comments/q7memc/retention_and_completion_differences_between/). Maybe the frequency of it depends on the age and popularity of the articles that are requested.

@albino1 : The server that would fail randomly in the test was Newshosting. It's owned by Omicron and possibly the most direct frontend you can get for the Omicron backend.

**Comment by thezoggy** [comment]
some usp do a hot+cold setup. where they have stuff locally only for x days and then everything else is cold. if a user requests something from outside the hot age then it has to fetch it from cold storage to make it warm then available. so that scenario is probably what you are talking about..  which is somewhat niche to a specific provider (but maybe more as less and less people run their own backend).   

now how to deal with it, sounds like you want sab to try and do a pre-fetch to kick start that process. wait a delay then try for reals.   back in the day we had a option to do the pre-check but i'm not sure it'd would work for this setup.. of course you could always setup the same server multiple times to simulate what you want (assuming you can afford the delay + connections).

**Comment by reallyuniquename** [comment]
So, what's the workaround?

Typical scenario is you have a failed job and you've just added a new server or maybe renewed an old one. How do you re-download only those files that have missing articles? Is manually checking and deleting incomplete files the only way here?

What does `Retry` actually do to incomplete files and missing articles if you don't supply additional NZB? Does it even matter for something besides post-processing?

**Comment by Safihre** [comment]
There's only the manual workaround. And it can redo post processing, in case of full disk or something. 
Retry doesn't do much indeed.
