### ISSUE TITLE
Fix versions in `requirements.txt`

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2047]
So far we have left the versions in `requirements.txt` to just be "whatever you have".
But we keep running into problems with our SABnzbd releases where dependencies have updated between our release candidate and the final release (see #2045 and #2046 for example).
Maybe it is better if we start using fixed versions for our dependencies and let dependabot update them when new versions are released? This way we can have a clear record of where things go wrong.
We will also have to list significant sub-dependencies, like the `jaraco.*` ones and `cheroot` for example. 
I already have to do this for the Synology release. The list is not _too_ long: [this](https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/src/requirements-pure.txt) and this [one](https://github.com/SynoCommunity/spksrc/blob/master/spk/sabnzbd/src/requirements-crossenv.txt).

@jcfp / @thezoggy / @sanderjo Your thoughts?

**Comment by thezoggy** [comment]
For docker usage it makes the most sense to be explicit to have ultimate control and prevent issues. It also makes sense for our usage as most don't install their own requirements (binary builds). 

The only real negative is those that would install from source and not have an isolated py env for sab and then might have some version conflicts.. but that's not our issue.

**Comment by sanderjo** [comment]
Yes, it seems we have to.

I can think of the following the side-effects
* if you fix things to a version, you also have to think & test when/if you switch to a newer version.
* what does this mean for Linux users installing python libraries via their package manager? That is out of control of requirements.txt, so ... put into SABnzbd.py itself a version check too ...? Because: we now do know python library versions that are incompatible / buggy.

**Comment by thezoggy** [comment]
the whole dependabot part of it solves the if we update does it break sab from starting up.. because it wont pass the check as it couldnt run the test set. overall it takes so many issues off our plate if we pin what everyone uses so if there is a bug we know exactly what version of the dependency/combination and can update to work around it. 

the lack of isolated env and running into version conflicts would be the only thing i could see as a negative but those that actually run sab from source and install their own dependencies is probably pretty slim  let alone its not like they cant just move to a pyenv/virtualenv setup.  

we have some basic checks for stuff in sab .py code but its mainly needed because we didnt enforce the requirements for everything. case in point is cherrypy.

**Comment by Safihre** [comment]
Done: 846c2761f6f6b0d82eaf487d42e68723b12e776a
