### ISSUE TITLE
nested asn1 error

### ISSUE THREAD

**Issue by puzzledsab** [sabnzbd/sabnzbd#2050]
Apparently some people are getting this error with the new version. I think it's because of a problem with broken certificates that users can't remove, described here: https://bugs.python.org/issue35665. There is an example of a workaround I think SABnzbd can use here: https://github.com/yt-dlp/yt-dlp/pull/1118/commits/599ca418ac75ab1c0baf97f184f32ac48aa759ed

I think it depends on creating the SSL context more explicitly instead of using `create_default_context()`. I'm not entirely sure what code is needed to replace it.

**Comment by Safihre** [comment]
Do you have more details? Where are the reports?

**Comment by puzzledsab** [comment]
https://www.reddit.com/r/usenet/comments/sgybgs/sabnzbd_350_update_available/

**Comment by thezoggy** [comment]
Tls 1.2?

**Comment by thezoggy** [comment]
It just sounds like there is some usp with busted certs or user has jacked up ca store (like may have really outdated win xp/7 ?) But not much info to go off of with that reddit link.

**Comment by jcfp** [comment]
It seems that issue is triggered by bad certificates in the operating system ca store (most notably one issued by the government of serbia). Upon encountering a broken ca cert python fails to create an ssl context altogether, which is why the issue happens with any usenet server.

In 3.5.0, sab does `ssl.create_default_context(ssl.Purpose.SERVER_AUTH)` vs. just `ssl.create_default_context()` before, but _SERVER_AUTH_ was already the default purpose anyway. So that change shouldn't be relevant.

**Comment by thezoggy** [comment]
i see people on other repos talking about running into this with certs from Serbian where openssl update basically stopped handling the bad asn (integer has invalid encoding / extra padding) and now it doesnt. then also happens with negative serials, all this back from 2019/2020 timeframe...

**Comment by Safihre** [comment]
Closing this as "exotic".
