### ISSUE TITLE
0.8.x ?

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#207]
some noteable changes in the latest newsbin that sab should also adopt:

* All SSL connections are now TLS 1.0 instead of SSLv3. Drops back to SSL if the news server doesn't support TLS

* Improved AutoPAR functionality, better repair capabilities.
- A second retry will trigger a PAR to download to keep things going.
- If 98% of files have downloaded, and PAR2 files exist, the first retry will trigger assembly.
- If Newsbin retries with less than 98% of files already downloaded, it will continue retrying until 90% of files are downloaded.

**Comment by shypike** [comment]
- SSL: 0.8.0 is already defaulting to TLS
- Improved AutoPAR. What's that? We're stuck with par2cmdline variants. Maybe they have something better, but likely closed-source.
- Second retry: we already do that
- 98%: not sure what it means. SABnzbd already starts a verify when all normal files and one par2 are in. In fact 0.8.0 has the option to always download everything because multiple runs are inefficient.
- I don't understand this one
