### ISSUE TITLE
Feature Request: Option to skip par2 repair

### ISSUE THREAD

**Issue by willhughes-au** [sabnzbd/sabnzbd#2073]
It would be useful in some scenarios to have an option whereby no par2 repairs would be attempted. 

For instance, on under-powered devices - it may be preferable for the user to simply consider the download failed and download it again.

I've seen this discussed elsewhere on other forums, repeatedly.  I can't see any Issue here on Github relating to it, but perhaps I missed it. 

The work around for me at the moment is to have a cronjob execute `pkill -9 -f 'par2 r' -e` every minute, so that SAB has some chance of progressing through the queue.

**Comment by sanderjo** [comment]
When you add the NZB, just select  Post Processing -> Download

**Comment by puzzledsab** [comment]
Setting download only would also skip post processing, which is not what he wants. I've looked into it and I think the simplest solution would be to add another special flag that makes sure SAB doesn't try to repair or download extra PAR2 files. It would either stop after the quick check or do a "par2 v[erify]" instead of "par2 r[repair]". What do you think, @Safihre ? Too much of an niche feature? Other ways to solve it?

**Comment by willhughes-au** [comment]
@sanderjo @thezoggy - Thanks for the response. 

Unfortunately your suggestion to just use Download won't work for my use-case. The other tools that integrate with SAB still expect that the RARs have been extracted and deleted.

While I suppose I could write a post-processing script that does this, I can't help but think that it's better to just have this as a hidden advanced option in SAB, as @puzzledsab  has suggested.  I don't mind if it's just "never call par2" - I'd be okay with the extraction failing if the RARs are not valid. 

My cron task is a hacky work-around, and prevents anything else using par2.

**Comment by sanderjo** [comment]
So you want to not run par2, and still run post-process and/or offer the result to other programs? Do you want the rar-files to (have been) deleted?

I know par2 repairing can horribly slow on slow devices (so you want to say "don't do that, just abort", but I cannot imagine how the above would a useful, user-friendly thing.

Anyway:
Maybe these hints are better than your crontab pkill:

* on your slow device: make par2 / par2repair a fake exectuable that always says "OK". Or maybe remove par2 ... and check what SAB thinks about that.
* before https://github.com/sabnzbd/sabnzbd/blob/develop/SABnzbd.py#L444-L451 let it point to some always-ok-executable
* prepend `par2` with a `timeout 60` so that par2 will never run longer than 60 seconds.

**Comment by thezoggy** [comment]
users can set extra par2 params which may or maynot help with the user issue:

config > switches > Extra PAR2 Parameters

with how fundamental par is to todays nzbs.. I'm not sure having some sort of job option to skip par logic or have some sort of special option turn it off would be very useful to most.

**Comment by Safihre** [comment]
Agreed.
We provide the path to the par2 executable as a environment variable to all post-processing scripts (see the wiki help page).
With that you can achieve any custom checks.
You can also disable "Post process only verified jobs", then par2 failures will just be ignored. But it will still verify and report everything as successful.
