### ISSUE TITLE
Push a stable version to snap latest/stable

### ISSUE THREAD

**Issue by jobe08** [sabnzbd/sabnzbd#2095]
Thanks for pushing a fixed update. The problem I have right now is that the latest/stable is listed as 3.6-develop and the application itself identifies as "develop" in the version api. 
This causes issues with sonarr - sonar then assumes its version 1.1.0 and expects values for the download dir in an old location (which going by the code was moved with 2.0 or so to fullstatus)
https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L338-L346
https://github.com/Sonarr/Sonarr/blob/0a2b109a3fe101e260b623d0768240ef8b7a47ae/src/NzbDrone.Core/Download/Clients/Sabnzbd/Sabnzbd.cs#L219-L230
could you please push a fixed stable version (with a version number and not "develop" to the stable channel so that sonarr works again with sabnzbd ?

**Comment by Safihre** [comment]
The snap's always had the version set to `develop`, this is nothing new.
There's also nothing I can do about that because the stupid system of Snapcraft only supports one git branch (develop) to build snaps from. It has this whole setup of release channels on their store, but no support for it in their git integration.
We should never have supported snaps in the first place.

**Comment by thezoggy** [comment]
this should be fixed on sonarr side shortly - https://github.com/Sonarr/Sonarr/pull/4912
this can be closed

**Comment by Safihre** [comment]
Closed in 2424682718b1c0dc750d1acf9f67b230139e62d0
