### ISSUE TITLE
slow downloads - stop, remove and mark as failed

### ISSUE THREAD

**Issue by skapytek** [sabnzbd/sabnzbd#2138]
Hi,
i have a long queue and some of the nzbs cant be downloaded or with very slow speeds and my queue gets longer and longer.
Is it possible to add a feature when a download get for example under 1mbit for 10 sec sabnzbd will stop the download. remove it and mark it as failed so radarr, sonarr,... can search for another release?

**Comment by thezoggy** [comment]
There different switches and things you can do to optimize what sab is working on. You could try to make a pre-queue script to do what you want but ultimately you should fix what causes the backlog/long queue in the first place.

**Comment by Safihre** [comment]
Indeed, what @thezoggy described. 
I don't know how many servers you have? Because if you have more than 2, it means Sab wil have to check every server for the article, and if the server is slow, this can take ages. 
It's only beneficial to have many servers of they are all very fast and reliable. 
I understand your feature request, but it's not easy to implement.
