### ISSUE TITLE
Create a General sorter

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2143]
Based on discussion in #1928.
Only if GuessIt agrees that something is the right category ("Movie" or "Serie"), the sorting will be applied.
For the general sorting like ` %dn.%ext` this is not important.

We should probably refactor Sorting to no longer have separate sorters, but to just have 1 type of sorter that can have a Movie or Serie hint. 
Then we should also allow to have any number of this general sorters, in case people want different sorter per category.

**Comment by jcfp** [comment]
I agree moving to a generic sorter is a good idea, and in fact considered doing this when converting to guessit. Only held back at the time because there were enough changes already in code with zero unittests cover, and didn't want to risk too much of a mess.

Generic sorters could be defined (and tested against a mock job name) in the sorting config, with the option to restrict them to jobs hinted by guessit as series/date/movie; these generic sorters then 'applied' at category level (in the category settings I guess?).

It would be nice if existing sorting settings were converted with the movie/series/date hint set to mimick current behaviour; otherwise, users would have to redo their sorting setup. That begs the questions what to do when categories overlap between the current sorters, i.e. when a single category is active/selected for multiple (current, non-generic) sorters.

**Comment by Safihre** [comment]
That's some wild layout, I hope we can improve that 😁

I also started on it a few weeks back, but gave up quickly.

**Comment by Safihre** [comment]
@jcfp How is the work progressing? 💯

**Comment by Safihre** [comment]
@jcfp any updates here? 😎
