### ISSUE TITLE
[Feature Request] Post-Process Again, Change Category and ReDownload

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2170]
NZBGet has these 3 functions that I use quite often and it would be great if those features were availabe on Sab. 
`Download again`
Basically the Download again is used when you delete the file and want to redownload the content. The .NZB files are usually in some folder, so it makes more sense to reuse that local NZB instead of going back to redownload from the Indexer or manually finding the file on disc.
`Change Category`
When drag and dropping NZBs, a default category is usually used which is specified in the settings, with its own processing config. More often than not, the default category is not where you want the download afterwards. So changeing the cat after download is a useful feature.
`Post process Again`
This is used after download for whatever reason you would need to rerun the post processing. Maybe it failed initially or whatever. I use it after changing the category after download has completed.

**Comment by albino1** [comment]
FWIW, you can Change Category right now.  If you hit the monkey wrench icon at the top and go to Web Interface you can set your Extra Queue option to Category to always visually see it.  To change it you can hit the down arrow on the right and pick a new category from the drop down, or do multiple operations by hitting the three horizontal lines at the top right of the queue to show more options.

**Comment by ItsME6969** [comment]
Unfortunately it only works while in que. In NZBget all 3 work even after download. Nonetheless thats pretty neat too.

**Comment by albino1** [comment]
Ah, I see, wasn't aware of that. Interesting idea.

**Comment by Safihre** [comment]
- Download again: we have the `.nzb backup directory` for that, since we don't store the NZB after finishing the job. Where would we put the NZB after a job completed successfully?
- Change Category: this would be the same as Post process Again but with a different category?
- Post process Again: for failed jobs we have Retry, for non-failed jobs I don't understand how this could work? The file is already repaired, unpacked, maybe a script is activated. How would it post-process anything again? All sources files are lost already.
