### ISSUE TITLE
Feature Request: Track when server download speed is bellow a certain threshold

### ISSUE THREAD

**Issue by SweetMNM** [sabnzbd/sabnzbd#2216]
This is the idea:

Feature is optional and thresholds can be manually configured.
After a certain defined amount of time that a server speed is bellow said
threshold action is taken.

First threshold will be higher and will log a warning and optionally notify that a server is being slow.
Second threshold will mark server as failed (I mean at some point low speed is practically not downloading).
Retry servers after a certain amount of time and check if the speed issue is fixed (this I believe is already a feature for other server errors)

I am making this issue after yesterday where I had servers downloading at 500kb/s due to some
cloudflare outage (presumably). It didn't affect all of my servers so with this feature downloads will
continue fine using the functioning servers. Without my manual check and intervention SAB would
have continued downloading at 500kb/s and the download would probably have never finished until
the servers fixed the issue.

I don't mind tackling this feature my self, the best place to implement the check from a quick
look at the source code would be in the bpmmeter in the update method, correct?

Looking for feedback about the feature and opinions, thanks!

**Comment by Safihre** [comment]
I understand the source of this request, but I don't think it's a good idea.
Because servers can also be slow when going through articles it doesn't have. Or for very old articles that are on their slow storage. I've often seen my main provider drop to 20MB/s instead of 100MB/s on older stuff, while it can be 50KB/s when articles are missing.

We already have mechanisms in place to disable servers based on the statuses they return or if they are unreachable/timeout. I don't think this is a feature that has value to add and also a feature that has to be maintained in the future.

**Comment by SweetMNM** [comment]
Understood
