### ISSUE TITLE
directory_is_writable_with_file special characters not an invalid file name on any filesystem

### ISSUE THREAD

**Issue by Sprooty** [sabnzbd/sabnzbd#2234]
As per https://github.com/sabnzbd/sabnzbd/commit/df8859d49e27daefbdc413c491b06355f621de25#r77570581

I tested creating file "**sab_test \\ bla :: , bla.txt**" on Ubuntu 20.04.4; the file is not created as i would assume the test expects

touch sab_test \\ bla :: , bla.txt
-rw-r--r--  1 root    root           0 Jul  3 23:12  sab_test

touch "sab_test \\ bla :: , bla.txt"
-rw-r--r--  1 root    root           0 Jul  3 23:12 'sab_test \ bla :: , bla.txt'

Apologies i am not a Linux or code expert, but to i am not sure the test is valid and this means it will always fail when run.

Logic for raising this case is that this test is written due to issues with windows mounts on Linux, however if the test would fail on Linux i do not think it is a valid case.

**Comment by thezoggy** [comment]
per: https://www.reddit.com/r/SABnzbd/comments/vpooww/directory_is_not_writable_with_special_character/ieqnvvt/

The problem is unrar. When run on a Linux host, it doesn't know that the path you are extracting to is a Windows share. So if the archive that it's unpacking contains these special characters, the unrar will fail. Even if you enable "Make Windows compatible" in Config Switches. There is no switch to unrar to force it to produce Windows compatible filenames (it will produce those when running on Windows), we contact the unrar authors to confirm that.

So that's why this check is warning you that this can happen.

**Comment by Sprooty** [comment]
@thezoggy, i agree with the logic of doing the test, but i am not sure the assumptions around file names are correct. If we assume a Linux only use case, i am not sure the file names used in the RAR test case valid use cases,

https://github.com/sabnzbd/sabnzbd/pull/2166#issuecomment-1113985593

**Not valid**
Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt"

**valid**
'Lorem ipsum dolor sit amet, consectetur adipiscing elit \ blabla \ dead::beef:0.txt'

If you are confident these file names are valid and supported in Linux, i'm happy there is no issue to be resolved.

**Comment by Safihre** [comment]
The `"` are not part of the test filename, they are not written. They are just the Python string delimiters.
The string we try is: `sab_test \ bla :: , bla.txt`

**Comment by sanderjo** [comment]
> If you are confident these file names are valid and supported in Linux, i'm happy there is no issue to be resolved.

Yes, they are, like your second test in your opening post proves.
And yes, you need quotes or double quotes around it, because of the spaces in it.

Filename from an actual download:

`[N3wZ] \T1OhXJ245333\::[PRiVATE] \9`

So: spaces, : and \ ... therefore the test by SABnzbd.

**Comment by Sprooty** [comment]
Validated above; closing issue.
