### ISSUE TITLE
Only allow Config-backup to the local device

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#2261]
The Config-Backup option creates a very simple way to just steal all credentials from an exposed SABnzbd instance.
Should we no longer allow the download of the backup, but let the user pick a folder on the filesystem where we export the backup?

This does introduce new problems in terms of permissions: are we allowed to write to a directory that the user can access?
But we could for example default to the Complete folder, since we can assume the user has access to this.

Or: are we being overprotective of users that, after all the warnings that SABnzbd gives, still expose their instance to the internet without a password?
An additional 'attack vector' raised by @thezoggy is that API-keys (which allow full access to SABnzbd thus also to the Config-Backup) can also leak from Sonarr instances or indexers where the user has put the API-key for integration.

Thoughts @puzzledsab @sanderjo @jcfp @inpheaux ?

**Comment by thezoggy** [comment]
The backup folder could just be another folder like admin or just a subfolder in admin. The backup Ip should just be named with version and timestamp so it makes it easier to know when/what it's a backup of.

**Comment by Safihre** [comment]
The feature was introduced because for users it was too difficult to reach the administration folder, for example on a NAS.

**Comment by puzzledsab** [comment]
Another option is to never allow downloading from external IP addresses.

**Comment by Safihre** [comment]
@puzzledsab can't that be easily avoided by setting `local_ranges` to your (the attacker) external ip range?

**Comment by puzzledsab** [comment]
@Safihre, I was thinking about only allowing the generic internal ranges (127.*, 192.168.* etc.). If that's not possible then it probably won't work. Some pros and cons:
Limit to internal IP range:
\+ Seems easier to me. The user can immediately put the file anywhere.
\- No way to get the backup if the server is only accessible from external IP addresses.

Download dir:
\+ Should work for everyone
\- The user will probably have to copy it elsewhere because it will still be on the download server. I don't backup that dir because it's not important and can contain a lot of data.
\- The backup will be available for everyone with access to that dir. Some users may want to allow others to access the downloaded files but not the sab instance and config.

**Comment by Safihre** [comment]
I'm starting to lean towards the download dir, with in the Config a button to create the backup so indeed the user can be in control of when one is created and move it away from the download dir.

**Comment by thezoggy** [comment]
some thoughts

to make things safer with current implementation:
- disable the download backup if no sab auth is set / only accessing outside private ip space...

would be a bit nicer if the file was versioned+dated so a bit of context is added:
example: `sabnzbd_backup_v3.6.1rc1_2022.08.06_17.34.42.zip`

which makes it less likely people would just replace an existing backup by accident of the same name / save them from having to dig into the zip to try and gleam what version/when it was for.. as the actual zip modified/creation time may not be reliable alone to figure it out.


about storing the file locally instead of serving it up remotely there are pros and cons to no matter where we want to put it.

- store in admin folder //  guaranteed sab has access.. but if the admin folder gets corrupt it also takes out the backups.
- store in download folder // some people nuke/change download folders as they assume the sab download folder is just a temp holding place while their script/3rd party apps move them to the final spot. also having to guard against people setting a category to the same thing as the backup folder name.
- store in arbitrary folder that user sets (like other folders we set via startup arguments / expose via gui) // way more flexibility for the user, especially for seedboxes/complex docker setups.

**Comment by sanderjo** [comment]
> * disable the download backup if no sab auth is set / only accessing outside private ip space...

I thought of this too, but an outside attacker with access to an open SAB interface can then first activate auth, and then download the config. Thus defeating the objective.

> would be a bit nicer if the file was versioned+dated so a bit of context is added: example: `sabnzbd_backup_v3.6.1rc1_2022.08.06_17.34.42.zip`

I like the date in the filename. I think the SAB version in the filename is overdone / not-needed
I would also like: SAB automatically saves a config each day/week, or before any change (and then also with time in it)

> store in arbitrary folder that user sets (like other folders we set via startup arguments / expose via gui) // way more flexibility for the user, 

Yes, I like that. With default set to Complete. It must be made clear to the user it's on the remote the machine running SABnzbd. No problem with local SAB, but for NAS/VPS users it can be confusing "Why can't I choose my local system folder?"

> especially for seedboxes/complex docker setups.

Ah, yes
seedbox ... yes, the user will have remote access to the Complete folder, because he accesses his real content download that way. 
docker setups. Then it must be an host exposed folder, which is indeed often Complete

**Comment by Safihre** [comment]
Adjusted the filename to match the *arr style backup filenames.

**Comment by Safihre** [comment]
Applied changes.
Also added option to create a scheduled backup.
