### ISSUE TITLE
ArticleCache not being used??

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2269]
This has puzzled me for a while but I thought this would be a good time to address it. I run both sab and nzbget mostly because of speed issues. I literally have the same exact settings on both but sab has always been slower with the download...3-4x slower.

Remote Server 10gbps connection with lots of RAM
100 connections between 3 providers on Both
ArticleCache set to 8GB on Both
DirectWrite/Direct Unpack on Both

nzbget maxes out the whole 10gbps connection--~`8800mbps`
................
![nzbgetSpeed - Copy](https://user-images.githubusercontent.com/89707006/184742375-5ac3927d-fb1e-49b0-ae48-04b62735558c.jpg)
....
sabnzb--~`1200mbps`
...
![sabSpeed - Copy](https://user-images.githubusercontent.com/89707006/184743611-eae6338e-8dc1-4de4-9fcc-e45e30d440a3.jpg)
....
looking at the system stats it seems that sab is not using the memory allocated for the ArticlesCache and might be downloading and directly writting to disk
.....
sabnzbd
......
![sabMemUsage - Copy](https://user-images.githubusercontent.com/89707006/184744816-e1341fe2-cc47-4e6a-80f4-789a02bbbbb2.jpg)
.....
nzbget
......
![nzbgetMemUsage - Copy](https://user-images.githubusercontent.com/89707006/184745074-9013a65f-1e14-48f6-9f9a-c67fcbe0c2f4.jpg)
......
![sabSettings - Copy](https://user-images.githubusercontent.com/89707006/184745241-5025b4b3-9863-437a-9f14-f2ede1c4e1b6.jpg)

.....

So what could be the cause?

**Comment by sanderjo** [comment]
Remarks:

* I would not set a bandwidth limit in SAB
* is NZBget using more CPU power than SABnzbd? Is SABnzbd withholding?
* status-Wrench: what used cache is shown there during a download?
* also status-Wrench: if CPU or DISK is bottleneck (and not Internet), SAB will tell so there.

See the `Download speed limited by  Disk speed (15x) `in my case:

![image](https://user-images.githubusercontent.com/1273502/184809382-3174e1da-6d36-418d-ab02-1ef62e5af1aa.png)

**Comment by ItsME6969** [comment]
@sanderjo disabled bandwidth limit....this is what i got...when doing the 10gb test the used cache hovered below 100MB the whole time

![Screenshot 2022-08-15 235310 - Copy](https://user-images.githubusercontent.com/89707006/184819810-89075b60-dd60-4f13-9e1d-51ad16bf790a.jpg)
.
![Screenshot 2022-08-15 235029 - Copy](https://user-images.githubusercontent.com/89707006/184819849-23881791-ac03-472f-934c-6aa2e444c50a.jpg)
.
![Screenshot 2022-08-15 235029 - Copy](https://user-images.githubusercontent.com/89707006/184819879-f2d2f832-e0df-4b82-86c3-91f9cd540bc9.jpg)

**Comment by sanderjo** [comment]
What a low System Performance (Pystone). Less than my Celeron (which does 95.000), and much, much less than my i3 (300.000 or so). What is your System performance if SAB is not doing anything?

Ah: Intel Xeon E5-2673 v3. We see strange things with old Xeons. Is SAB running directly on the OS, or in a docker or VM? If docker: you can run the docker in priviliged mode, which will give much better performance.

**Comment by ItsME6969** [comment]
7.97 | 9.25 | 10.10 | V=144M R=110M
> Ah: Intel Xeon E5-2673 v3. We see strange things with old Xeons. Is SAB running directly on the OS, or in a docker or VM? If docker: you can run the docker in priviliged mode, which will give much better performance.
Thats where I'm not sure. It's a remote server that I rent and SAB is installed via `their` one-click script so I have no idea how it is installed and whether or not. My numbers are just in comparison with nzbget installed in the same system via their script so it could indeed be some problem with the installation method but honestly idk.

**Comment by Safihre** [comment]
Oke let's check and explain a few things:
What SABnzbd version are you using? Is it 3.6.0? It's listed on the About window or the first page of the Config. 
When you hover over the CPU information in the Status window, it will say at the end which SIMD instructions it's using. For example SSE2 or AVX, what does it list? 

Indeed, SABnzbd will write the decoded data directly to the disk. Not in a cache file, but directly to the target file. In NZBGet this is called Direct Write, which might be disabled on your system. 
This way we will prevent a huge memory buildup if the disk writing cannot keep up with the decoding speed. 
This is exactly what you see with nzbget in your example: yes, it has downloaded at 1100MB/s but it has kept all the raw data in the memory and will then spend time after the download has finished to actually write data to the disk. If you were to download a 100GB file, will it still sustain such speeds? I doubt it, because the cache fills up even in NZBget. 
For the 10GB test download, how much slower is the total time between SABnzbd and NZBGet?

**Comment by sanderjo** [comment]
Ah, ok, I thought you were running a Xeon at home. 

SAB's sabnzbd.log will tell if it's in a docker:
Dockerized = False
or
Dockerized = True

But: I would say that as long as your "System performance (Pystone)" is so low, there is not much you can do to pump up SAB's download speed. Maybe the Xeon is much used by others, or the VPS probider is limiting your usage.

Per Mbps download, SABnzbd needs more CPU power than NZBget. For most cases that is not relevant: SAB on a modern Celeron can saturate a 1Gbps link. However it is relevant where CPU power is very limited compared to available Internet speed. So: a slow NAS on a 1Gbps link, or (your case) slow CPU on a 10 Gbps link.

It's weird SAB's wrench does **not** say CPU or Disk is the bottleneck.

**Comment by ItsME6969** [comment]
sorrry for the delay in response was doing some manual benchmarking

@Safihre 
SAB 3.6.0
AVX2
Direct write ON, Article Cache ON on nzbget
https://forum.nzbget.net/viewtopic.php?t=1317#:~:text=Location%3A%20Germany-,%5BNew%20Feature%5D%20Article%20memory,allocate%20a%20larger%20cache.,-Implemented%20in%2014.0

TEST same file on both SAB and nzbget 63496MB (2MB Missing Articles so had to be repaired by both)

Test1 (SAB)
File 63496MB took `17 minutes` exact...well 16:58.59 on my stopwatch

Test2 (nzbget) 
File 63496MB took `11 minutes` 10:59.62

@sanderjo I wish I had a 10gbps pipe to my home 😊
Dockerized = True
It used to show the bottleneck not sure why its not showing right now

**Comment by sanderjo** [comment]
> Test1 (**SAB**) File 63496MB took `17 minutes` exact...well 16:58.59 on my stopwatch

So effective download speed: 62 MB/s, or 505 Mbps

> 
> Test2 (**nzbget**) File 63496MB took `11 minutes` 10:59.62

So effective download speed: 96 MB/s, or 779Mbps

**Comment by ItsME6969** [comment]
the download in nzbget for the whole 63gb took slightly under 3 minutes while downloading to RAM the repair and flushing to the disk is what took a long time lemme get better numbers on a file that needs no repair.

**Comment by Safihre** [comment]
I think it's not just unrar, but also emptying that NZBGet buffer from the ram. So total time is only about 60% slower, not bad for a Python application.

There's a few thing you could try that could be interesting:

- Disable Direct Unpack (in both applications), I feel our implementation of interacting with unrar might be a bit slower.
- In `/app/sabnzbd/sabnzbd/constants.py` modify [this line](https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/constants.py#L91), instead of `35` make it something like `3500` and restart SABnzbd.

**Comment by ItsME6969** [comment]
@Safihre unfortunately I'm at a loss... I have no access to SABs install location + I have no root access to the server (it's shared)
sab is installed in `/app/sabnzbd` a folder that I cant access. It used to be installed in the $HOME directory but the VPS provider changed that in their installation script and I mentioned that caused issues with me running post processing scripts here https://github.com/sabnzbd/sabnzbd/issues/2230#issuecomment-1172880142 .

**Comment by sanderjo** [comment]
> how accurate are those numbers? my synology home nas is showing some pretty low `folder numbers`

You must run it while SAB is not doing anything.

For CPU speed and disk speed: Accurate with a factor of 2. For your NAS speeds: slow & low. Spinning disks, I assume?

For Internet speed:  the measurement is less accurate. Reason: the measurement downloads a file a few times sequentially, and reports the max of the mean time of the overall download.
Better would be: parallel sessions, and meaure peak summed download speeds. Even better: use a command line tool like "axel" to download a 25GB, and measure max speed.

**Comment by Safihre** [comment]
@ItsME6969 You are able to SSH into the box? Then you could try things like `vim /app/sabnzbd/sabnzbd/constants.py` or `sudo /app/sabnzbd/sabnzbd/constants.py`?

**Comment by ItsME6969** [comment]
@Safihre tried that already cannot access it in any way...the file is outside my home directory so cannot access it and cannot sudo.... i have no root perms.
@sanderjo yea spinnig disks tested while sab had nothing going on. Not sure why those numbers dont look close to this.
...
![Screenshot 2022-08-16 054905 - Copy](https://user-images.githubusercontent.com/89707006/184884089-376f8aad-69f2-4f5d-a961-ceb34850bb41.jpg)

**Comment by Safihre** [comment]
It works well if the files you download fit inside the cache. If you download a 100GB also in nzbget the cache will fill and slow down.

Your suggestion is the way SABnzbd used to work, which resulted in very high starting speeds and then full collapse as soon as the caches fill up. And that happend a lot for users, especially when cpu is a limitation and decoding and/or assembly can't keep up.
During assembly we also calculate md5 in order to do Quickcheck and deobfuscation, so also assembly uses cpu.

I could build a switch to disable the partial writing.. This system has proven to get much quicker to the maximum speed that all component of the system can cope with it.

**Comment by thezoggy** [comment]
I've personally never seen that.much of the cache get used.. because it's only per file and that file articles aren't that big. It would be nice if it just did the job.. what people do is just setup a ran drive for the incomplete folder so it then doesn't matter about the article cache ram usage

**Comment by ItsME6969** [comment]
Yea I personally dont understand the inner workings just high level stuff but what I'm going off on is just presumptions based on the numbers I'm observing. Like here https://github.com/sabnzbd/sabnzbd/issues/2269#issuecomment-1216341230 NZBget had an effective download speed of 230MB/s while SAB had 100MB/s. That is pretty much Copy/Paste Raid0 type speeds with NZBget. That's really all I'm trying to achieve with SAB as well and the only difference I can see btn the 2 is that NZBget will use up all the RAM I give it while SAB will only use less than 100mb out of the 8gb I've allocated to it. So my assumption is that filling up the RAM is helping out because the RAM can keep up with the 10Gbps download speeds. I could be wrong of course. Again I have no problem with SAB on my low speed home connection, it works as required, I just feel like it doesn't work as well when the internet speeds are well over the hard disk speeds and ram drive is not an option for me zoggy on a vps.

**Comment by Safihre** [comment]
Nice! What settings did you end up using?

**Comment by sanderjo** [comment]
@ItsME6969 and all these speeds on your Celeron J3455?
