### ISSUE TITLE
Can't purge download queue

### ISSUE THREAD

**Issue by bjwest** [sabnzbd/sabnzbd#2272]
In trying to move from Sickchill to Medusa, Medusa decided to send over fifteen hundred downloads to Sabnzbd.  I have 84 pages of downloads to delete, with no way to do it other than page by page in the Multi-Operations by clicking the Check All box, the trashcan icon and the OK in the resulting popup.  Apparently, there was a purge all button sometime in the past, but that was removed for some unknown reason.  I did find [this post](https://old.reddit.com/r/SABnzbd/comments/s7c4jt/how_to_mass_flush_the_download_queue/) on Reddit stating the API is still there, and can be used with curl, but when I try that I get an error stating the API key is missing even though I included the correct key in the command.

This is absolutely ridiculous!  The purge all function needs to be brought back, and the problem with the API call looked into.  In the meantime, I guess I'll be sitting here wearing out my mouse button clicking 252 times to get rind of all this crap in my queue.

I'm sorry if this sounds harsh, I'm a bit ticked off at both Medusa and Sabnzbd right now.  I love Sabnzbd, and think you guys are doing a wonderful job.

**Comment by sanderjo** [comment]
> In the meantime, I guess I'll be sitting here wearing out my mouse button clicking 252 times to get rind of all this crap in my queue.

... or ... consider renaming queue10.sab to queue10.sab.BACKUP in .sabnzbd/admin. First stop SABnzbd.

**Comment by Safihre** [comment]
If you write a harsh message that shows little respect for the fact that you use free software that we maintain in our free time, you will get a harsh response:
The purge all function was not often requested, so it was not added as a button. If you had requested to put it back in a normal way, we could indeed easily have added it back.
Regarding the API: you probably just have some mistake in your curl call, since if the API-key verification was broken, the whole interface would not work and we would have endless complaints. You could have just posted your curl call, and we could have helped you with that.

@sanderjo's solution also requires you to manually delete the files in the Incomplete folder, so it's not an optimal solution.
An alternative is just to set the Queue item limit to 250, and you would have been done in just a few clicks.
