### ISSUE TITLE
Free Space Detection wrong when using Direct Unpack

### ISSUE THREAD

**Issue by Thundereye90** [sabnzbd/sabnzbd#2299]
It seems to me, that sabnzbd wants to have at least twice the size of what is already downloaded available, which cant be right in my opinion, if direct unpack is enabled.

For more details please visit this Forum post:
https://forums.sabnzbd.org/viewtopic.php?t=25957

**Comment by Safihre** [comment]
@puzzledsab If you have time, could you help me think of better solution for this? (see forum)
I never really thought about it very well when we implemented it.

**Comment by puzzledsab** [comment]
If we can assume that the direct unpacking is keeping up with the downloading and that the archive consists of many relatively small rar files then I think we can just use the base space limit without adding anything. The unpacking will pause soon after the downloading pauses.

It will break if it's just one large rar file or the unpacking isn't keeping up, though. I think it will get messy trying to compensate for every situation. Maybe assume that direct unpack is keeping up and add a warning that the free space calculation can be inaccurate if direct unpacking is used? Is there a way to pause direct unpacking separately so that it stops even if there are more available files?
