### ISSUE TITLE
Download speed regression in 3.7.1RC1

### ISSUE THREAD

**Issue by Cpuroast** [sabnzbd/sabnzbd#2357]
Hi,

I noticed a pretty download big speed regression in 3.7.1RC1. 
This is probably related to the recent download optimizations, but I'm not sure which commit caused it.

Using 3.7.1RC1 using the 1 or 10GB download tests, speeds up goes slowly and tops out at ~34MB/sec, it will sometimes go up to ~40MB but come back down to ~32-34MB/sec

Using 3.7.0 using the 1 or 10GB download tests, speed goes up very quickly and tops out at ~53MB/sec which is the limit of my connection and stays there.

I can easily replicate it by switching back and forth between the 2 versions, so it's not random.

This is on macOS Big Sur, downloading to a SATA SSD.
CPU: I7-3720QM which is a 3rd gen mobile hyper-threaded quad-core CPU.
Maximum line speed: 53MB
Percentage of line speed: 0
Article Cache Limit: -1

**Comment by Cpuroast** [comment]
I don't test individual git commits, only betas, RCs and stable. Probably could have caught it earlier had there been a beta instead of going straight to RC1.

**Comment by Cpuroast** [comment]
anyways, somewhere between 3.7.0 and 3.7.1RC1 the speed regression occurred.

**Comment by puzzledsab** [comment]
It's https://github.com/sabnzbd/sabnzbd/commit/557b9ef71d928857c42637774fe007ab7157e971 or the next one. I can't be sure because this one hangs.

**Comment by Safihre** [comment]
@puzzledsab why? He doesn't have problems with failing to connecting, just with speed.
I expect it's one of the recent optimizations.. But which one..

**Comment by sanderjo** [comment]
in SAB: Wrench symbol (upper right corner), what does the popup say at "Download speed limited by"

Mine:
Download speed limited by  CPU (95x) Disk speed (192x)

**Comment by puzzledsab** [comment]
I don't know why for sure but it's when I check out https://github.com/sabnzbd/sabnzbd/commit/8597784bc64b3cbc935cbcfbbae4df1baea1fbf9 that the download speed first goes down. https://github.com/sabnzbd/sabnzbd/commit/c7791a478ae61d38703971f606e098d9ae788424 downloads at full speed. I think it may be downloading in blocking mode.

**Comment by puzzledsab** [comment]
Replacing `self.sock.settimeout(None)` with `self.sock.setblocking(False)` in develop increases the speed to almost max speed but not completely so there may be other issues.

**Comment by puzzledsab** [comment]
The reason why I'm not getting full speed after the change is probably that the nzb I am using is old and not cached on the NNTP server. Is there any particular reason why you replaced `setblocking `with `settimeout`?

**Comment by Safihre** [comment]
Damn, my sleep deprived brain must have mixed up the documentation. Will correct.

**Comment by thezoggy** [comment]
loaded up nzb, waited ~30 seconds:

3.7.1rc1
![sab](http://zoggy.net/firefox_2022-12-04_14-32-21.png)

killed download, stopped sab. downgraded, loaded up nzb and tested again

3.7.0
![sab2](http://zoggy.net/firefox_2022-12-04_14-34-51.png)

so yeah 3.7.0 deff is faster

**Comment by Safihre** [comment]
@Cpuroast Could you try the "fixed" build?
https://github.com/sabnzbd/sabnzbd/actions/runs/3620289266

**Comment by thezoggy** [comment]
upgraded to 'fixed' build, faster than 3.7.1rc1 but slower than 3.7.0 for me
![sab](http://zoggy.net/firefox_2022-12-05_11-04-49.png)

**Comment by puzzledsab** [comment]
This is strange and unfortunate because there are a bit many commits and the blocking change came early so we can't easily check them one by one. Also, I don't see it myself after after blocking was fixed. I have made a list of commits that I think may impact performance in some way:

Possible
https://github.com/sabnzbd/sabnzbd/commit/59a3d58c0fd08b5dd9f7cba56fb24bcdfe1ed2c9
https://github.com/sabnzbd/sabnzbd/commit/d8fb19c26e8845c39450745c46cc5a701be3cd06
https://github.com/sabnzbd/sabnzbd/commit/b0530325c51378b25e612bc9038f02137efb38cb
https://github.com/sabnzbd/sabnzbd/commit/734a86a2485b6660ca7c18115e5485b66c5542b1
https://github.com/sabnzbd/sabnzbd/commit/63018439c8cf3b8c5d476a7a411cc96c5da00b25

Unlikely
https://github.com/sabnzbd/sabnzbd/commit/a12d447d953aad0e5a0d0c9c53a08027fd501cce
https://github.com/sabnzbd/sabnzbd/commit/e9578d9aa0aee9381539248d2e5a2e78dbc76d99
https://github.com/sabnzbd/sabnzbd/commit/ee2b2b2c3a0f8f215405e7f58f63e042a51b8896
https://github.com/sabnzbd/sabnzbd/commit/8597784bc64b3cbc935cbcfbbae4df1baea1fbf9
https://github.com/sabnzbd/sabnzbd/commit/557b9ef71d928857c42637774fe007ab7157e971

In addition there are all the dependency updates which I don't know anything about.

@thezoggy : What is your server set up? How many server entries do you have under servers, how many connections do each of them have, are they all using SSL and what priority do they have? Do you know if you are using 100% CPU on at least one core when downloading? It will say 25% in Windows task manager if you have 4 cores.

**Comment by thezoggy** [comment]
@puzzledsab i have several servers (astra usually enabled but ran out of block so disabled for the moment). i rarely hit blocks, i mainly just have collected them over the years during deals to try and get one on different backends and for testing. 

![firefox_2022-12-05_13-40-15](https://user-images.githubusercontent.com/500882/205727711-56ebb1ff-1111-4af2-8305-bb761555692e.png)

so for my main, its UNS with 40 connections and it connects at TLSv1.3 (TLS_AES_256_GCM_SHA384)

now for specs, my windows instance of sab is on win10 (fully patched) with Intel i7-4790K CPU (base 4.00GHz, turbo boost to 4.4GHz). 

Sab d/ling ~20%

![Taskmgr_2022-12-05_13-46-30](https://user-images.githubusercontent.com/500882/205729141-c193c757-fd83-4e58-ad36-50f6c1467cfc.png)

Sab incomplete/complete folder is on the OS ssd, which gets 300-400MB/s per the wrench test.

**Comment by Safihre** [comment]
I used my Intel NUC with slow N3700 processor (but fast SSD), and the new "fixed" version is a slight bit faster.
So considering this as resolved.
Unless @thezoggy sees some special speed variations with the different versions from @puzzledsab?

Something to also note is that when downloading and running `.exe` from the new builds, Windows automatically does a lot of background scanning and "telemetry". So this can influence the _first_ test results quite a lot.

**Comment by puzzledsab** [comment]
The first test with the blocking patch was still slow for @thezoggy and I missed the speed in the second image, which seems more normal. That's why I made those other branches. The first test without any of the optimizations was slow too, but then there was the big rollback which was fast, so I assumed there had to be a problem with one of the other commits since 3.7.0. In retrospect I think it's more likely that it was caused by random variations and Windows behaving badly.

**Comment by Safihre** [comment]
Windows behaving badly cannot be underestimated 🙃 
I had to run the tests over and over again to get stable results. Probably there is also caching on the side of the server that comes into play.

**Comment by Cpuroast** [comment]
I was always using the 1GB or 10GB test downloads which are always fast.

I tested and this was definitely the source of the initial slowdown and download was broken:
https://github.com/sabnzbd/sabnzbd/commit/557b9ef71d928857c42637774fe007ab7157e971 

Download was fixed in https://github.com/sabnzbd/sabnzbd/commit/8597784bc64b3cbc935cbcfbbae4df1baea1fbf9
But it was slow.

**Comment by Safihre** [comment]
Thanks! Will do!

**Comment by Safihre** [comment]
No news seems good news.
