### ISSUE TITLE
Focus not on first INPUT in "Add NZB" dialogue

### ISSUE THREAD

**Issue by pvanderp** [sabnzbd/sabnzbd#2382]
Typing "a" on the SABNZBD GUI brings up the "Add NZB" dialogue, but then still you need to use the mouse to set focus to the first INPUT. 

It would be nice if it would be possible to do - 'a' - Paste from clipboard - RETURN - sequence to add an NZB without using the mouse.

Reproduced with Safari on macOS and SABNZBD 3.7.1. I assume this is not browser specific.

Peter

**Comment by thezoggy** [comment]
what are you wanting to be first taxindex?
![firefox_2022-12-21_19-10-27](https://user-images.githubusercontent.com/500882/209033069-4e4806e6-cf39-4722-b6b4-f95dc3e9b3c9.png)

**Comment by thezoggy** [comment]
you could just hit `a`, then hit tab a few times to get to what you want..  
If your talking about 'browse...', that is not an input but a click target to load the file browser... which is why you cant tab to it. Which is also why we cant really just default to it, (simulate click) since it would open up the file browser.. which may not be desired. As some people just drag and drop, some want to load from url...

**Comment by pvanderp** [comment]
> what are you wanting to be first tabindex/focus?
> ![firefox_2022-12-21_19-10-27](https://user-images.githubusercontent.com/500882/209033069-4e4806e6-cf39-4722-b6b4-f95dc3e9b3c9.png)

Input element 1 (top left) seems logical to me.

regards,
Peter

**Comment by Safihre** [comment]
I was convinced I had already implemented this sometime before, I'm sure this was already request before we had the keyboard-shortcuts,
But yes, sounds like a fine idea.
