### ISSUE TITLE
Security Vulnerability pertaining to usenet provider password extraction on all versions

### ISSUE THREAD

**Issue by rlaphoenix** [sabnzbd/sabnzbd#2455]
Hi,

I have found a vulnerability in all versions of SABnzbd that I'm sure others are aware of and have not reported.
This vulnerability allows you to extract the usernames and passwords of providers.

The only pre-requisite to the attack is needing authorization to access the settings page of the Web UI instance.
This means that this attack can run freely on open instances running on the web.

I was wondering where I could securely report details and a PoC of this vulnerability as the Wiki contact page states to report on the Forum or GitHub and I found GitHub easier.

![image](https://user-images.githubusercontent.com/17136956/218328956-7126d5ee-7f1b-4bd7-b362-66f91ae35d6c.png)

**Comment by Safihre** [comment]
You can share it with me at safihre@sabnzbd.org

**Comment by thezoggy** [comment]
Yes it's well know you can siphon credentials by running a sniffer and testing a server to it. But as you noted you need to have access to sab gui. So it's no different than just saving sab config or using API to get details that way as well

**Comment by rlaphoenix** [comment]
While yes, it may already be known. I thought I would mention it just in case. However, your comments about saving the config or using the API to get the password is invalid. Only early 3.x versions allow you to download or retrieve the config. Later versions of 3.x have instead changed it to just tell you where to find the config on the server machine. As for the API, there's never been a way to get these details from the API, not that I know of.

This attack works on ALL 2.x and 3.x versions.

**Comment by rlaphoenix** [comment]
> You can share it with me at [safihre@sabnzbd.org](mailto:safihre@sabnzbd.org)

I've sent you an email now with a PoC in Python. I also have code that completely automates it into an aiohttp web API, of which I can provide it an IP or hostname and it will automatically run the PoC on it and save the credentials to an SQLite DB. This attack can be widenened to shodan scraping or even IP scraping.

**Comment by rlaphoenix** [comment]
A suitable fix would be to be unable to change the hostname after the server is configured. Instead, have users delete and remake a new server if the hostname really has changed (which doesn’t ever happen).

**Comment by Safihre** [comment]
Thank you for taking the time to investigate, but I don't find this to be a real vulnerability since it only applies to exposed instances.
We have tried extensively to warn users against exposing without protection, but there's only so much we can do.
I'm sure there's even more damage that can be done with an exposed instance than just sniff usernames and passwords.

**Comment by rlaphoenix** [comment]
I somewhat agree, but when a fix is possible with such a small change, I don't see a reason not to.

**Comment by thezoggy** [comment]
When I brought this issue up before my proposal was to just wipe the pw on change.
https://github.com/sabnzbd/sabnzbd/pull/2255

But the argument was that there's already other places one can siphon creds. Which is lead to the config backup change. In the end it wasn't worth the user inconvenience.

**Comment by rlaphoenix** [comment]
I find it ridiculous to intentionally keep in a vulnerability. Even if its exposed interfaces or not. The point still stands. What if a server got malware, or someone maliciously connected to your WiFi and used it, e.t.c e.t.c.

A simple change of being unable to change the host name once added, is a simple and logical solution.

**Comment by Safihre** [comment]
And what about the Config backup? It contains everything anyway. 
Or you would expect us to create special patch versions of all previous releases?

**Comment by rlaphoenix** [comment]
In newer versions of SABnzbd, you cannot extract the config backup from just the WEB interface or any related API. Only in early versions of `3.x` where the Server Backup feature was first added is such a backup possible. In later versions of 3.x, it was changed to make a browser popup noting the location of the backup zip on the server.

I'm also not expecting a new PATCH release for old versions. Just to have this fix in as soon as possible for the next release.

**Comment by thezoggy** [comment]
You can use API to get info (config). But anyways making server name read-only would be annoying when you need to rename to deal with mistakes when setting it up/update to reflect new host/change to another region or whatever the reason. 

And about your comment, it would be mad at like not having a lock on your fridge because you left your front door open. Making it harder for people while has a use but also causes other pains.

**Comment by rlaphoenix** [comment]
> We put many safe guards but of course no matter what we do someone can always get around it when they have access.

And you don't consider patching this to be another vital safeguard? I personally do not see how this comes down to a user inconvenience question. It simply is something that should be guarded, regardless if people have it exposed or not. This still makes users vulnerable to adding new devices to their home network, malware, e.t.c.

> Making server name read-only would be annoying

Security is annoying, so what. I personally want this fixed, even if it would be more annoying to rename a server, of which I would never ever ever need to do.

> annoying when you need to rename to deal with mistakes when setting it up

It really wouldn't. First-time setup people wouldn't make a mistake. After all, it does have a test server feature before adding the server.

> update to reflect new host/change to another region or whatever the reason

That would happen almost never though. If they change host the auth e.t.c would almost never be the same.

> Why I went with the approach to just wipe the pw.

This would be the annoying approach you are so fond of avoiding. Let's say I open my own SABnzbd settings, and edit the timeout. Now I need to re-enter the password. Or, I need to edit priority, or ... and so on. That's the annoying resolution.

The simple fact is a read-only host would be the logical solution to a problem that isn't just an issue to exposed endpoints but also protection from malicious new devices entering your home/server network (malicious intra-device attacks), malware, or annoying friends/family.

> Still an inconvenience but not as bad as having to delete the server and re-add which would cause you to lose server stats/settings.

It's literally the other way around as I've described now.

> There are various things we could try to do to lock things down / prevent access if x isnt set or mandate x is set. But then you take away features or flexibility for how people use sabnzbd.

I've already suggested arguably the best method. A read-only host. I don't see how this is in question. I understand trying to be for user convenience, but when that's over security for something as mundane and often unused as renaming a host, ridiculousness starts to come into picture.

> We've talked about several ideas in private but honestly you can only fix stupid so much before you treat everyone as stupid and then no one wins.

Again, this is not an issue only affecting people who **accidentally** have their ports open without authentication. This can happen to closed port instances, or even instances with a password depending on the situation.

**Comment by thezoggy** [comment]
Going to have to break this out since there are a few things you noted incorrectly that need to be clarified.

> > We put many safe guards but of course no matter what we do someone can always get around it when they have access.
> 
> And you don't consider patching this to be another vital safeguard? I personally do not see how this comes down to a user inconvenience question. It simply is something that should be guarded, regardless if people have it exposed or not. This still makes users vulnerable to adding new devices to their home network, malware, e.t.c.

We understand your opinion, you are fine to have it. We've already talked about this before and I tried to share my approach when we last had it. I personally find your approach more disruptive to usability.

> > Making server name read-only would be annoying
> 
> Security is annoying, so what. I personally want this fixed, even if it would be more annoying to rename a server, of which I would never ever ever need to do.

Security doesn't have to be annoying or combative to the user. This is why we give options to users to dictate how they want sab to be used. Some dont expose sab, some restrict their api. We offer up things like a nzb key which is a limited in scope api key that cant do much besides add nzbs.

> 
> > annoying when you need to rename to deal with mistakes when setting it up
> 
> It really wouldn't. First-time setup people wouldn't make a mistake. After all, it does have a test server feature before adding the server.

Users make mistakes, it happens we are human. If a user had to delete a server to re-add it to fix a typo, I would understand them being unhappy about that. Which is why I can do not think that your method is the right one. It adds more negatives than gains.


> 
> > update to reflect new host/change to another region or whatever the reason
> 
> That would happen almost never though. If they change host the auth e.t.c would almost never be the same.

The host name while is somewhat static, but can change.
People make typos, usenet servers get bought up/resellers change names, want to deal with outages, etc etc.

Is it end of the world to delete a server and add it back? no. 
Should a user have to jump through this hoop because some ding bat left their sab instance open somewhere and we wanted to prevent someone doing a drive by change of their server to cause them this inconvenience.. no.


> > Why I went with the approach to just wipe the pw.
> 
> This would be the annoying approach you are so fond of avoiding. Let's say I open my own SABnzbd settings, and edit the timeout. Now I need to re-enter the password. Or, I need to edit priority, or ... and so on. That's the annoying resolution.
> 
> The simple fact is a read-only host would be the logical solution to a problem that isn't just an issue to exposed endpoints but also protection from malicious new devices entering your home/server network (malicious intra-device attacks), malware, or annoying friends/family.

If you read the pull request of the note, its only wiping the pw if you change the host. Not if you change a setting.
Which is the target that people generally want, the pw. So making it harder to get is the goal. 

But the argument to do this was lost because if a user has access to their instance there is other things that can be done anyways to get the pw so its all a bit moot.


> > Still an inconvenience but not as bad as having to delete the server and re-add which would cause you to lose server stats/settings.
> 
> It's literally the other way around as I've described now.

Making your requested change causes more problems than the one edge case you are trying to fix.

> > There are various things we could try to do to lock things down / prevent access if x isnt set or mandate x is set. But then you take away features or flexibility for how people use sabnzbd.
> 
> I've already suggested arguably the best method. A read-only host. I don't see how this is in question. I understand trying to be for user convenience, but when that's over security for something as mundane and often unused as renaming a host, ridiculousness starts to come into picture.

You are welcomed to your opinion. sab is open source, feel free to fork and make the change for yourself. But I really hope you are not on this band wagon because you are one of those people that left their sab instance open and got your stuff stolen and now are just trying to blame sab because we let you do it.

> > We've talked about several ideas in private but honestly you can only fix stupid so much before you treat everyone as stupid and then no one wins.
> 
> Again, this is not an issue only affecting people who **accidentally** have their ports open without authentication. This can happen to closed port instances, or even instances with a password depending on the situation.

Note quite sure I believe that.
Again, you would have to have access to sab's instance (so bypass auth if they have it) or sab apikey (with them allowing config access) for you to get the information your talking about.

**Comment by jeffgeorge** [comment]
As Zoggy has said, if you already have full WebUI access then specific exploits that flow from having admin access aren't worth fixing on their own. At that point the whole instance should be assumed to be running in a fully insecure / compromised mode. If we patched away _everything_ potentially malicious you can do if you're running SABnzbd in a known-insecure configuration, there wouldn't be much left.

I'd be more open to evaluating our options to fully refactor our authentication setup to make password mandatory for the admin (regardless of port config), and only leave it optional for the normal WebUI. It'd be a nontrivial effort to get this done, but it'd solve this whole _class_ of issues comprehensively.

**Comment by Safihre** [comment]
I think our opion is clear and we can close this issue.

We can create a Discussion for what @jeffgeorge suggested. 
We actually had this in older versions, where in the wizard you could choose to set the host to `0.0.0.0` and then directly allow you to setup a username and password. But we scrapped that, I think to simplify the wizard. Remember @sanderjo?
See this wizard page: https://github.com/sabnzbd/sabnzbd/blob/0.7.x/interfaces/wizard/two.html

**Comment by sanderjo** [comment]
> We actually had this in older versions, where in the wizard you could choose to set the host to `0.0.0.0` and then directly allow you to setup a username and password. But we scrapped that, I think to simplify the wizard. Remember @sanderjo?

Yes, exactly. The old wizard was full of options (and so: needless difficult). Setting the username/password was confusing (users filled out the username/password of their news provider) and locked users out.

I'm so glad with the current easy wizard: you now have SAB up and running in a few clicks. Later on you can change stuff.
