### ISSUE TITLE
[Feature Request] Make history database an archive

### ISSUE THREAD

**Issue by Taomyn** [sabnzbd/sabnzbd#2503]
Not sure if the title makes sense but an issue I have been having for many years is that I prefer to see the history database a bit more permanent, so that even if I remove an entry from the display it actually remains in the database as an archived record. A good benefit of this would be the duplicate download detection as I have lost count of the number times I have accidentally cleared the history and then an automated download comes along that is a duplicate but does not get detected - I've even had this happen nearly a year after the original release but for some reason my indexer service decided to submit a new release which I did not need.

So perhaps the history records should have an archive flag that hides it by default in the history view when you do a standard delete but the view could also have an option to view archived records to allow for a permanent deletions if you so wish. Perhaps even a "retention period" setting that can regularly removed archived records older than a certain period.

**Comment by thezoggy** [comment]
You can use nzb backup folder for long term dupe detection  as we I'll use that as well as the history. I Can't find the previous conversation about this request, but basically asking for us to add a flag to the db like nzbget so you can keep it in history but hide it from api. It's something I have wanted to add  because of how *arr apps rely on having history to process / only looks back at x many items to process.

**Comment by Safihre** [comment]
While it's not a bad idea at all, it's just not in scope at the moment!
