### ISSUE TITLE
RCE from WebUI

### ISSUE THREAD

**Issue by mullerdavid** [sabnzbd/sabnzbd#2549]
An authenticated user can run arbitrary code with basic binaries found on Linux host.

In Settings->Folders,  the Scripts Folder option can be set.
Then under Settings->Notifications, the Notification block allows setting an executable with parameters that can be ran with the Test Notification button (running the script as [user script] SABnzbd Other Messages [user parameters]).

Correctly choosing the Folder, Script and Parameter can result in arbitrary code execution.
I managed to do it with some basic commands that can be found even in a lot of stripped down linuxes.

Possibly Windows is affected as well, I did not test that platform.

As this might work as intended, a basic check for the file owner matching the running user might be able to mitigate the issue. Current users that use some other files can create a wrapper and use that instead, as that would still match the user requirement.

**Comment by thezoggy** [comment]
The key here is that you need access.

**Comment by Safihre** [comment]
We only allow to execute if the execute bit is set, but indeed this would already be the case for system executables.
The crux is here indeed that we allow parameters for the Notification Script.

Thoughts @jcfp @sanderjo?

**Comment by mullerdavid** [comment]
Yeah, also the py files are checked for the bit before prepending the python command. The permission of the downloads are also stripped off from the execution bit nicely when setting up permissions. Those parts look solid.

**Comment by sanderjo** [comment]
I agree with @thezoggy  "The key here is that you need access.". So:

- access on / from your PC: OK. If not: set a password.
- access on / from your LAN: hopefully you trust your LAN mates. If not: set a password.
- access on / from Internet: if you set that open, without password: anything can happen, and not clever

Having said that:
Config -> Folders: Scripts Folder set to /usr/bin, and indeed then via Config -> Notify I can see all the stuff in /usr/bin.

So _if_ we want to avoid this, how? 

- Only allow sub-dir within SAB-dir (but what if users have the scripts on another location?)? 
- Only allow scripts? 
- Only a dir that has mainly scripts, and no system executables? 
- Nothing within /bin and /usr/bin ... ? Only within a directory that has "sab" or "sabnzbd" in its name (does that work for *arr users?)?

**Comment by jeffgeorge** [comment]
> So _if_ we want to avoid this, how?

I'd look at evaluating the option of matching owning userid. SABnzbd should only be able to execute stuff owned by the user sabnzbd is running as. Then this would only be an issue if SABnzbd is running as root, and . . please do not do that.

**Comment by sanderjo** [comment]
> I'd look at evaluating the option of matching owning userid. SABnzbd should only be able to execute stuff owned by the user sabnzbd is running as. Then this would only be an issue if SABnzbd is running as root, and . . please do not do that.

Clever. 

Maybe a problem for docker users: AFAIK docker has only one account: root. But then: within docker, it's sandboxed, so   no/little harm can be done to the host OS. Within the docker: so be it. Docker can still access the exposed drive of the host, but that is only downloaded content (if exposed correctly)

**Comment by mnightingale** [comment]
I think you need to try and protect users from doing silly things, maybe lockdown the config so if no username/password is set but "External internet access" is allowed don't let the script path be changed?

I'd certainly consider removing the notification parameters since that's just too easy to attack (bash+curl=done) and it doesn't really take anything away from users - they can just make those parameters part of the script which gets called.

**Comment by sanderjo** [comment]
> I think you need to try and protect users from doing silly things, maybe lockdown the config so if no username/password is set but "External internet access" is allowed don't let the script path be changed?

Also clever!
And also works with VPS / with only remote access: first set password, only then allow scripts to be configured

**Comment by thezoggy** [comment]
@mnightingale the only catch with this one is those that rely on external auth (reverse proxy with sso like authelia/authentik) where they can have sab auth disabled and sab exposed because it's actually handled by the reverse proxy. 

For sonarr/radarr how they handle that scenario is allowing users to set auth as external (instead of none or the internal basic/forms) so they know it.

**Comment by Safihre** [comment]
We designed it to allow parameters so we can offer some sort of flexibility. For example nzb-notify script allows users to specify the specific service(s) to notify. Or for example you could pass api keys or other configuration to a notification script.
 We could remove the parameter, but then users would have to hardcode any parameters in a wrapper script. 

I'm open for any ideas how to improve this. If forcing scripts to have current user, it sounds reasonable. We could release that as part of a alpha/beta release and see response from the user base.

**Comment by Safihre** [comment]
I will change the code to supply the parameter as a environment variable (`SAB_NOTIFICATION_PARAMETERS`).
@caronc would you be able to modify nzb-notify to handle that? 

Is this something that needs to be patched in a 4.0.x or can it wait for 4.1.0?
And do we need to publish a Security Advisory (which will result in a CVE)? Probably, since we did to that for this one: https://github.com/sabnzbd/sabnzbd/security/advisories/GHSA-9x87-96gg-33w2

**Comment by caronc** [comment]
> I will change the code to supply the parameter as a environment variable

Sure, I'd be curious what approach you plan on taking as i still very much think Apprise could be integrated into SABnzbd with a lot less effort then you think and still send alarms selectively on download, queued, etc (selectively). I'll try and mock something up in Visio today if i have time to illustrate this. But regardless, there is a script you're referring to is dedicated to just handling SABnzbd calls. So we can definitely tailor it to your likings. 👍🙂

> Is this something that needs to be patched in a 4.0.x or can it wait for 4.1.0?

I'm just curious on the scope of the work. If you need me to do it, just provide me with some details of what will be in this new environment variable (`SAB_NOTIFICATION_PARAMETERS`). Otherwise feel free to do a pull request too. Either way. Is it the same arguments being passed to the CLI, but comma or tab delimited? Or something new (JSON)?

Your call on CVE. My experience is to identify exploits and fix them asap first; usually all done one on one with those who discovered them; not a public forum like this where those reading will now leverage the 0 day. Release the CVE once you've solved it thereafter so people are encouraged to upgrade (not panic) 😉. I'll gladly assist in any way

**Comment by mullerdavid** [comment]
> Your call on CVE. My experience is to identify exploits and fix them asap first; usually all done one on one with those who discovered them; not a public forum like this where those reading will now leverage the 0 day. Release the CVE once you've solved it thereafter so people are encouraged to upgrade (not panic) 😉. I'll gladly assist in any way

I'd normally contact privately, but this looked like a smaller issue with really small attack surface, that might be even a feature. Tried to be as vague as possible as well. So far, i think everything was handled properly and in a timely manner. Thanks for fixing it.

**Comment by caronc** [comment]
You did great @mullerdavid ; honestly. It's a good find and you reported it. The outcome of the investigation you all did just revealed it to be more serious i guess. So it is what it is.

**Comment by mullerdavid** [comment]
I checked the diff and tested the current version. You are adding the parameters to the SAB_NOTIFICATION_PARAMETERS. The fixed environment variable looks good, as it limits the command injection through the env variables (eg, java JDK_JAVA_OPTIONS), and I can't imagine anyone else using remotely similar variable..
