### ISSUE TITLE
upgrade removes Pre-queue user script

### ISSUE THREAD

**Issue by bubbyboyy** [sabnzbd/sabnzbd#2557]
when upgrading, the Pre-queue user script is deleted. creating and restoring a backup does not fix the issue.

**Comment by Safihre** [comment]
And where is your pre queue script located? 
Or better, where is your Scripts Directory relative to where your SABnzbd installation is?

**Comment by bubbyboyy** [comment]
hi. it's in C:\Program Files\SABnzbd\scripts\ which i'm guessing is the default? so same as the installation directory

**Comment by thezoggy** [comment]
the pre-queue script would only be removed if the script is no longer accessible/valid at that point. also debug logs would show why (it tried / permission denied/etc). normally you only see this sort of fallout if the user changes the install location  / remove the old stuff which the user put the script in the app folder rather than a user folder so it got removed with it.
