### ISSUE TITLE
Every download needs repairing with the latest version when using mergerfs

### ISSUE THREAD

**Issue by Crowley007** [sabnzbd/sabnzbd#2558]
Like the topic says, every download needs to be repaired with the latest version. I had this problem with the beta also, which is why I used the last stable version until now. 

I also know what causes this behavior, but not why. My setup uses mergerfs pools for both completed and temp folders. My temp is setup as follows: First 5G go to a ram disk, the next 20G go to ssd and everything after that to mechanical disks. This is to speed up downloading while saving the ssd. Small downloads do not touch the SSD at all.

If I move the temp folder to a pool that contains only the mechanical disks, everything works fine, no extra repair needed. So my conclusion is that the problem has something to do with the function that switches the disk in the pool when the size quota is filled. 

But this setup does work absolutely fine with the last stable sabnzbd and with nzbget so the latest version is doing something differently. 

Setup: Ubuntu, sabnzbd 4.01

Attached is the log from a session where I add the nzb and when it completes and starts to repair, I delete it. Then I switch the temp folder location and download the same nzb again and it completes fine.  I didn’t have debug enabled, but I can repeat either or both cases with debug logging if it helps.

[sabnzbd.log](https://github.com/sabnzbd/sabnzbd/files/11442726/sabnzbd.log)

**Comment by mnightingale** [comment]
Direct unpack does seem to fail at *.part12.rar which I think will be around the 5GB mark.
Have you tried ramdisk + mechanical to rule out an issue with the SSD?

I can't think of a 4.0 change that could cause this, maybe someone else can.
But looking at the logs every file written after 5GB failed crc32 check and needed repair.
Maybe io.write fails because it's out of space, but `moveonenospc` should be taking care of that.

What mergerfs mount options do you have?

**Comment by Crowley007** [comment]
First, I tried without the SSD, no change.

About that mergerfs config, what part do you think would help? I'm not an expert so bare with me. It has no moveonenospc, so how would it know to change disks? Also I need category.create=lfs so the disks are filled in the right order ram->ssd->hdd..

**Comment by thezoggy** [comment]
with your article `cache_limit = 1G` you are offloading to ram to then ram again..  you are creating a ram drive to ram drive with that alone.. so something prob just is not playing nice to do that with your options/setup. I dont know mergerfs enough to know what specific option but also your setup is highly unusually to most that do things. 

most people just download to an incomplete folder thats on ram drive / cache pool / its own drive. then the completed folder is more semi perm storage or perm storage. depending if you have yet another app that comes in and moves the files around/transcode it/etc.

you should try and isolate it to see if its just the ram drive causing issues, make sure ram is good and not causing any corruption or have some merger option that just isnt playing nice.

so just the ssd -> hdd and make sure that is all good. so you can try and isolate what to focus on.
if you think its a sab change, change to specific version  / step through commit and see what change isnt working for you and we can try and point you in the right direction

**Comment by Crowley007** [comment]
Well, Like I said this works fine with nzbget and did work with the older sab as well. 

I tried without article cache, but that totally kills my speed even when downloading to a ram drive. This setup is needed, because I have  only 8GB of ram on this server and the ramdrive wont fit most downloads.  Since the error happens right when the ram drive is filled, I  doubt that's the problem.  

Like [mnightingale](https://github.com/mnightingale) said, everything downloaded after is the problem so it happens when the change of disk occurs. To be clear, it downloads everything fine after this as well but direct unpack fails on that point and it wont verify correctly after download.

**Comment by Crowley007** [comment]
This gets even stranger. I downloaded version 3.7.2 on the side so that I could test. And now it fails the same way as well! Direct unpack fails, but it downloads every part correctly. Then it tries to unpack, and fails when it need the first part that's on the next drive.  So the drive change is definitely the issue.

But since it doesn't work with the older version anymore either, I wonder if the problem lies in one of the requirements I updated with pip...

**Comment by sanderjo** [comment]
"**Every** download needs repairing with the latest version"

and

> But 4.0.1 will not work, I tested multiple times with **same** nzb file.

So ... what if you use the reference download:

In SABnzbd's upper right corner, click on the wrench symbol ("Status and interface options"), then click on first tab Status, click Test download 10GB.

**Comment by Crowley007** [comment]
I have to test when I get a chance. I did test with multiple over 5GB downloads with same results. With same I meant that it worked with the old build but not new. Downloads under 5GB were fine.

**Comment by Crowley007** [comment]
Just ran the test using the reference download, and the results are the same. 1GB finished nicely, 10GB causes direct unpack to stop after the ram disk is full. All the files download after that, but can't be unpacked, just like with "real" downloads. And like before, the 10GB file downloads fine with 3.7.2.

But this is a really good and fast way to test the problem. Since everything does download, "moveonenospc" has to be working. But with 4.01 it causes some corruption that does not happen with 3.7.2.

**Comment by mnightingale** [comment]
I just tried a VM with 512MB ramdisk+nvme with an old version of mergerfs (2.33.3) and recreated the problem, it was as expected `fout.write(data)` writing less then expected which I don't think should happen due to `moveonenospc`.

I tried the latest release by installing the .deb from GitHub releases (2.35.1), it claims to write the expected amounts but still sometimes had errors `Target: "sometestfile-1GB.part07.rar" - damaged. Found 197 of 199 data blocks.`

The filesystem should be transparent to SAB so I'm fairly sure it's a mergerfs problem.
Personally I just have a sacrificial SSD that's already written 50% more than its TBW and more modern ones have way higher TBW anyway.

Regarding your edit2 above, your min space 1GB will mean it's less likely a file has to be moved from RAM to disk, which seems to be where the problems starts.

**Comment by Crowley007** [comment]
I find that minfreespace with mergerfs isn't always followed for some reason, but that's a separate issue. Right now I have 5200MB ram disk and minfreespace at 200. With this setup, 3.7.2 & nzbget consistently work and 4.01 consistently fails after 5GB mark.

I get that ssd could be used without issue, but this setup should be usable as well, I have used it for years with nzbget before making the swap to sab a few weeks ago.  Because of this, I have my doubts of it being a mergerfs issue. I still suspect some  weird edge case with sab and & moveonenospc.  When I have the time I will try the setup without the ram disk, I suspect that the error happens with any disk when it needs to switch  due to low space.

**Comment by thezoggy** [comment]
What if you turn off direct unpack?

**Comment by Crowley007** [comment]
A lot of testing done. To rule out the ram disk, I made a 5GB SSD partition. Like I suspected, no difference. It fails when it changes disks.

I also tested with direct unpack off, but it makes no difference when the unpack happens, the files on the next disk are corrupted, so it fails at the same point. 

The only thing that works without fail, is going back to 3.7.2.

**Comment by sanderjo** [comment]
> Edit: I tried unrar manually, and it fails on the first file that is on another disk, 

So it's not a SABnzbd problem ...

> so I guess it doesn't really download correctly either

Ohh? How do you get to that conclusion? You can run md5sum on the rar files, and check them against downloading the same download to a normal drive. You could use the SAB 10GB reference rars for that. 

To analyze this, I would do this:

On a normal drive, create a 10GB file.
Run rar to create rar files. EDIT: you can use the SAB 10GB reference download for this, with download-only.
And then: unrar to your mergerfs drive ... and see what happens. Problem with the boundary ... then a disk problem. Not SAB.

**Comment by Crowley007** [comment]
I'm not trying to be unpolite, but again, Sabnzbd 3.7.2 works with everything, the reference download and everything else. I also use mergerfs pools for many things on my server, unrarring to and from the pools does work fine.  Only thing it does not work with, are the rars that sab 4.0.1 produces after the disk change. Rars from 3.7.2 extract fine from multiple disks, as tdoes nzbget etc.

**Comment by Crowley007** [comment]
I get it, so just to rule things out, I did the test as follows:

I download the reference 10GB rars to a pool that has only the mechanical drives, so no need to split the files on multiple disks. They downloaded and extracted fine. 

Next I copied the rars to the pool that I'm using for temp, that contains Ram disk & SSD .  As expected, the files copied fine, 5GB on the Ram disk and 5GB on the SSD. They also Extract fine. To be clear, only my temp folder that houses the rars is like this, completed downloads are on the mechanical pool. 

So the conclusion remains the same, Sab 4.0.1 does not handle the disk change well, after the ram disk is full the rest will download on to the ssd, but these will not work.

And the topic now better reflects the real problem, thanks.

**Comment by mnightingale** [comment]
There is nothing Sab does specifically to handle the disk change, it just opens a file handle and writes to it.

---

Here is an example of the 1GB test file in download only mode - no repair because I wanted to see how broken the files were.

```
$ ls -al /mnt/pool/complete/test_download_1000MB.1/
total 1532264
drwxrwxr-x 2 mike mike      4096 May 11 21:57 .
drwxrwxr-x 4 mike mike      4096 May 11 21:57 ..
-rw-rw-r-- 1 mike mike     42696 May 11 21:56 sometestfile-1GB.par2
-rw-rw-r-- 1 mike mike 107374182 May 11 21:56 sometestfile-1GB.part01.rar
-rw-rw-r-- 1 mike mike 191407718 May 11 21:56 sometestfile-1GB.part02.rar
-rw-rw-r-- 1 mike mike 144799334 May 11 21:56 sometestfile-1GB.part03.rar
-rw-rw-r-- 1 mike mike 144115302 May 11 21:56 sometestfile-1GB.part04.rar
-rw-rw-r-- 1 mike mike 202909286 May 11 21:56 sometestfile-1GB.part05.rar
-rw-rw-r-- 1 mike mike 107374182 May 11 21:57 sometestfile-1GB.part06.rar
-rw-rw-r-- 1 mike mike 203642470 May 11 21:57 sometestfile-1GB.part07.rar
-rw-rw-r-- 1 mike mike 148481638 May 11 21:57 sometestfile-1GB.part08.rar
-rw-rw-r-- 1 mike mike 205858406 May 11 21:57 sometestfile-1GB.part09.rar
-rw-rw-r-- 1 mike mike 107374182 May 11 21:57 sometestfile-1GB.part10.rar
-rw-rw-r-- 1 mike mike      1780 May 11 21:56 sometestfile-1GB.part11.rar
```

Note the files except for part01 are the wrong size.
part02 and others have NUL data followed by the actual file.

![image](https://github.com/sabnzbd/sabnzbd/assets/9887246/950e8458-24a0-4f15-b138-5cb7a9d5ce16)

---

Here's a simple POC script that resembled how SAB writes the downloaded parts to disk and seems to show it going wrong in the same way https://gist.github.com/mnightingale/6ee1fe797df09d340b62738868e66443
The script wants to write 1MB of "0", 1MB of "1", and repeats 0-9, range(201) means 201MB total (bigger than size I set the tmpfs mount).

```
/etc/fstab

tmpfs /mnt/ram tmpfs nodev,nosuid,noexec,nodiratime,size=200M 0 0
/mnt/ram:/home/mike/Downloads /mnt/pool fuse.mergerfs  defaults,noatime,allow_other,use_ino,cache.files=auto-full,dropcacheonclose=true,category.create=lfs,category.search=newest,moveonenospc=true,minfreespace=50M   0       0
```

I end up with a 400MB file, 200MB of NUL (0x00) followed by the file.

I'm not sure what could have changed since 3.7.2, I don't believe the file write process has changed but it's frequency probably has.

I've no idea why this seems to happen, hopefully you can replicate it with the above script and ask mergerfs for help, it looks like they'll want strace outputs of the script and mergerfs.

**Comment by Crowley007** [comment]
Some of your explantion is going a bit over my head, but my testing show that tmpfs is not really the issue, same happens with multiple small ssd partitions in the pool. And the pool by itself works just fine since manually copying the rar files there extract just fine as well. Indeed there is something in the way sab writes the rar files that clashes with moveonenospc, files on first pool drive work, files on the second do not.

I'm not an expert with mergerfs either, certainly not enough to open an issue there when everything else but sab 4.0.1 work fine. I can just see the dev saying it's a SAB issue and I'm right back here again and I don't have the technical expertise to prove any different. If you decide this is a mergerfs issue, I'll just have to use the older build/nzbget, no harm done.

**Comment by mnightingale** [comment]
Sab is opening the file in append mode and for some reason once the move happens the file balloons in size and is not what it was told to write.

I'd expect manually copying rar files is different, the filesize will be known at creation time of the copy so mergerfs can immediately write to to where it will fit and not have to move it after writing until out of space.

Here are strace's of slightly modified [POC script](https://gist.github.com/mnightingale/6ee1fe797df09d340b62738868e66443) 
python: https://gist.github.com/mnightingale/f3af90e839d47cba6d4c54bbda3d3cb7
mergerfs: https://gist.github.com/mnightingale/58a0fd3a3f2632d23556384eb06fc269

If you follow all the `write` calls Python has made the expected 201 of them 1048576 bytes each.
But the bytes written doesn't match the size of the resulting file.

I'm certainly no expert at the low level filesystem calls in the mergerfs-process trace, but to me it looks like:
- it writes a load of data as expected until length is 209707008
- opens /home/mike/Downloads/tmp.dat.UPPOSE
- ftruncate to set length
- copy_file_range fails - why I've no idea
- falls back to a read/write copy from the old to new file

I expect the [copydata_readwrite](https://github.com/trapexit/mergerfs/blob/latest-release/src/fs_copydata_readwrite.cpp) fails because the file was opened in append mode (O_APPEND) so the data starts writing at the end of the file.

I conclude it's a mergerfs problem, but it won't happen in nzbget because it doesn't open in append mode and #2526 will probably resolve it in Sab.

If you don't want to report it to mergerfs I can try but I'm not really invested in getting it fixed and I've spent way too long investigating it.

**Comment by Crowley007** [comment]
I appreciate that you looked into it, I didn't mean that you should report it, perhaps we should just leave it be for now especially if the direct write feature could help with this. 

When I have the time I will go through the mergerfs policies and see if anything could help there.

**Comment by mnightingale** [comment]
I've reported it so we'll see what they make of it, hopefully my observations are correct 😄

**Comment by Crowley007** [comment]
Ok, thanks for that, we shall see I guess! If something gets updated, I can of course help with the testing at least.

**Comment by Safihre** [comment]
Closing this as upstream problem.
Thanks @mnightingale for your deep dive!
