### ISSUE TITLE
Could not link to OpenSSL library

### ISSUE THREAD

**Issue by sderrow** [sabnzbd/sabnzbd#2568]
Splitting out from #2421 to avoid user confusion.

Version: 4.0.1 [916c191]
Python version: 3.9.16 (main, May 16 2023, 15:53:32) [GCC 6.3.0 20170516] [UTF-8]
OpenSSL: OpenSSL 1.1.0l 10 Sep 2019
Multicore Par2: ☑️

uname: Linux antaeus 4.19.123-feral # 2 SMP Mon May 18 09:01:14 BST 2020 x86_64 GNU/Linux

On `python -c "import ssl; print(ssl._ssl.__file__)"`, I get `~/python/lib/python3.9/lib-dynload/_ssl.cpython-39-x86_64-linux-gnu.so`. Confirmed that the file does exist at that path.

On `python -c "import ssl; print(ssl.__file__)"`, I get `~/python/lib/python3.9/ssl.py`

Built Python from source. Specifically these exact commands:
```bash
version=3.9.16
# Download
wget "https://www.python.org/ftp/python/$version/Python-$version.tgz"
tar -zxvf "Python-$version.tgz"
rm "Python-$version.tgz"
cd "Python-$version"
# Install
 ./configure --prefix=$HOME/python --enable-optimizations --with-lto
make
make altinstall
cd ..
rm -r "Python-$version"
majMin="${version%.*}"
ln -s "$HOME/python/bin/python${majMin}" ~/python/bin/python
ln -s "$HOME/python/bin/pip${majMin}" ~/python/bin/pip
```

@mnightingale `lsb_release -d` reports `Debian GNU/Linux 9.13 (stretch)`. Feral does implement global installation restrictions:
> Users do not have root access and will not be able to run apt-get, su or sudo. Whilst many software guides (outside of Feral) may instruct you to use sudo, this is generally only to allow you to install to a protected directory such as /usr/bin/. On your slot, you can simply install things relative to $HOME which does not require any special permissions.

**Comment by mnightingale** [comment]
I think the issue is dlopen won't do tilde expansion.

It looks like we should be able to use the `wordexp` function to expand it to an absolute path.

I'll try and implement a fix sometime this week.

**Comment by sderrow** [comment]
@mnightingale sorry, I may have led you astray! My bad. When I said I got `~/python/lib/python3.9/.....` as outputs from the two python commands you had me try, that was me abbreviating the output. Sorry, should have clarified! It actually responded with the absolute path: `/media/...[path to my home folder].../python/lib/python3.9/...`. Was trying to protect my privacy a bit by not exposing my home folder name/location since it's hosted on feral.

**Comment by mnightingale** [comment]
Ah no worries I did think it was strange that Python would return such a path.

I think what I'll do when I get a chance add some extra logging to try and determine where it failed.

https://www.openssl.org/docs/man1.1.1/man3/SSL_read_ex.html
> The SSL_read_ex() and SSL_peek_ex() functions were added in OpenSSL 1.1.1.

Since it finds the correct path, I'm fairly sure its because of an old OpenSSL version.
I'd suggest following https://help.dreamhost.com/hc/en-us/articles/360001435926-Installing-OpenSSL-locally-under-your-username to install a local version.

Then install Python from source and tell it to use your openssl with:
```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/path/to/openssl/lib
./configure --prefix=$HOME/python --enable-optimizations --with-lto --with-openssl=/path/to/openssl
```
I'm not 100% sure that's the correct commands but hopefully points you in the right direction.

**Comment by thezoggy** [comment]
and out of curiosity, why did you install python 3.9 manually? why not with ppa or pyenv? and why not 3.11?

**Comment by sderrow** [comment]
Yeah, I was just following feral's docs because most other guides for installing software have you use sudo and that's not available to me.

Tried to do 3.11 but then pip didn't work at all because it couldn't find OpenSSL (probably the same reason!)

Will try some of your suggestions and report back. Thanks for the help!

**Comment by sderrow** [comment]
Tried a bunch of different variations of installing openssl and then pointing the python build to it, but couldn't get it to work sadly. Probably have to wait for feral to upgrade ssl to 1.1.1 or later.

What's the better option? Downgrading to sabnzbd 3.7 or continuing with 4.0 and just ignoring the openssl link warning?

**Comment by mnightingale** [comment]
Try these steps:

OpenSSL
```
wget https://www.openssl.org/source/openssl-1.1.1t.tar.gz
tar zxvf openssl-1.1.1t.tar.gz
cd openssl-1.1.1t
./config --prefix=$HOME/openssl --openssldir=$HOME/openssl no-ssl2
make
make test
make install
cd ~
```

Python - mostly the same as https://www.feralhosting.com/wiki/software/python
If you remove `--with-lto` it'll be a lot quicker to build, I'd try it first without instead of waiting ages for a build only for it to fail.

```
version=3.11.3
# Download
wget "https://www.python.org/ftp/python/$version/Python-$version.tgz"
tar -zxvf "Python-$version.tgz"
rm "Python-$version.tgz"
cd "Python-$version"
# Install
./configure --enable-optimizations --with-lto --prefix=$HOME/python --with-openssl=$HOME/openssl --with-openssl-rpath=auto
make
make altinstall
cd ..
rm -r "Python-$version"
majMin="${version%.*}"
ln -s "$HOME/python/bin/python${majMin}" ~/python/bin/python
ln -s "$HOME/python/bin/pip${majMin}" ~/python/bin/pip
```

This failed for me on a Vagrant VM using `generic/debian9` image because I was missing ffi among others, but since these are Ferals instructions I guess they are more likely to work.

There isn't an issue sticking with 4.0 or later, if it couldn't link OpenSSL it just carries on using the less optimal methods the same as previous releases you'll just be stuck with a warning message.

**Comment by sderrow** [comment]
Awesome, that worked, thanks @mnightingale . I tried the same thing but with openssl 3.1.0 instead of 1.1.1, and couldn't get it to work. Should have tried 1.1.1!

Closing the issue now. Thanks again.
