### ISSUE TITLE
Minor UI change request

### ISSUE THREAD

**Issue by ItsME6969** [sabnzbd/sabnzbd#2580]
I like switching back and forth between tabbed and untabbed layout.
One of the things that's always bothered me tho is that releases that are done downloading are moved to history while still processing. So while using the tabbed layout there is no indication that there is a release still processing in the background.
Might not be a big problem on some systems but on systems with fast(10gbps) internet and regular hdds, that processing could be upto a couple minutes after the release is done downloading. That means the release was moved to history a few minutes before it actually fully completed.
Is it possible to change this behavior so that a release is only moved to history once it's completely done with processing and post-processing?

**Comment by thezoggy** [comment]
things for most people prob dont live in post processing state very long, unless you do a pp script or have crazy amount of things in your queue and not enough io to keep up with the demand (usually fallout of those doing direct unpack, limited unpackers or doing remote completed folder where there is a high amount of overhead on the unpacking/final state). 

Logically, things being downloaded are in queue, then moved to post-processing which then show up in history as things are being processed/have been processed. With history showing things in pp up top. So kinda all makes sense for it to be there?

To play devils advocate here, we know things being post-processed can affect the queue (direct unpackers / pause during pp/etc)  so makes sense to have it in the queue view. 

But you could also just use keyboard shortcut to change tabs/dont use tab view. Or you know with automation.. dont even need to look at it and just trust the system.

Now to be even more logic, why not add a 3rd tab for "processing" so that intermediate step is surfaced easier.. but still would cause you pains since your looking at queue.

**Comment by Safihre** [comment]
It's just a matter of definition and one that lots of external tools have gotten used to. Indeed maybe staying in queue makes more sense, ore even a seperate api call. However, this is just the way everyone is used to it now.

However, maybe we could add some counter to the history that allows to see pp vs. history items in tabbed layout.

**Comment by Safihre** [comment]
![image](https://github.com/sabnzbd/sabnzbd/assets/5703454/a52db390-7d64-410b-9915-166b1dd8590a)

**Comment by Safihre** [comment]
Its a design choice and people have gotten used to it now. It's also my personal preference.. so that's that 😜
