### ISSUE TITLE
Duplicate RSS sourced downloads not obeying paused state

### ISSUE THREAD

**Issue by icstm** [sabnzbd/sabnzbd#2698]
### SABnzbd version

4.1.0 [b7e3401]

### Operating system

Windows 10

### Using Docker image

None

### Description

I have a range of RSS feeds that load jobs, which are supposed to in a paused state. 
If sab spots a duplicate, and if duplicates are set to only "tag" rather than pause, delete etc, then the job is loaded as an active job and starts downloading, even though the RSS settings would have been to load the job as paused.

This is not the expected behaviour.
The DUPLICATE setting, if set to ignore or tag, should ensure the job is in the state a non-duplicate would be in, which in this case is paused.

This only impacts duplicate jobs, but the majority of jobs loaded by RSS feeds.

_Per [safihre] request, reporting here._

**Comment by Safihre** [comment]
This one is a bit complicated..
`Paused` is also a job-priority, so that's how we communicate from RSS to a job being added if it should be paused or not.
Additionally, we do something similar for duplicate detection. Because within RSS we do a separate duplicate check (only based on the RSS feed contents), we need to tell the job-add-code that it was a duplicate that should be tagged. But we also do that using a special duplicate-priority. After parsing the information, the priority is set to the priority it would have gotten from it's category.

I don't know if I can fix this in a simple way.
For now the workaround would be to set the category of the job also to Paused.

**Comment by icstm** [comment]
Hi, Thanks for your reply.
I tried your workaround, I changed the Priority for the category that the RSS feed chooses to Paused and left the RSS filters to paused (as they previously were).

Duplicate job still auto-downloading.

**Comment by Safihre** [comment]
You are right, there is some code checks that prevent that.
Fixing this requires a substantial overhaul with impact on many things, so it will take some time.

**Comment by icstm** [comment]
Thanks for keeping me posted
