### ISSUE TITLE
Support for encrypted file

### ISSUE THREAD

**Issue by abusenet** [sabnzbd/sabnzbd#2739]
### Description

It would be nice if SABnzbd supports files encrypted by `rclone` or similar. The "password" is stored in the NZB like usual, but there would be some way to detect that the file is encrypted, and let SAB decrypt it.

The nice thing about [`rclone`'s crypt](https://rclone.org/crypt/) is that it's a streaming algorithm, so not only we can "obfuscate" the file without archiving using `rar`, we can also stream it as more articles are fetched.

The same password is also used to decrypt file name.

No rar, no unpack, less CPU usage, and faster download.

**Comment by sanderjo** [comment]
I don't understand what you mean. But if you mean "no rar needed in usenet posts", then: correct. Already proposed by @animetosho some time ago, and already done with a lot of posts. And easy to check: in your NZBs, in the lines with "file poster" ... is there any rar file?

**Comment by sanderjo** [comment]
> This is a request to add support for decryiting files from Usenet. 

So that is already done with posts on Usenet? If so, can you give a NZB?

**Comment by mnightingale** [comment]
> There is no longer the effort to rar the original file, which can take a couple minutes. par2 may not need either, because there would be no missing articles due to DCMA/NTD. On reverse, SAB does not need to collect the parts to unpack, and do the recovery with par2. Depending on the file size, it could take a good 30 minutes or so.

I take issue with a few points here;
- par2 is useful because its computationally cheap to verify the file integrity
- articles can still be missing/corrupt regardless of takedown requests so par2 would still be required

---

I'm trying to get my head around how it could work.

Would a client need to write the encrypted file to disk first because of possible missing articles?

If so is that not the same as a single huge encrypted RAR? i.e. we still write the encrpyted file, maybe repair it (read&write), then decrpyt it (read&write).

I'm not familiar with streaming encryption but are you instead suggesting SABs download process would cut out one read&write cycle and only write the decrypted file to disk i.e. [download => yenc => decrypt] then write the result to disk?

Maybe because it's a streaming algorithm it could it handle missing articles?
But then PAR2 would need to be created against the decrypted file which would cause problems for other clients.

**Comment by thezoggy** [comment]
Then the issue is getting anyone to actually adopt the process to post. Which then you could probably just use a post processing script?

If you don't like rar then don't use it. Just realized that the majority of stuff you're getting is probably being done by a few select people using automated scripts setup decades ago for specific reasons. Usenet nntp is an old protocol that existed before things came about which required solutions to handle file names created on different filesystems than your own, even things like Unicode, or handling missing files, besides things like hash verifications, encryption/password or various obfuscations tactics. Where rarsets handle the requirements and then par2 for the rest. 

Honestly the pros outweigh the cons, and rarsets are generally used not to compress, so they take very little time to extract. I've worked with unrar dev and animetosho and made unraring even more optimized (can test it out in unrar 7 beta).

**Comment by animetosho** [comment]
> Articles are missing only on takedown request. But being encrypted on both content and file name, there is no base for takedown request.

You've got a rather optimistic view...

(personally, I think most obfuscation/encryption is pointless and a waste of effort; people seem to think it mitigates/eliminates takedowns, but show little evidence, and it logically makes little sense. I'll set this aside for this discussion though)

If you're going on the basis of encryption being necessary, and are willing to introduce a currently unsupported mechanism, I feel the most appropriate way to do it is within yEnc itself. You'd introduce some new field in the header to indicate that an article is encrypted, and the downloader could handle the decryption in the same line it does decoding.  
(this might also enable an update to the yEnc specification, which I think is sorely needed)

We've already got a huge mess with RAR to deal with, so minimising external dependencies (rclone crypt) would be preferable.

**Comment by animetosho** [comment]
Well an immediate objection I'd have is that rclone's crypt [states](https://rclone.org/crypt/#chunk):

> Each chunk will contain 64 KiB of data

Typical article sizes are 700KB or 750KB, neither of which are a multiple of 64KB. Implementations will thus need to cater for this misalignment, including blocks which straddle across article boundaries. This seems unnecessarily cumbersome and meaningless.

Sure, you could adjust things accordingly, but at that point, it's too uncertain to actually implement anything. You should draft up a precise specification which allows one to implement your scheme without any uncertainty, then seek feedback from multiple implementations.
