### ISSUE TITLE
API returns invalid JSON booleans

### ISSUE THREAD

**Issue by tunloop** [sabnzbd/sabnzbd#2785]
### SABnzbd version

4.2.1

### Operating system

Debian 12

### Using Docker image

None

### Description

I was using the API and noticed that it uses the Python JSON capitalized boolean values. I know this may not be your fault, most likely upstream python package, but I'll just leave this here.

According to the JSON specification from json.org and RFC 8259, JSON boolean values not inside quotations cannot be capitalized. 

This breaks tools such as JQ and Cyberchef (and most likely many others) from ingesting the JSON. 

I know that when querying the API I could just make every true and false lowercase, but this should really be handled as far upstream as possible.

**Comment by Safihre** [comment]
Can you shown an example?
I tested with all 3 of our json serliaizers (orjson/ujson/json) and everytime I get:

![image](https://github.com/sabnzbd/sabnzbd/assets/5703454/92ba1824-6684-4820-9ca9-d4a7e39457ba)

**Comment by Safihre** [comment]
Ah, you didn't specify `output=json` in your request. 
In that case you will get a text-response, which is Python serialization.

**Comment by tunloop** [comment]
> Ah, you didn't specify `output=json` in your request. In that case you will get a text-response, which is Python serialization.

Ah! haha, that took me for a ride. I thought it looked like a wild JSON. 

My mistake, its proper now : )

**Comment by Safihre** [comment]
We should probably make `json` the default if nothing is specified.. 
The `text` format is pretty useless..
@jcfp @thezoggy thoughts?

**Comment by thezoggy** [comment]
Having text/json/xml  prob doesn't make much sense in this day.. pretty much everything expects json. just the issue is some legacy apps never got around to updating to use sab json output.. but that's mainly abandonware.  I'll have to poke around to see if there's any concerns (browser extensions/add-ons/3rd part apps) to not go forward.

If we do depreciate/drop xml+text I would vote for it to be in 4.5.

**Comment by Safihre** [comment]
I would only change that the default is `json`, not dropping xml/text. Would you still expect problems?

**Comment by thezoggy** [comment]
> I would only change that the default is `json`, not dropping xml/text. Would you still expect problems?

yes if the app really isnt passing output=text and just using the default of text output, as changing that default would now break things for them / force them to update to do json.  i assume there are some random one off scripts and abandoned software from back in the day that just used text output for whatever the reasons, do we care about them.. probably not but still something to check before making that assumption.

why i figure if we are going to change default we prob could just prune out text output as an option since everything should* be using json.. as I dont recall anything ever using xml output. so if we prune out text+xml we prob could optimize things a bit for json only with code..

**Comment by thezoggy** [comment]
We should keep the output argument to maintain compatibility

**Comment by Safihre** [comment]
It wasn't removed? You can still use it to specify `xml`.

**Comment by thezoggy** [comment]
Ha yeah I deleted almost instantly as I was looking via phone. All good
