### ISSUE TITLE
Bring back rating system

### ISSUE THREAD

**Issue by dclintondclinton** [sabnzbd/sabnzbd#2878]
### Description

Reading up on the current state of the rating system and it seems every iteration is gone now.

On my old system the rating system using rating_host did a callback on failed jobs and the message included the news server used.
This was great to post as an user comment.

I would like to restore this feature, anyone want to split the load?

**Comment by Safihre** [comment]
It was removed because no indexer supported it.. And they mostly didn't implement it because most users use *arr programs anyway and never really look at the ratings or the posts on the indexer websites.

**Comment by dclintondclinton** [comment]
I think I had 60k comments posted, it was really nice to see what server still had the articles.
If written to specs it would be accepted right?

**Comment by thezoggy** [comment]
ratings never really made much sense from sab -> indexer point of view as the context of time/which server/etc. 
as things may be missing from the provider due to propagation / server issues / takedown.  then even if it was taken down it may have been recovered by someone updating the nzb and reposting.. or not taken down from the same provider in a different region. so nuance of where and when become a huge factor. which is not what the previous rating system worked..  which also speaks to why the ratings never got adopted by most, and those that used it complained about how it was worthless. so in the end, its just not really a useful thing to re-add.

**Comment by dclintondclinton** [comment]
I only want the callback on a failed job llike in the first iteration of the rating system.

**Comment by dclintondclinton** [comment]
What is the chance this being approved?
I don't mind spending the time on it.

**Comment by Safihre** [comment]
@dclintondclinton Any progress? :)

**Comment by Safihre** [comment]
Closing due to lack of response from @dclintondclinton.
Let us know if you have any updates, we can still consider it!
