### ISSUE TITLE
Add setup.py and/or requirements.txt

### ISSUE THREAD

**Issue by mrmachine** [sabnzbd/sabnzbd#366]
If SABnzbd had a `setup.py`, installation to run from source could be as easy as:

```
$ mkvirtualenv sabnzbd
(sabnzbd)$ pip install -e git+https://github.com/sabnzbd/sabnzbd.git
```

and then to run it, `path/to/venv/bin/SABnzbd.py [...]`,  or interactively:

```
$ workon sabnzbd
(sabnzbd)$ SABnzbd.py [...]
```

Alternatively, at least a `requirements.txt` file would make it easier for people to get up and running from source (e.g. if they are wanting to make a change and contribute back, or just always run the latest):

```
$ git clone https://github.com/sabnzbd/sabnzbd.git
$ cd sabnzbd
$ mkvirtualenv -a $PWD sabnzbd
$ pip install -r requirements.txt
(sabnzbd)$ python SABnzbd.py [...]
```

This latter option would have the disadvantage of not installing `SABnzbd.py` into the virtualenvs `bin` directory, which would make it easier to run.

Here's a sample `requirements.txt` file:

```
cheetah
pyopenssl
http://www.golug.it/pub/yenc/yenc-0.4.0.tar.gz
```

Here's a sample `Brewfile`, which would make it easier (on OS X) to install the non-python dependencies, for those using Homebrew:

```
brew 'openssl'
brew 'p7zip'
brew 'par2'
brew 'unrar'
```

Here's a sample `setup.py` file:

```
import setuptools


setuptools.setup(
    name='SABnzbd',
    version='FOO',
    packages=setuptools.find_packages(),
    install_requires=[
        'cheetah',
        'pyopenssl',
        'yenc',
    ],
    scripts=['SABnzbd.py'],
)
```

**Comment by Safihre** [comment]
Agreed, would be much easier!
Someone already tried to add this but didn't complete it: #242
Maybe you can submit a pull request for a working requirments.txt/setup.py?

**Comment by makefu** [comment]
I third this :) I want to create a clean installer for https://github.com/NixOS/nixpkgs/ .Right now it uses a custom build script but a default install with `setup.py` would be much better.

**Comment by Safihre** [comment]
I am not an expert on these things, but the problem is that it's platform dependent what needs to be installed and that not everything are packages. 
On Windows for example you only need 3 packages (Cherrypy, Cheetah, PyWin32) but you have to manually install a proper yEnc. 
On Unix you would need those first 2 but also Unrar and Par2 that are not available as packages... 
So maybe someone has a good solution to this, but we just couldn't find a good one..

**Comment by Safihre** [comment]
As a reference, this topic by JCFP who makes the PPA version,  has a very interesting dependency tree for the Unix tree. It's huge.. See the link in his reply:
http://forums.sabnzbd.org/viewtopic.php?f=16&t=19977

**Comment by makefu** [comment]
well that's too bad. As a reference, nixOS has a package with the dependencies: https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/sabnzbd/default.nix

The only 3 non-python packages required in path are par2cmdline, unzip and unrar .

**Comment by Safihre** [comment]
Which are also the most essential packages..
Since there is no way to install those from the python installer and that another essential package (yEnc) doesn't compile on Windows without extra tools, we decided against it. If we offer such a thing it should work all the time on any platform without extra tools.
