### ISSUE TITLE
Clearing Multi-Operation checkboxes

### ISSUE THREAD

**Issue by labrys** [sabnzbd/sabnzbd#405]
Python: 2.7.10 x86
OS: Win 10 x64
SAB: 4e20004f7b6315c97e18958b900e2d2dbf096233

When using Multi-Operations if you check several checkboxes to apply an operation, there is no easy way to remove the checkboxes.  

For example, say I pause 8 shows with multi-operation checkboxes.  Now I want to apply a different operation, say change priority to High for 4 shows.  Checking the checkbox at the bottom selects all on the page applying the current operation, so using that to clear the current selection isn't viable.    The user must uncheck all the checkboxes manually before changing operation.

Could this be changed to either make the select all checkbox start by clearing all or add a clear all selections button?

**Comment by Safihre** [comment]
Making the check all clear any checked ones (if there are any), feels counter intuitive. 
I understand your problem but not completely sure how to fix it elegantly.. How could we add this functionality in a way that makes sense? 
Maybe a double click to clear all (which we would explain in the tooltip)?
Just thinking aloud here, open for suggestions!

**Comment by labrys** [comment]
@Safihre My first suggestion would be, if any checkboxes are selected use a grayed out checkbox to represent a partial selection.  Then checking on it resulting in a cleared unselected state is similar to behaviour seen in things such as program installation.  A second click would then check the box, selecting all.   If that isn't viable a "Clear selection" button or similar could be implemented.  Also you have the feature already in place in plush (`Selection:  All ⋅ Range ⋅ Invert ⋅ None`). However, I think the greyed out checkbox would be more appropriate to the style of Glitter.

**Comment by Safihre** [comment]
Forgot to mention that in #402 I made it that clicking on the Multi edit button again clears all the selected ones and the selected options! 
It's not perfect, but at least a quick reset.

**Comment by Safihre** [comment]
In #409 I finally figured out that there is also this 'intermediate' checkbox style available in HTML (with the little dash). So now it will use that when you only select a few and clicking on it will uncheck the few checked ones.
Also the performance of (un)check-all is dramatically improved.

Also pushing everything I can out of the Javascript framework for large queues, small improvements. I would still recommend the (new) setting of 100 items for queue/history, since up to showing about 150 there's almost now slowdown.
