### ISSUE TITLE
sab -- handling nzb contents that is obfuscated with no visible parset

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#440]
tv show.. when completed sab's completed folder shows files: `75e524c64ef1e78c5a9cc42400914773fb94c4ec.01` to `75e524c64ef1e78c5a9cc42400914773fb94c4ec.34` 

which then results in sonarr not being happy since theres no media files.. 
if i rename .01 to .par2 and launch it.. it can then 'restore' as 0.0% blocks are lost... and even then there is files .28-.34 left that arent the rarset.. looking at the file i see they are the parset `PAR2 PKTD	     ^·¡Ô àsŽë&Cýªc¥BDr^ñZ]v,S1å•PAR 2.0 RecvSlic    Ÿ;Z¹¿ÄÀ*bÑë8Sù` so anyways suggesting that perhaps we inspect .01 to see if it happens to be a par (47kb) and if so.. try renaming it and seeing if this results in being able to verify/restore names... and do it.

**Comment by thezoggy** [comment]
ultimately its an issue on there end.. they served up this crap nzb from a 'misc>other' category before it was fully indexed i guess.. but anyways brings up yet another scenario we could try and work through...

sample nzb: https://nzbcache.info/nzb/7142f01dce3a58bd07d99ae8834c33c1ffd0ebe6.nzb.gz

**Comment by albino1** [comment]
I just got this as well with a different indexer.  Files are labeled .01 through .38 with no .par2 files.  SABnzbd obviously doesn't attempt a repair or extract since there's no pars and no rars.  The file with the .01 extension is 48kb and when you rename it to .par2 it opens in Quickpar and renames 30 of the 37 files.  The final 7 remaining files are also secretly par2 files, just labeled as .32 through .38.

I've gotten this in the past, but didn't think much of it.  Comparing it to @thezoggy's it appears to be the same poster and group, so maybe it's just that one uploader.

Following @thezoggy's lead, here's a sample NZB:

https://nzbcache.info/nzb/c321c53ce6ca0f99376ee1bdb93ebabab1368136.nzb.gz

**Comment by thezoggy** [comment]
just ran into this again.. but from another indexer.. :/  same thing as before. manually renaming .01 to .par2 and having it fix the filenames allows me to then just extract the rarset.

**Comment by shypike** [comment]
Are all the par2 files incorrectly names, including the smallest one?
Because SABnzbd already passes all available file names to par2, the bad names shouldn't matter.
However, this is not true for the first par2 file (without "vol" in the name).
It's likely that we must start checking the content of each file for the magic signatures.

**Comment by albino1** [comment]
The final output folder literally just looks like this:

![al-sabnzbd-nopars](https://cloud.githubusercontent.com/assets/12164957/12825702/76a4b406-cb2c-11e5-8cae-c7ed2cd483a3.jpg)

.01 is a small 48kb par2.  Renaming that and running it results in:

![al-sabnzbd-nopars3](https://cloud.githubusercontent.com/assets/12164957/12825817/ea2145d4-cb2c-11e5-8b12-4591cf61f00b.jpg)


.32 through .38 are also pars, but they don't rename when you run the initial par2 file.

**Comment by thezoggy** [comment]
its because that par you renamed only could handle that parset data to rename. the other files is another parset... just rename one of those to par2 and let it rename..

**Comment by thezoggy** [comment]
@shypike yes, we should add some logic that if upon completion we dont see a parset.. make a quick pass to identify a par.. stop after first one.. rename extension to .par2, let it restore.. then process. rinse and repeat until no pars are found.. by that time we should have completed the extracted data...

**Comment by thezoggy** [comment]
started to work on this, so far during the 'no par2 set' spot during the post-proc I have it scanning files (sorted by size - since smallest one usually is the par2) for par2 signature.. renames the first found then stops. so now im stuck in having sab know that ive done this to try and repair the files using this..  shy, you mind helping me with the rest of this code / point me where to look at how to tell sab that for this nzo there is a new par2 for it to use..

**Comment by thezoggy** [comment]
@shypike https://github.com/thezoggy/sabnzbd/tree/develop--obfuscated_parset
started to work on this.. need help to finish. curious if we should just look for par2 signatures in the `nzbstuff` `handle_par2` routine... but uncertain if you can pass a filename thats not .par2 to par..

**Comment by thezoggy** [comment]
worked with safihre.. we have this fixed and should be in an upcoming sab release.
