### ISSUE TITLE
sab 0.8.0b6 -- glitter - Status and interface options

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#445]
recent change broke the 'Status and interface options' modal from loading. just hangs at Loading now. yes I use firefox

**Comment by thezoggy** [comment]
just tried chrome.. also broken there

**Comment by thezoggy** [comment]
restarted sab again.. now its working.. odd...

**Comment by Safihre** [comment]
No, it happens when you click on it within 2 sec after page load. 
Because after 2 sec it will load the status info in the background to check for orphaned jobs and possibly show an INFO message. 
I cannot fix that bug, I tried many times, but otherwise Knockout crashes and burns. When you close the window and open it again, it will work fine.

**Comment by thezoggy** [comment]
odd, i loaded up a whole new browser and went to sab first time.. and it still wouldnt load that modal.. why i thought it was the recent timeout change..

**Comment by Safihre** [comment]
Will reduce the waiting time to 200msec, that should be enough now we do pre-loading!
