### ISSUE TITLE
sab 1.0.x -- history

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#478]
requesting the history from sab can be a very costly thing.. i see many things we could do to help make this more efficient on both the backend and the frontend.

lets start with glitter requesting the current max amount of history:
api/history?start=0&limit=500

some notes:

* internally we limit history to `1000000`

* we search internally using python not sql.. thus we have to iterate over every result.. 

  > really could optimize this to just use sql... 

* we internally .reverse() the history results (which can get pretty large when your talking about the data set of 1000000), then we append post proc queue (.reverse there too)

  > not sure why we do all this ant not in sql.. as we have to hold a copy of the history in memory to do these actions..

one time hit is fine, but then to ask for the same thing when 99% of the time its going to be the same (until a new item is parsed) is just wasted cpu cycles
leverage the fact that history is showing the results in order by __completed__ time and stuff in post proc on top.. means we can easily sub out the limit from __500__ to just __1__ to check to see if something changed..
now to know if something changed, we just need to calculate the hash of the row data.. compare it to the last computed hash to see if its changed.. thus querying for one row to compare a string is much quicker/less memory than requesting the whole data
(since im not sure just querying/storing the latest `nzo_id` is reliable?)

now to put this all together all we need to do is add a hash param to the history (or just auto do it when limit=1) so that we dont rely on browsers/javascript to do it.. 
    api/history?start=0&limit=1&hash=1

really rough pseudo code
```
if no hash value:
  query history&limit=1, store it
  query history&limit=x
if has value:
  query history&limit=1
    if hash == last_hash
      return
    else
      query history&limit=x
```

**Comment by shypike** [comment]
We **are** using SQL to extract the desired range.
database.py#260
```python
        t = (search, start, limit)
        cmd = 'SELECT * FROM history WHERE name LIKE ?'
        fetch_ok = self.execute(cmd + post + ' ORDER BY completed desc LIMIT ?, ?', t)
```
But I agree that history retrieval can be optimized.
Unlike the queue, it doesn't change all the time.

**Comment by thezoggy** [comment]
not sure what your comment is regarding exactly...  yes sql is used to get the base data.. but then python is used to clean stuff up / search over / etc which can become very costly in memory/cpu.

**Comment by shypike** [comment]
"We search internally using Python". That's not true. It's the conversion that is costly, so caching it is likely useful.

**Comment by thezoggy** [comment]
in the actual history routine yes you convert searches to sql, but I'm referring to the search param in the history api call:
https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/api.py#L1795
looking at it closer, its the queue your searching over not the history db.. so not nearly as bad as first through.. unless the queue is giant.

anyways, ill have to load up pycall/graphviz/etc and see how bad the history api command actually is/if its worth even messing with stuff.

**Comment by Safihre** [comment]
So I have been looking into this, since there were reports from users that couldn't even use Glitter because of large queues. I implemented a version of @thezoggy's suggestion, but while testing I found something else:
I now have 900 jobs in my queue of about 5TB of data, I display 10 and display 10 history items. Using current Glitter, my CPU usage **80%** (of 1 core) without any downloading.
It occurred to me that maybe it's having so much trouble because it is basically calculating the same thing at the same time, and indeed! When adding a 500ms delay between the queue and history API-call, response times drop dramatically.
![image](https://cloud.githubusercontent.com/assets/5703454/14047945/5839729e-f2ab-11e5-83c5-1011d95696fc.png)

Still, normally a history/queue API-call takes 30-50ms max, while now a history call alone takes 120ms+ when disabling queue-calls. 
Probably because of the ```build_header``` that also calculates all this stuff from the queue for the history output. @shypike why do we need all that info that's already in the queue call also in the history call?

**Comment by thezoggy** [comment]
with your changes, does this break the other skins / do they need updates?

**Comment by thezoggy** [comment]
https://wiki.python.org/moin/PythonSpeed/PerformanceTips

while there are some code optimizations we can do.. one thing ive always noticed is that we bury imports inside stuff.. which can be very costly:

https://wiki.python.org/moin/PythonSpeed/PerformanceTips#Import_Statement_Overhead
