### ISSUE TITLE
Connection Stops - Priority Setting Lost And Time

### ISSUE THREAD

**Issue by Geyup** [sabnzbd/sabnzbd#516]
Hello,

I'm not sure if this has been reported.

My Specs:

Linux
Firefox 38.7.1 ESR
SABnzbd 1.0.0
Python Version: 2.7.5 (default, May 29 2013, 02:28:51) [GCC 4.8.0]
OpenSSL: OpenSSL 1.0.1s 1 Mar 2016 [t1, v23, v3, v2]
pyOpenSSL: 0.13.1 

I noticed when I was downloading, and for whatever reason the download stopped, and it was just sitting there not doing anything, then when the connection resumed a few seconds later, I noticed on the far right where a remaining time is being displayed next to the trash can, the Priority option disappears when the connection resumes, and then the time no longer functions and just stays on 0:00

See the screen shots below.

In this screen shot you can see the Priority section and the time remaining is at 22:49

![sabnzbd_1](https://cloud.githubusercontent.com/assets/13072581/13940506/ec2d049e-efd5-11e5-81bb-b380f99853b1.jpg)

In this screen shot below the Priority section disappeared when the connection resumed and time is  now at 0:00

![sabnzbd_2](https://cloud.githubusercontent.com/assets/13072581/13940513/0f72cbc8-efd6-11e5-8997-da8ba32d25d4.jpg)

**Comment by Safihre** [comment]
The priority should only disappear when a download is fetching more par2 blocks after initial repair failed.

**Comment by Geyup** [comment]
Well this was happening just as I started downloading, about 15 seconds only into the download it stopped for a few seconds and then continued, and this is when all this happened.

**Comment by Safihre** [comment]
@shypike I do not know if this is related, but today I wanted to stop a download and I selected Priority: Stop.
This caused the download to go into post-processing, but instead of stopping it decided it needed more blocks. So it was put back in the queue with status = Fetching and time stayed at 0:00.
Only when pausing the job and unpausing I could try and stop it again. Weirdly now it was already at 800 of 900MB and when I stopped it shows the message: 
"Repair failed, not enough repair blocks (823 short)". That can't be the case..
This seems like a bug to me: Stop should be stopped.

**Comment by shypike** [comment]
"Stop" means: go to post-processing. This means that it's treated just like any other job that enters post-processing. The alternative is to just delete the job.
We added "stop" to get rid of hanging jobs (mostly when you have a bunch of missing articles and server(s) that time-out instead of admitting that they don't have the article).
