### ISSUE TITLE
When Downloading Queue Name/Section?

### ISSUE THREAD

**Issue by Geyup** [sabnzbd/sabnzbd#518]
Hello,

I'm not sure if this has been reported.

My Specs:

Linux
Firefox 38.7.1 ESR
SABnzbd 1.0.0
Python Version: 2.7.5 (default, May 29 2013, 02:28:51) [GCC 4.8.0]
OpenSSL: OpenSSL 1.0.1s 1 Mar 2016 [t1, v23, v3, v2]
pyOpenSSL: 0.13.1 

I noticed when something is being downloaded the name Queue remains shown at the Top Left of the GUI.

At first when using 1.0.0 I was thinking there would be two sections appearing, items sitting in the Queue section, and when a Download started, those moved to the Downloads section with that name appearing.

Right now this is not technically correct when downloading something to call that in the Queue, when a Queue is something waiting...

Another section should of been created, one for the Queue and another Downloads.

I see when downloads are completed there is a History section appearing, so the same idea.

Here's how this is looking for me when downloading;

![sabnzbd](https://cloud.githubusercontent.com/assets/13072581/13941277/3d64e62a-ef8a-11e5-80da-155e0afeb9a4.jpg)

This was always the same layout in the past, but with the release of 1.0.0 I was hoping this was going to change.

I hope this will change...

thanks

**Comment by albino1** [comment]
The files are in the Queue and the Queue is being processed, where's the confusion?  It's never been like you suggest in any version/theme of SABnzbd AFAIK.  Or any other download client, Usenet, Torrent, or otherwise for that matter.

**Comment by Geyup** [comment]
@albino1 What would you call after the Queue is processed?

From what I remember the GUI look of Plush in 0.7.2 and 1.0.0 is pretty much the same, with the name ```Queue``` appearing in the upper left.

Actually I've also never seen any other clients that confuse a Queue with a Download either, so not sure the point.

Even in the Computer World a ```Queue``` is a ```Waiting Point``` same idea, like a person waiting in a line...

After the wait is over the Job is moved from the ```Queue``` to where it needs to go, in this case, a ```Downloads``` section.

These 3 actions are not correct of a Queue

```Waiting Processing Downloading```

**Comment by Safihre** [comment]
SAB's terminology since it's origin has always been "Download Queue", which is shorted to "Queue" in **all** of the skins.
There is only Queue and then History, maybe not the perfect name, but this is how it is and I highly doubt it will ever change.

**Comment by Geyup** [comment]
I actually looked online to see how far back the name Queue dates, I found it going back to the 1890s, maybe it dates even further.

Well it's sad to see a name and process being misrepresented...

It would be nice if Queue only appeared when something was in it, then Downloads appeared when that process happend. Both appearing like how History pops up...

**Comment by thezoggy** [comment]
for sab, anything thats not finished is stuff that needs to be processed.. so stuff still queued up. 
might be the fact that the original dev wasnt american.. and over across the pond a __queue__ = waiting for something.

**Comment by Geyup** [comment]
Queue is waiting for something, I mentioned this...

Hence The NZB is added to the ````Queue``` to ````Wait```` to ```Move``` over into a ```Download```, then once a ```Download``` begins, the ```Queue Wait``` is over and a ```New Process``` begins, it is no longer a ```Queue```

The way the GUI should look if 5 NZB files are added and one is downloading, then four are sitting in the ```Queue``` waiting to download, and there should be a section called ```Queue``` that these foru are sitting in, and a ```Downloads``` section showing the actual download taking place. This is the correct way to do this, and I hope in the future it will change...

**Comment by albino1** [comment]
I would say that since an NZB is made up of thousands of smaller pieces, and those pieces are still waiting to be downloaded (AKA "queued up"), that it makes sense that it's still in the Queue.

And since 99% of the time at the most 1 NZB is being processed at a time, it's pretty simple to infer that the one being downloaded is the one being downloaded.  If you're so inclined, you can click on the NZB and it will take you to a new page where you can see which pieces are actually being downloaded in a much larger and more specific queue.

**Comment by Geyup** [comment]
Well yes it can be looked at this way, partial queue, partial download, but the fact is, it's at a download state...

You have 5 NZB added to SABnzbd, 1 is downloading, 4 are waiting, so 4 are the ones that are actually in the Queue, it should be looked at this way...

**Comment by Safihre** [comment]
You have a poiny, but splitting it up in 2 sections would be a little inconvenient interface wise. 
For historical reasons it's  most probably never going to change..

**Comment by thezoggy** [comment]
to play devils advocate.. i can see the confusion myself on this scenario:

I have this enabled: config > switches > Pause Downloading During Post-Processing
because I have sab transcode the release when completed...

thus when its done downloading it moves to the queue.. thus it may be misleading as you dont know whats going on when your using tabbed layout:

![sab14](http://zoggy.net/sab14.png)

as I'd have to switch to the queue tab to see why my main download isnt going... because something is still being 'processed'

![sab15](http://zoggy.net/sab15.png)
