### ISSUE TITLE
MySQL Backend?

### ISSUE THREAD

**Issue by thejrose1984** [sabnzbd/sabnzbd#524]
Tried looking around to see if it was possible to configure sabnzbd with a MySQL backend instead of using SQLite3. Any possibilities?

**Comment by jeffgeorge** [comment]
Not presently possible, and I seriously doubt we'd add it. MySQL would be an *incredibly* heavy dependency to add for very minimal gain if any. We use SQLite for our meager database storage because all we really need is something just barely more complicated than a flat file db, not a true comprehensive RDBMS.

**Comment by labrys** [comment]
@jeffgeorge I know its probably overkill since it would likely result in a significant rewrite, but if you ever decided to go the SQLalchemy route for an ORM based approach, it would simply be a matter of changing engines to use a different database.  And while imo SQLite is all that is really needed, the niceties that an ORM provides may be worth the effort.  A user being able to specify a different database engine would just be an added feature (not quite a bonus, since I don't see many people wanting or needing anything other than SQLite for this).

**Comment by jeffgeorge** [comment]
If we ever start seeing perf strain related to outgrowing SQLite I'm sure we'll end up investigating an ORM of some fashion, but right now I think we're good.

**Comment by labrys** [comment]
The thing I like about SQLalchemy is that it gives you the ability to write SQL statements directly or use  it as an ORM and when used with the default SQLite that comes with python as the engine, you have a pretty powerful tool at your hands.  That having been said, unless you have a need to rewrite the db stuff, its a lot of effort for little respective gain, especially in the short term.
