### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by scoobydoo1959** [sabnzbd/sabnzbd#547]
15/04/2016 01:23 [15/Apr/2016:01:23:57]  Traceback (most recent call last):
  File "C:\Media_Apps\Sabnzbd_1.0\cherrypy\_cpwsgi.py", line 180, in trap
    return func(*args, **kwargs)
  File "C:\Media_Apps\Sabnzbd_1.0\cherrypy\_cpwsgi.py", line 99, in __call__
    return self.nextapp(environ, start_response)
  File "C:\Media_Apps\Sabnzbd_1.0\cherrypy\_cpwsgi.py", line 410, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "C:\Media_Apps\Sabnzbd_1.0\cherrypy\_cpwsgi.py", line 234, in __init__
    self.run()
  File "C:\Media_Apps\Sabnzbd_1.0\cherrypy\_cpwsgi.py", line 349, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "C:\Media_Apps\Sabnzbd_1.0\cherrypy\_cprequest.py", line 617, in run
    raise cherrypy.TimeoutError()
TimeoutError

**Comment by shypike** [comment]
Internal time-out, can sometimes happen with very large NZB file or other lengthy actions.
What were you doing?

**Comment by Safihre** [comment]
Same as #497.
It will give that error after the timeout, which according to the manual you cited is 300 sec. So maybe we are better of just setting it to unlimited (if possible, otherwise very high value). Because in Glitter and Plush, we set the timeout of the browser to be 10 or 30sec, so the browser isn't even listening to the response anymore.. And if an action takes long but still competes, that's just the way it is. 
So let's just control the error.

**Comment by untotren** [comment]
"Internal time-out, can sometimes happen with very large NZB file or other lengthy actions.
What were you doing?"

--This is unacceptable, this cannot be behavior that is acceptable.

SAB team needs to get their shit together.  They release version 1 and it's just as shitty as ever.

**Comment by Safihre** [comment]
So turns out only real API-calls are limited to 10 seconds. I was adding 600 jobs back to the queue for testing purposes using 'Add all' (non-API), which took to long:
![image](https://cloud.githubusercontent.com/assets/5703454/14602049/fda13ac4-0565-11e6-84a5-02c8ef39d6de.png)
Even though SAB itself was responsive just fine, that 1 request took too long even though the adding itself completed just fine.

I would opt to extend the processing time to 10 minutes for API-calls instead of just disabling it, this way any 'garbage' threads are still killed at some time.
Like this: https://github.com/Safihre/sabnzbd/commit/8cf14746a280d2b7d2483aef6a3b2c8d28f2c731

**Comment by shypike** [comment]
Solved in 9239fa0ac5500caa0d02cdcbeb9ae66196cac4b
