### ISSUE TITLE
Have version.py reflect the actual version

### ISSUE THREAD

**Issue by rkleijwegt** [sabnzbd/sabnzbd#571]
A recent commit b7e2bd96844d85623458ea5ad02432becdb199e5 shows that several text files are updated to reflect the latest version. However in the origin/1.0.x branch version.py only shows 0.8.x [unknown]. This was last updated back in 2012 6737704b15dfb4d025b71f11f38e7453dca549b5.

What is the idea behind this disconnect?

It would seem more logical that version.py actually reflects the current version.

**Comment by shypike** [comment]
We patch version.py during the build process to the actual release number.
If we update it in the repository it won't be correct for people who use SABnzbd directly from a git branch.
Having said that, version.py in the "develop" branch should say "1.1.x", because it will be leading to the release of 1.1.0.

**Comment by rkleijwegt** [comment]
OK, fair point. As long as it's something that was done deliberately. It didn't seem logical to me. So I thought I'd raise an issue about it. Guess I'll keep checking the text files.
