### ISSUE TITLE
sab 1.0.x -- config > rss

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#572]
setting the rss interval then saving, the value for `Next scan at: ` does not update until you manually refresh page. also that value should note if its being delayed by the scheduler to the side (clock icon? with tooltip) since the not underneath `Not active when you use the Scheduler!` only makes sense if you know what the scheduler/remember setting it up/know how to check it.

**Comment by Safihre** [comment]
Fixed it in ebc2f15 in #565  by restarting the scheduler just like when adding scheduling events, since that's really what it is.
Think people who use RSS will understand what the Scheduler is, since have to specifically set up an event for RSS for the interval to be disabled, that's not something that happens on accident, is it?

**Comment by Safihre** [comment]
Fixed (except for the text), close?
