### ISSUE TITLE
"Tuning" and throttling speed limit

### ISSUE THREAD

**Issue by Yankee14** [sabnzbd/sabnzbd#587]
`$ lsb_release -a`
`
Distributor ID:	Debian
Description:	Debian GNU/Linux testing (stretch)
Release:	testing
Codename:	stretch
`

`$ uname -a`
`Linux debian 4.5.0-2-amd64 #1 SMP Debian 4.5.4-1 (2016-05-16) x86_64 GNU/Linux`

`$ sabnzbdplus --version`
`sabnzbdplus-1.0.2`

I did an upgrade recently and I noticed that the functionality for throttling the connection has changed dramatically. The old way was very easy and intuitive to use; you just typed in the speed you want, and off you go. Now, I have to go into configuration, figure out what my maximum line speed is, and base the throttling rate as a percentage of my maximum line speed. I change my physical location often enough for this to be a severe inconvenience, and I relied upon the ability to just simply type in a speed.

Is there a way to get the simple functionality back?
Why was the old way regarded as needing improvement?
Thanks.

EDIT: As a workaround, I tried to restore the old functionality by setting my "maximum line speed" to 1kbyte/s. This should have let me enter something like 4500% to get 4.5Mbyte/s, but it didn't work.

**Comment by Safihre** [comment]
What skin do you use?
Yes, Glitter only allows in %. But this is very user friendly using the slider, I also work on multiple locations but setting it to the max of 50MB/s of work still allows me to throttle it at home by just using 10% for 5MB/s.
In case of Plush there is an option how to input it however you like:
![image](https://cloud.githubusercontent.com/assets/5703454/15735511/c43bbc08-2899-11e6-86b2-97032b008551.png)
Only SMPL doesn't have a nice visual way, but there is also a trick that's indeed not explained anywhere but still works:
You can also type values in K/M/G notation. So instead of typing a percentage in the SMPL box you type 4.5M and hit enter, the speedlimit will be set to that.

**Comment by Yankee14** [comment]
Thanks for your quick reply!

> Only SMPL doesn't have a nice visual way

I guess thats in the eye of the beholder; I've been using simpl - black for 4 or 5 years now and I liked the way it worked. I tried the trick you explained and it works great! Thank you very much for that. I'm just sad it had to change like this. It feels like somebody somewhere ignored the old adage "if it ain't broke, don't fix it." But I understand why this kind of change would be needed on the other interfaces in order to implement things like slider bars.

This issue can be closed, but I strongly recommend bringing back the old KISS functionality to the simpl interface(s). Maybe the the throttling style could depend upon which interface is loaded?

**Comment by Safihre** [comment]
> EDIT: Will your trick stop working in a future update?

No the trick will stay because this is also how it works for the scheduler :+1:

**Comment by Safihre** [comment]
@shypike Close?
