### ISSUE TITLE
New sabnzbd.org website

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#590]
With a new logo, comes a new website! 

I have been working on a new design for a bit and hope to get some feedback on what I made so far. It is to be hosted on GitHub pages so it's easy for everyone to make changes.

**Frontpage:**
http://safihre.github.io/
**Wiki:**
http://safihre.github.io/wiki/
http://safihre.github.io/wiki/1.0/switches
http://safihre.github.io/wiki/1.0/folders (I ported all of the 1.0.0 config pages)
http://safihre.github.io/wiki/quick-setup

The download button on the frontpage will download the version for the platform you use to visit the website (Windows/OSX/Linux, in case of Linux I want to add a link to the instructions for the PPA underneath). The button is dynamic to always show the latest release, in case there's a beta it will show 2 buttons (example see below).
The screenshots need to be re-done using "approved" downloads and proper captions, but that's for later concern. Porting the Wiki-pages is for now just copy-paste of the original wiki's HTML, it's relatively clean but could use some optimizations. For example the API page really needs work.
And we would also need 301-redirects from the old to the new wiki pages.

For now I would like to hear what you think about the design/feel and structure of the website.

![image](https://cloud.githubusercontent.com/assets/5703454/15932022/602a5c26-2e5a-11e6-9621-7580a86faecc.png)

**Comment by jeffgeorge** [comment]
Thanks so much for taking over this effort and running with it.

Couple notes:
- For screenshots of the UI that we want to redact sections of, consider temporarily hacking Glitter to use something like [Redacted-Font](https://github.com/christiannaths/Redacted-Font) (specifically, Redacted Light). in some sections of the admin.
- The Dynamic Download Button is great, but I think it could use some more words indicating the Call to Action. I'll see if I can dig up my old notes regarding what I was thinking about actually putting in and around the main download button.
- Also regarding screenshots, employing some sort of Colorbox-ish popup or at least `target="_blank"` is probably a good idea.

Regarding 301's and the Wiki, If we're planning on switching from wiki.sabnzbd.org to sabnzbd.org/wiki (so the wiki and site would be in one big repo, which is fine), I can handle the 301's on my server once we know the destination site structure.

**Comment by Safihre** [comment]
Thanks! Will use that redacted font indeed and make the screenshots pop a little better. I already added 'Download' to the download-button, but indeed maybe other wording might be better!

Added more pages to the Wiki, but some of them are greatly outdated or contain duplicate/conflicting information. 
It won't take me too long to transfer all the pages, but it actually might need some more updating of the text and HTML that will probably take longer..

**Comment by sanderjo** [comment]
Hi,

Impressive task, @Safihre 

My suggestions (not meant to be harsh):

Overall: less text and less info on the frontpage. (Example: https://endlessm.com/ )

Upper right corner: Just "Download", plus "other downloads". No Changelog, no Ubuntu PPA.

"The totally free and incredibly easy to use Binary Newsreader" ... correct, but a lot of text and possibly complex for NNE (Non-Native English) readers. Suggestion: "Free and Easy Binary Newsreader"

"In your languague": "In 15 languages", and then show also non-Western flags.

"It Runs Anywhere" ... dangerous claim, because of ... but not Android. I would say: Windows, OS X, Linux, and others. And mention "certain NAS-devices" in the text.

"Customizable Themes" ... I wouldn't say that at all; Glitter is the way forward, isn't it? ;-)
I would emphasize: accessible from your phone and tablet.

"Easily Extensible" I would not say that on the frontpage as it's only relevant for the subgroup of developers. Maybe under the dropdown of Documentation?

"Contribute to SABnzbd!" I would not say that on the frontpage as it feels like begging for a financial contribution, which it is not.

**Comment by thezoggy** [comment]
also maybe revise some of those screen shots so its not trying to promote piracy :)

**Comment by Safihre** [comment]
@sanderjo I like your suggestions. The PPA-text only shows up for Linux users, not other OS's. So assuming those are not novices :)
Would you maybe have time to make 4 texts and pictures to go with the texts in the 4 blocks on the frontpage? Or some other organisation for this information. Maybe you have more inspiration than I do!

**Comment by Safihre** [comment]
Do we really need separate Wiki-config pages for 0.7?
Could just redirect them to the 1.0 ones?

**Comment by shypike** [comment]
What I did before was make a clone of each page that was significantly different.
A release can point to a mix of old and new pages.
Since 1.0.0 has large differences in the Config pages, compared rto 0.7.x, they needed new ones.

**Comment by shypike** [comment]
The 0.7 pages are quite different than the ones for 1.0 (like moving options around between pages).
I expect 0.7.x to be around for a while.

**Comment by Safihre** [comment]
:sob: so much work for update-resistant users. 
But guess you're right.

**Comment by Safihre** [comment]
I decided to only show the latest stable on the front page and add a separate downloads page
http://safihre.github.io/
http://safihre.github.io/downloads

Also bringing back 0.7.x Config pages:
http://safihre.github.io/wiki/configuration/1.0/folders
http://safihre.github.io/wiki/configuration/0.7/folders

Still working on getting all  the links fixed.

**Comment by shypike** [comment]
I'm impressed!
@inpheaux Will sabnzbd.org do the redirection or do we have to have links to github in the source?

**Comment by shypike** [comment]
@Safihre I see that the pages are in (sort of) HTML.
Is that the language to edit in or is this generated code?

**Comment by Safihre** [comment]
For now they are html, copied and butified from Wikidot. But it also allows pages to me written in markdown (like when writing a comment on github). So for new pages you can choose, whatever works for the writer.

**Comment by jeffgeorge** [comment]
Once Safihre gets something deliverable we'll push the lot of it to https://github.com/sabnzbd/sabnzbd.github.io. Once we confirm it all at https://sabnzbd.github.io we'll be able to set it up so the whole site is served up by Github directly at the sabnzbd.org domain.

Also, so we can drop Wikidot, I'll be setting up a vhost on my server that handles all the 301 redirects from old `wiki.sabnzbd.org/*` paths to new `sabnzbd.org/wiki/*` paths (or `sabnzbd.org/manual`, or whatever).

Github Pages are built with Jekyll, which is a simple static-site templating . . thing . . You can build out pages with simple HTML templates with includes, or with Markdown, or whatever. From looking through [the repo itself](https://github.com/Safihre/safihre.github.io) it looks like Safihre has gone the route of a very lightweight template (header, content, footer), and then mostly has content in raw html. 

That's great for complex pages with a lot of complex layout stuff (like the Downloads page), or for bulk-migrating content from Wikidot, but eventually I can see us migrating most general content pages over to Markdown for ease-of-editing. Plus, since it's all in another Github repo, we can accept changes to the Wiki via Pull Request.

**Comment by Safihre** [comment]
@jeffgeorge Exactly what I was thinking. For now HTML, but new pages probably in Markdown.

The redirects will be a little more complex probably, but I had to write a find-and-replace script anyway for the conversion. So we can output this list in any form that works for the redirect ```.htaccess``` or etc.
https://github.com/Safihre/safihre.github.io/blob/master/replace_old_links.py

Using this script I have now updated all pages to reflect the right links everywhere. 

Very close to completing the transfer :smiley:

**Comment by Safihre** [comment]
@thezoggy Can I use your API page as a base for the new API wiki-page?
http://thezoggy.github.io/sabnzbd/api

Much better than what's in the current Wiki to start with.

**Comment by thezoggy** [comment]
cloned the sb-api page i made and started to put in some data.. but gave up pretty quickly as shy and i were talking about having it auto gen... readthedocs/doxygen/etc..

**Comment by Safihre** [comment]
Updated the frontpage with the help of @sanderjo:
http://safihre.github.io/
Downloads-page now done:
http://safihre.github.io/downloads (automatically updated)

Cleaning the Wiki pages.. Lots of outdated stuff and references to versions below 0.6.x...
http://safihre.github.io/wiki/installation/install-off-modules
Wiki could use some new pages, but I can only write about the things that I know.. Hope others will add new info in the future.

**Comment by jeffgeorge** [comment]
Regarding the Download Buttons, can we get some kind of text in there indicating exactly which build the button would download? Something like:

"Latest Stable Release - [OS Identifier]"

Where [OS Identifier] is "macOS dmg", "Windows Installer" or "Python Source".

Then, below it, have the "Other downloads" link say "Downloads for Other Platforms and Release Notes".

**Comment by Safihre** [comment]
@jeffgeorge Updated! But the part about "Release Notes" became almost wider than the button, so kept it to "Downloads for other platforms".
Also removed the part about stable/unstable from the button. Less text is probably better.

**Comment by Safihre** [comment]
@jeffgeorge I'm done I think, everything is transfered. There is the mapping from old URLs to new ones. What else? 

Yes, some texts of the wiki could use some updating. But die already quite a lot of them :)

**Comment by thezoggy** [comment]
need to update the fact that we only support 2.6 and 2.7 now (not 2.5):
http://safihre.github.io/wiki/faq#toc5

**Comment by Safihre** [comment]
@thezoggy Updated, removed any reference to Python 2.5 and below.

@jeffgeorge Updated all the screenshots on the homepage, they are now 'redacted'.
Ready for the next step :star2:

_For future reference, by adding these lines to Glitter's CSS and having the Redacted font installed you can make 'safe' screenshots:_
```css
td.name,
.hiddentext,
.item-files-table span>span,
.modal-title.row-wrap-text,
.history-status-table .col-sm-10 {
    font-family: 'Redacted Script Light' !important;
}
 ```

**Comment by jeffgeorge** [comment]
https://sabnzbd.org <- Now Live via Github

Thanks for all your work getting this done @Safihre!

**Comment by thezoggy** [comment]
congrats all on the shiny new site, looks so much nicer
