### ISSUE TITLE
Sabnzbd 1.1.0Beta1: Language screen in wizard missing languages

### ISSUE THREAD

**Issue by Dr-Bean** [sabnzbd/sabnzbd#593]
During testing the beta package, I noticed that the languages/language flags don't show up in the wizard. Next steps work as expected. See http://imgur.com/YVSbywV (uploading on Github seems broken...).

Tested on Firefox, Chrome and Iceweasel with a clean profile, so I don't think it's browser-related.

The log (sabnzbd.log) doesn't show anything of interest, just the normal startup sequence. Sabnzbd-error.log is empty. Restarting doesn't help.

**Comment by Safihre** [comment]
On linux systems when running from source, this command has to be executed to compile the languages:
```
python tools/make_mo.py
```
It's also in the README, but easy to miss!

**Comment by Safihre** [comment]
Actually as far as I understand the SynoCommunity package, it should download the ```SABnzbd-1.1.0Beta1a-src.tar.gz``` file and use that, right?
I just tested that package and it includes the compiled languages and shows the languages on the wizard.
We did update that one last night (it's now Beta1**A** instead of Beta1 because of another small error), maybe this helps?

**Comment by Dr-Bean** [comment]
Yep, that's it. I guess I missed that file in the list. Thanks :)
