### ISSUE TITLE
Password field in wizard is not hidden

### ISSUE THREAD

**Issue by BenoitAverty** [sabnzbd/sabnzbd#611]
In the wizard, when setting up the news server, the password field isn't an` input type="password"`, so the password is visible in the field.

It should be changed for security reasons.

**Comment by Safihre** [comment]
This is done on purpose. It turned out that after that page, the browser would suggest to save the password and many users would do that. This would cause the browser to later aggressively fill this information in *all* the username and password fields in the Config. Causing people to be locked out of Sabnzbd because the browser set the newsserver username and password as the Sabnzbd username and password. Lastpass and KeePass are even worse. Every time when we alter the forms in the Config to not be auto filled, a few months later they still do. 

Setting  it to password type doesn't really add any security or encryption etc. In 99% of cases the username and password are copy pasted from some email or website anyway.

**Comment by Safihre** [comment]
This was also reported before, but can't find the issue or forum thread right now.

**Comment by BenoitAverty** [comment]
Couldn't this be solved by simply using different names/ids for the inputs? for example newsserver_password, sabnzbd_password, etc...

I'm aware that the password type doesn't add much security, but many people have a bad impression or "unease" when forced to type a password in a clear text input. Moreover, the "password" type has semantic value and some browsers may use this to provide a better user experience. For example, on mobile, typing in a password input doesn't trigger any autocorrect. There are also text-based browsers, readers, etc...

**Comment by Safihre** [comment]
Try it, the browser (and particularly Lastpass)  doesn't care what the name is. It can even be called a completely random name like '58hsjnahdjej' as long as it's a regular text field followed by a password one, it will suggest to save and autofill it. We had this problem numerous times where users blame sabnzbd for locking them out or changing server settings, while actually it was the browser/passwordmanager. 

Agreeing completely on the semantic value for normal use, but in the case of Sabnzbd: Who will setup their sabnzbd from a mobile device or using a text browser?
