### ISSUE TITLE
Checking Files Before Download - Sonarr

### ISSUE THREAD

**Issue by SphinxJ** [sabnzbd/sabnzbd#645]
Any chance in getting an option to check all files before download for all but Sonarr files? Maybe I can set a category for Sonarr and then all the other files in the queue would be checked before download.

Sonarr creates a warning with the pre-check enabled when testing the connection to sabnzbd.

Thanks in advance!

**Comment by Safihre** [comment]
Why not use "Abort jobs that cannot be completed"? Granted, it will take SABnzbd maybe a minute or 2-3 to figure out it can't complete it, but it's much faster than Check before download, since that one will check the whole download.

**Comment by SphinxJ** [comment]
That is an option, but I use that already. I turned on the "Check" option to help with bad downloads, which has helped tremendously. With that being said, this is why I suggested adding this feature.

Thanks for the quick reply.

**Comment by Safihre** [comment]
Do you notice the Abort that cannot be completed takes too long to cancel an obviously failing download? Or did you have cases where it didn't Abort even though it should? 

I will admit that I don't think your request will be implemented, since it's a lot of work and for mainstream users the Abort function should do the trick.

**Comment by SphinxJ** [comment]
I will go back to just using the "Abort" function and see if I still see the error. Prior to enabling the "Check" function, I would see several failed downloads due to not enough repair blocks or other issues.

I think it would be worth having the option to not check Sonarr files, but if it will take a ton of work, then I understand. I didn't know if that would be an easy addition.

**Comment by shypike** [comment]
A selective pre-check wouldn't be very hard to implement. Only the UI is a bit of a puzzle.
On the other hand, we don't really want to promote the feature, because it wasn't such a good idea in the first place. There are too many pitfalls.

**Comment by SphinxJ** [comment]
Can you explain what you mean about the pitfalls? I assume you are referring to "Check before downloading" option.

**Comment by shypike** [comment]
You cannot predict accurately whether or not a download will be a success. NZB files list bytes including the unpredictable yEnc encoding overhead instead of real sizes. par2 works with blocks and you cannot determine exactly how many blocks are damaged or missing. That's why we use a threshold, which may fail potential downloads and may still try unsuccessful ones.

Some indexers replace removed posts with fake articles (saying "removed" in the content).

For many indexers querying for presence is almost as slow as the actual download of an article.

**Comment by thezoggy** [comment]
perhaps a better use would be to limit the checking for only posts larger than x size? a 1:1 bluray (50gb) takes awhile to d/l and a while to check.. but checking would save you a bit of time and bandwidth if it just isnt going to work..
