### ISSUE TITLE
Combine RSS feeds to share filters

### ISSUE THREAD

**Issue by shypike** [sabnzbd/sabnzbd#680]
If people use more than one indexer, they may be re-entering filters for each one.
Allow one set of filters to work in multiple RSS feeds.

**Comment by Safihre** [comment]
Personally I don't this is worth the time, how many people actually still use RSS in the age of Sonarr/CP?

Yes, we should make RSS evaluation faster, but to make it possible to have 1 set of filters for multiple feeds seems like a lot of work for very few users that only need to enter these filters once in many years.

**Comment by thezoggy** [comment]
plenty of people still use RSS.. some rely on using it over those automated programs.. some use it because thats just how they like to work... for example i dont like CP  :)  tv/movies is one thing.. but when you start doing music/comics/etc.. rss kinda becomes a huge pita unless you can do stuff with it.. since the source rss feeds filter/controls are usually lacking..

**Comment by mgaulton** [comment]
I found using rssmix at least for not personalized rss feeds worked well.
