### ISSUE TITLE
sab - 1.2.x -- ppa patches

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#689]
@jcfp can probably chime in on this as I'm talking about his ppa version of sab.. it has an init script and patches to modify sab...  perhaps we should take the time to look at them to review and see if theres anything we should change to help out.. 

https://launchpad.net/~jcfp/+archive/ubuntu/ppa/+packages
grabbed latest `sabnzbdplus_1.1.0-0ubuntu1~jcfp1~yakkety.debian.tar.xz` and opened via winrar, navigate to the `debian\patches` folder.

`02_find_parts_in_usr_share.diff` + `04_use_config_when_daemon.diff` -- I assume this is needed for multi-user type installs? 

`06_use_packaged_modules.diff` -- not sure why this one exists...

`08_disable_new_version_check.diff` -- we could add the ability to just disable the update check via startup argument.. which then we could add the check in the various spots and save jcfp modifying 3 files.. 

`09_remove_external_resources.diff` -- we could just do this ourselves to eliminate user/ip leakage by requiring 3rd party sites... move the v6 check to sab test instead of using google..

**Comment by jcfp** [comment]
02 enables installing sab in line with the [fhs](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)
04 restores storage to the user homedir in case the program is run with arg -d but without -f, to prevent it from trying to write ini and more in /usr/bin. That used to be the default in pre-fork times but it was changed to work around a windoze-only problem (where local system accounts used for services don't have the equivalent of a homedir set iirc).
06 loads some modules from the system python rather than the included copy, as required by the distros.
08 does what it says on the tin. Needed because users cannot successfully update by just overwriting existing files with those from a newer release, which is what they keep trying to do when that big fat warning shows up. A startup arg still wouldn't cover all use cases here.
09 attempts to remove code that could allow tracking of end users at runtime, along the lines of the _privacy-breach-*_ items in [this list](https://lintian.debian.org/tags/). Note that this includes connecting to systems currently under the control of the sab project. Most of this patch deals with the ip address lookup, by running the "leaky part" only when debug logging is on.

As you can see, most of the patches deal with install requirement or distro specific wishes. Not unnecessarily adding or running stuff that has the potential to be abused for tracking would be helpful though.

**Comment by shypike** [comment]
@jcfp Regarding "09". It's the usual trade-off between privacy and ease-of-use. The code is very helpful in problematic cases, but can indeed be explained as "phone-home".
I don't think Debian and Ubuntu remove all "phone-home" stuff from Firefox.
BTW: as soon as I run "apt-get update" the OS distro people are tracking me.

**Comment by jcfp** [comment]
@shypike agreed, and exactly why I kept that function around for debugging purposes.

**Comment by thezoggy** [comment]
why was this closed?

**Comment by Safihre** [comment]
Seemed to me the explanation by @jcfp for each item made sense? 
Nothing for us to change in the code, all distro stuff.

**Comment by thezoggy** [comment]
he made sense on why hes patching, not that we shouldnt change anything to make his life and other distro's lifes easier..

**Comment by Safihre** [comment]
So what shall we change? :)

**Comment by shypike** [comment]
Some of the modules in sabnzbd/utils could be moved to the root, so that JCFP doesn't have to patch paths for feedparser, listquote and configobj.
I'll look in more detail to his other patches.

**Comment by Safihre** [comment]
Checked the latest patches for 1.2.1Beta1, and it seems there's nothing in there that we can change from a SAB point.
