### ISSUE TITLE
500 Internal Server Error in 1.1.1RC1 and 1.1.1RC2

### ISSUE THREAD

**Issue by ChristopherHaws** [sabnzbd/sabnzbd#714]
I seem to be having an issue loading the apps home page. I am getting the following errors for several minutes and then the app will be accessible again. The app itself is still running and downloading, its only the web frontend that is failing.

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "cherrypy\_cprequest.pyo", line 670, in respond
  File "cherrypy\lib\encoding.pyo", line 263, in __call__
  File "cherrypy\lib\encoding.pyo", line 172, in find_acceptable_charset
  File "cherrypy\lib\encoding.pyo", line 116, in encode_string
MemoryError
Powered by CherryPy 6.0.2
```

and

```
500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "cherrypy\_cprequest.pyo", line 670, in respond
  File "cherrypy\lib\encoding.pyo", line 220, in __call__
  File "cherrypy\_cpdispatch.pyo", line 60, in __call__
  File "sabnzbd\interface.pyo", line 407, in index
  File "_Program_Files__x86__SABnzbd_interfaces_Glitter_templates_main_tmpl.py", line 526, in respond
  File "Cheetah\DummyTransaction.pyo", line 57, in getvalue
MemoryError
Powered by CherryPy 6.0.2
```

SAB Version: 1.1.1RC2 [01d668a]
Python Version: 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)] [cp1252]

**Comment by thezoggy** [comment]
how much ram does that machine have and how large is your queue?

**Comment by ChristopherHaws** [comment]
OS: Windows Server 2012 R2 Standard
Host: Virtual Machine
Cores: 6x 3.2GHz
RAM: 6GB

SABnzb Process:
CPU Usage: 9%
RAM Usage: 521MB
Handles: 692
Threads: 48

My queue size varies between 10 and 30 items.

**Comment by thezoggy** [comment]
how much ram are you giving your vm?

**Comment by thezoggy** [comment]
this isnt hosted remotely like pythonanywhere is it?

**Comment by ChristopherHaws** [comment]
The VM has 6GB. The host has 24GB.

**Comment by ChristopherHaws** [comment]
Nope. This is hosted in my downstairs closet :)

**Comment by thezoggy** [comment]
what other things are running in the vm then? 
apparently there is certain vm env dont play well with cherrpy/python in general -- https://www.pythonanywhere.com/forums/topic/637/

**Comment by Safihre** [comment]
I also saw your logs, and it's full of ```Delaying``` meaning that it runs out of memory and has to slow down the downloading. 

There is something about python on Windows Server editions, also on the forums there are the bugs that only seem to happen for those.. 
What happens if you run it on the actual machine, not the virtual one?

**Comment by ChristopherHaws** [comment]
Well, I am one patch version out of date for pythod LTS. I could try updating that. Does SABnzb support python latest (3.5.2)? I guess it could be possible that this is a python issue, but I have been running SABnzb without this issue for about 2 years. It only seems to have started with the latest RC version.

Thanks! :)

**Comment by thezoggy** [comment]
sab only runs on python 2.6.x+ 
python 3.x you can view as a difference language, similar but is in a different syntax... slowly we are getting towards supporting it though

**Comment by thezoggy** [comment]
@ChristopherHaws I would suggest reverting back to a previous release to help us bisect what change is causing you issues...
https://github.com/sabnzbd/sabnzbd/releases

I see your running binaries.. have you tried just running it from source/with python itself? perhaps the issue is how the binary package is being built for your setup..

**Comment by Safihre** [comment]
Do you run it as a service? Something changed in Windows (because we didn't change the way sockets are read or articles are decoded). 
Clearly it's not giving python the memory it needs, but why. 
What do you have set for Article cache? Maybe reduce it to 250M, we did update that to 450M.
But first try not running it as a service, that might do the trick.

**Comment by ChristopherHaws** [comment]
No idea how, but the article cache was set at 2GB. I set it to your default 450M setting. I will see if that fixes the issue, if not I will try not running as a service as you mentioned.

Thanks!

**Comment by thezoggy** [comment]
@Safihre can confirm, but 2G should be fine, assuming that you have the ram for it to allocate..  and probably is only going to be used if your d/ling some really crazy large nzbs....

**Comment by Safihre** [comment]
@thezoggy is right, and seeing you mention that SABnzbd uses ```RAM Usage: 521MB```, this is quite an odd number for me. It almost seems that it's cut off at ~512MB+overhead and probably it's limited at that amount by the OS.
Because when Python throws a ```MemoryError``` it really means it's not allowed _any_ more memory.
On my Windows10 box I have seen memory usages of 2.5GB (when I made a coding mistake) and that was handled just fine.

**Comment by Safihre** [comment]
@ChristopherHaws any luck with the new cache setting and/or not running as service?

**Comment by ChristopherHaws** [comment]
So far so good. I am going to close this issue and will reopen it if I see the issue again. Thanks!
