### ISSUE TITLE
Overhead with 3000 yenc lines

### ISSUE THREAD

**Issue by Nemesh64** [sabnzbd/sabnzbd#735]
Hello to all,

Had my first contact about this issue with Shypike at 4 Sept 2016.
This issue occurs when your downloadspeed is well above 200 mbit and you download a post witch is posted with 3000 yenc lines.
The max downloadspeed SABNZBD will reach is between 17-22 MegaByte.
However, if I download the same files, but now posted with 5000 yenc lines, the downloadspeed will be 34-36 MegaBytes.
This problem can be easily be reproduced.
As Shypike replied on my PM on the SABZNBD forum, saying it has to do with the internal overhead in SABNZBD when you download a post that is done with 3000 yenc lines.
Three RC from version 1.1.1. have been released up until now but the problem persists.
So, had contact with Shypike and he asked me to post this problem overhere.
Hope that in the future there will be a fix for this.
Give you my best regards,

Nemesh64

**Comment by Safihre** [comment]
Unfortunately a problem that any NZB-downloader faces: decoding and processing 1 huge yEnc'ed article is much more effective because we don't have to do a lot less bookkeeping and we have to do less requests on the sockets for new articles.
We have to ask socket connections if they have new data to process, when you're on a fast connection (and don't use SSL) we can get up to 500K in 1 read of a socket. If your articles are only 50K we don't use the full power because we need to first send a new request for the next article.

NZBGet suffers from the same, for example:
Article size of 32K gives me 50MB/s on my Core i5, while 500K articles give me 70MB/s.

**Comment by thezoggy** [comment]
does the overhead change with different article caches? since thats the whole point of it... which only really gets used for those large postings...

**Comment by Safihre** [comment]
It's not "overhead" since all actions are nessecary to download stuff. We need to look up which article to download, request it from the server, download it and then process it.
All we can do is make the individual steps faster, for example with the SABYenc I'm working on. But in the end, small articles will cause more work for any usenet software..
It's not dependent on article cache size, since it's about the steps of getting the article.

**Comment by thezoggy** [comment]
sure, but part of the 'overhead' is disk io since you need to store those articles some where..  which is why i mention about using the article cache to see if this helps as ram is much faster than most storage devices..
