### ISSUE TITLE
post-process scripts vs default python interpreter (shebang)

### ISSUE THREAD

**Issue by jbormolini** [sabnzbd/sabnzbd#741]
Commit 6fbe450dcce0b87f02dac5f4daecd14f0ed75695 (Require x-bit to be set for scripts on non-Windows) should be reverted.

Looking at sabnzbd/newsunpack.py external_processing() function.

It breaks post-process scripts that specify a specific version of python to use (in the #! line at the top of the script). I see no reason why the logic should be changed from the original behavior.

The original logic came from commit dd7335c25744c2e2eb0f6a479e06f8c5a13b2424 (Use default Python interpreter only for non-executable Python scripts (OSX and Unix).). This makes sense - gives a chance at running python scripts correctly even if user didn't give +x.

**Comment by Safihre** [comment]
The reason is this real world hack of a pc using a sabnzbd: https://forums.sabnzbd.org/viewtopic.php?f=9&t=21804

So if an intruder gets your API key he can just download some python script from usenet and execute it. Sabnzbd shouldn't blindly execute scripts.
If a user wants a post processing script, he will have to set it to +x, is this so weird?

**Comment by jbormolini** [comment]
Ouch. I don't mind enforcing +x, but I think it shouldn't force the 'python' interpreter.

**Comment by Safihre** [comment]
Aaah yes.. True, now I see the problem.
Before you could set the +x and then specify your own interpreter, now you can't. 
I think we should check if the file starts with ```#! ```, if not (and it has +x) we add ```python```. 
What do you think @jcfp and @sanderjo?

**Comment by jbormolini** [comment]
At the risk of polluting this issue, I've been thinking about the security problem. Here we go...

Assumption 1: attacker can change script path
Assumption 2: attacker can change post process and/or notification script

Steps:
1. Set /bin as script path
2. Set 'bash' as script name
3. Profit? Bash will interpret an argument it receives as a script

**Comment by jcfp** [comment]
@Safihre hashbang should be relied on, in fact the only reason for inserting the python command at all on *nix would be backwards compatibility with prior releases of sab. I already mentioned the python version mixup that could ensue from inserting the command in our recent discussion by forum pm on Nov 20th.

So I'd certainly prefer going with just the hashbang, without any attempt to tweak the command line by sab. Otherwise, at the very least it should never be overruled if present.

**Comment by Safihre** [comment]
Implemented 👍
