### ISSUE TITLE
SSL context selftest question.

### ISSUE THREAD

**Issue by nzbjamz** [sabnzbd/sabnzbd#789]
First, thanks for such an awesome project!

I noticed [the selftest for `HAVE_SSL_CONTEXT`](https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/downloader.py#L385-L398) and was wondering if that checks it repeatedly? If so, it might be better to move the logic to only test if the SSL verify check fails to avoid pinging `https://self-test.sabnzbd.org/` a ton. I'm up for creating a PR to help too.

**Comment by Safihre** [comment]
It only checks it once on startup of Sabnzbd, which usually shouldn't be too often. 
Same is true for the check for IPv6 just above it. 
We opted for this since it's only a socket-connect, and no data is really transferred in both cases, making the load quite low. 
The right combination of OpenSSL, Python version and CA certificates makes this a tricky thing that we rather just test than assume :)

**Comment by nzbjamz** [comment]
Ah nice! Ya if it's once then no worries. It's a pretty a pretty considerate check. I just got my python cert verification issues resolved as well 😉
