### ISSUE TITLE
Feature Request: Include Queue items in the 'checking' state in the total remaining download calculation

### ISSUE THREAD

**Issue by cdloh** [sabnzbd/sabnzbd#809]
Currently it isn't calculated which can make the queue appear a lot smaller than it is.

I'm not sure if this is intended or not.

**Comment by Safihre** [comment]
It's intentional.
Mostly because during the check, the counter will go down because checked bytes are counted as "downloaded" bytes in that state. So after the check is done, it would jump up again.

We could of course count the total job-size for Checking downloads, what do you think @shypike ?

(We kind of want to get rid of the checking feature since it causes hangups for some users that we haven't been able to reproduce/identify in almost a year....)

**Comment by thezoggy** [comment]
just disable checking if you dont like the effects of it..

**Comment by Safihre** [comment]
He's just wondering why it's not included in the title, not that he doesn't like it.

**Comment by cdloh** [comment]
Ah it's a shame to hear you are thinking of getting rid of it. It's saved a considerable amount of bandwidth for myself on what overwise would have been failed downloads.

**Comment by Safihre** [comment]
I think we will stick with current behavior, since a download is only really adding bytes to the Queue if it's accepted after a check.
