### ISSUE TITLE
Minimum Free Space

### ISSUE THREAD

**Issue by marka65** [sabnzbd/sabnzbd#818]
Would it be possible to have minimum free space to auto pause if there is not enough space  for the current download? 
Then maybe check any others in the download queue, and if there is enough space run those downloads.

For example, say you have available by disk space or disk quotas 7gb free in your download path, and in your queue you have 3 jobs. first one is 1.4gb, and the second one is 8gb, and the last one is 4gb.

So the process would check the first item and see if enough space, yes there is, so it would process that one. Then it would check the second item, and because that would not fit, then it would skip that item. Then again, it would move onto the next job, and because there is enough space it would process that one. It would then pause the downloads until enough space becomes available. (Presuming that there was 3 in the queue, or else it would look at all the items in the queue)

Anyways, just an idea - thanks for all the work so far.....

**Comment by thezoggy** [comment]
this already exists.. `config` > `folders` > `Minimum Free Space for Temporary Download Folder`
set it to `10G` if you want sab to auto pause if there's not that much free space.

**Comment by marka65** [comment]
Thanks, I had seen that setting, and thought that it would stop the whole queue. Would this feature process any jobs that would not set the minimum space setting off.

For example, if you set it to 5gb minimum, and your sab queue had 10gb as the first job, and then a 1gb job as the second item, would it process the second job and then pause, or would it pause the whole queue?

Will have a play with that setting when I have some more jobs.
Cheers

**Comment by Safihre** [comment]
It's much simpler: as soon as the available space goes below that during downloading, the whole queue is stopped. 
On the other hand for the Complete folder this is very complicated because different jobs can have different results folders based on their category for example. So it's not just a simple check..

**Comment by marka65** [comment]
Thanks for the explanation with the issues it would cause..... Yea, I have all my categories pointing to the same drive.

**Comment by kappaknight** [comment]
Question - does this feature auto-resume once enough space frees up again? As files get processed and moved into its final destination, space opens up again, but the queue hasn't resumed as far as I can see.

**Comment by Safihre** [comment]
No, there's no auto resume. We assume you manually fix the problem after which you also restart the queue.
Otherwise we could end up filling the disk way too much when there's actually no space and keep hammering it as soon as space becomes available.

**Comment by kappaknight** [comment]
Gotcha. I totally see where you guys are coming from, but can I make a change/feature request for the system to do this then? The option would be activated via a checkbox or a visual toggle like it is today for setting minimum free space. Basically this will help automate the software even more so we can set and forget it.

Basically, my current workflow with sonarr/radarr, which I'm sure is like many others: 
- files come in
- get repaired if needed, and unzipped
- moved to complete folder (which could be a different drive too)
- then we wait for one of the above two programs to pick it up and move it to its final destination

This means that I don't have to go manually go clean things up every time before the space frees itself; and things could potentially continue without my intervention.

Right now I have my settings set at 30GB's free. Some days when I wake up to check if anything new has been added to Plex, and seeing nothing since the night before, I usually have to go check Sabnzbd to see if it's paused or if it had crashed. Most times, it's just paused, but with the other programs picking away at the files, I also see the drive with over 100GB free, but Sabnzbd not doing a thing.

As I was thinking this aloud, another thought actually came to me; which wouldn't require setting up toggles and checkboxes.

*If the service paused for low low disk space, maybe instead of pausing it for good, activate that option where it pauses for an hour. If in an hour it needs to continuing pausing for low disk space, just keep extending it by hour increments.*

**Comment by Safihre** [comment]
It's possible for sure. This would then only apply to the Incomplete folder, so we are clear.
Because for the Complete folder there's no real check, just unrar that errors out. Plus we have the problem explained above that complete directories can be everywhere due to category settings.

**Comment by kappaknight** [comment]
Yeah - I believe incomplete is where it matters. I do see what you're saying about various Completed folder locations; but I assume if a file can't be copied/moved over to a particular completed folder, then Sabnzbd would just retain it in the incomplete? (In which case, the incomplete folder would still be full, so downloading wouldn't resume?)

**Comment by Safihre** [comment]
That's correct indeed, it would stay.

**Comment by methanoid** [comment]
Would be helpful if Sab then resumed when the minimum space issue is resolved.. Mine downloads files and my machine moves them to other free space. I can return to find an empty HDD but Sab has paused all night... 

I'd like to see the free space limit periodically checked ;-)

**Comment by Safihre** [comment]
Closed by #1724
