### ISSUE TITLE
FAT: pro-active and re-active detection & reporting

### ISSUE THREAD

**Issue by sanderjo** [sabnzbd/sabnzbd#848]
A SABnzbd Complete directory on a FAT file system, can cause problems: if the download is bigger than 4GB (which does happens with MKV-files), SAB / unrar will discover & reports problems at the **end** of the download process. If we can detect and report that ealier & more clearly, that would be useful for users.

So my suggestion is:
1)  pro-active detection of FAT: at startup of SAB, and at setting another Complete directory
2) re-active detection in the unrar output of FAT-caused problems

The above is not needed for the Temp/Incomplete directory, as rar and par2 files will never be 4GB
The above is also needed for Category folders.

Such problems will not occur with other, more modern file systems, like NTFS, ext3, ext4, etc

If we agree on this (especially @safihre), I can write the code.

**Comment by Hellowlol** [comment]
Why on earth would anybody use fat? The only reason I can come up with is sd cards. So the next question is why would anybody save to a sd card :p

**Comment by sanderjo** [comment]
> Why on earth would anybody use fat?

If you buy a 2TB USB-disk, it's FAT, isn't?

**Comment by thezoggy** [comment]
sadly fat32 is still used by a lot of people due to it being so open to write to..  for example amazon's firetv supports fat32 for external harddrives.. which people use and end up having to rarsplit movie files just to get them to fit and load in kodi.

anyways, we cant really do much on the remote file system.. but locally we deff should detect if FAT12/16/32 is being used for the incomplete/complete folders and warn against it..   

another battle is case sensitive file systems.. but i'll leave that conversation for another day

**Comment by Safihre** [comment]
It should be at the start of the post processor I think. So at the start of its `run()` method. This way it's run asynchronously during startup. 

Can you also integrate a check if all the output folders are writeable? :+1:

**Comment by thezoggy** [comment]
sounds like we really should just make a `health` tab in sab config.. where we can do all these sort of warnings / optimization / tests.. and put the pystone/disk speed/network tests/setup tests at
