### ISSUE TITLE
Suggestion: let's not bind to a different port when the configured port is blocked

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#875]
SAB has always done this, and I never understood it.
Why bind to a different port instead of dying with an error message? 
It seems also illogical from a user's point of view. How does he know where his SAB has gone?

**Comment by sanderjo** [comment]
I find it annoying and confusing too. And when it happens, and SAB is on another port, it will keep using that port.

However, it was probably introduced a long time ago with the idea "we need any port, doesn't matter which one, and we print it on the STDOUT and sabnzbd.log so that the user can see it easily".

That reasoning is not true anymore if you don't see STDOUT: non-local devices (likes NASes), non-technical users, SAB running as a daemon/service, etc.

The bad side of "8080, or nothing" is non-starting services. Which is as bad for the users mentioned above ... :-(

So we need a way to inform the user...

**Comment by shypike** [comment]
The search-for-free-port was implemented for first time startup.
When a user starts SABnzbd for the first time, it's essential that a usable port is found.
On later launches it makes less sense.

Currently there's a hidden INI setting called "fixed_ports", which prevents searching for a free port.
I propose that we set this variable to 1 after a successful start.
Of course, then it will no longer be useful to set it manually to 0. But that's OK; we have more one-time flags.

**Comment by sanderjo** [comment]
Ah, I found it: http://127.0.0.1:8080/sabnzbd/config/special/#fixed_ports

**Comment by sanderjo** [comment]
Just asking: is this something for SAB 2.0.0, or apres SAB 2.0.0?

**Comment by Safihre** [comment]
After, that's why I put it with the `2.0.X` milestone!

**Comment by sanderjo** [comment]
> After, that's why I put it with the 2.0.X milestone!

With X not 0, apparently. 

OK, clear.
