### ISSUE TITLE
<status> in API used for different things

### ISSUE THREAD

**Issue by sepodele** [sabnzbd/sabnzbd#906]
With the new version of SAB <state> in qstatus and queue is changed to <status>. I think that's a problem because now <status> is used for both the status for items in queue as well as the general status of SAB. Change back to <state> for the general status? :)

**Comment by Safihre** [comment]
As you can see on the API page and in the 2,0,0 release notes, the `qstatus` one will be deprecated soon.
https://sabnzbd.org/wiki/advanced/api#queue_main

The only reason we haven't, is because Couchpotato relies on it but it's official installers haven't been updated in over 1.5 years. 

`qstatus` is short for Queue-status, so doesn't seem so weird to me to have both status and queue items?
For just status you should use `fullstatus` (that's also in the 2.0.0 release notes).

**Comment by sepodele** [comment]
I see some symbols were removed in my initial post. What I tried to say was that the tag `<state>` been changed to `<status>`, also in the fullstatus. So now the status tag is used for two different things (also in the fullstatus).
