### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#933]
It seems Python 3.6 is really speeding up things and I wonder if we should consider re-writing SAB for Python 3?
https://www.youtube.com/watch?v=d65dCD3VH9Q

This is also inspired by Cheetah now being ported to Python 3.
https://github.com/CheetahTemplate3/cheetah3

I already tried running the `2to3` tool on SABnzbd, but it turns out to be a bit more complicated than that...
Anyone willing to help?

**Comment by Hellowlol** [comment]
Wouldnt it be better to use http://python-future.org/futurize.html to port the code to python3 check that it works then remove the fixes that enables py2 support?

Or are we gonna do a hard switch?

**Comment by Safihre** [comment]
Hard switch. I've seen projects supporting both, and it's a mess. 
We control the packages for Windows and Mac, and on Linux all distributions have some version of Python 3, so we should be good. 
I am aware that older Python 3 versions have problems to, so we will have to figure those out as we go.

**Comment by Hellowlol** [comment]
What is the minimum supported? 3.4?

**Comment by Safihre** [comment]
No clue yet, need to convert first.
Working now with 3.6.1.

**Comment by thezoggy** [comment]
i personally would say we would rewrite sab from scratch for py3 not convert. there is so much legacy code and cruft... better to take the time to just redo things correctly. converting you are most likely going to introduce bugs.. and the fact sab has 0 unit tests... is a huge issue where you dont know what you break until after its too late. 

adding test sets to sab is far more important imho than converting it to another language

**Comment by labrys** [comment]
3.4 is safe.  Personally I prefer a 3.6 baseline for cross-platform due to PEP 529: "Change Windows filesystem encoding to UTF-8", but 3.6 is not available on all platforms yet (for example latest debian has 3.4 and 3.6 is only in experimental).  Also I would highly recommend a rewrite for py3 as @thezoggy recommends.

**Comment by thezoggy** [comment]
```
Python 2.0 - October 16, 2000

    Python 2.1 - April 17, 2001
    Python 2.2 - December 21, 2001
    Python 2.3 - July 29, 2003
    Python 2.4 - November 30, 2004
    Python 2.5 - September 19, 2006
    Python 2.6 - October 1, 2008
    Python 2.7 - July 3, 2010

Python 3.0 - December 3, 2008

    Python 3.1 - June 27, 2009
    Python 3.2 - February 20, 2011
    Python 3.3 - September 29, 2012
    Python 3.4 - March 16, 2014
    Python 3.5 - September 13, 2015
    Python 3.6 - December 23, 2016
```

https://wiki.ubuntu.com/Python/3

looking at packages..
https://packages.ubuntu.com/search?keywords=python3

can see that with ubuntu 14.0.4 LTS they added py 3.4.0

**Comment by Safihre** [comment]
@thezoggy Agreed. Without unittests it's just shooting in the dark.
Also with that I'm going to need help though. Especially because it's a bit boring 😃

**Comment by Safihre** [comment]
In that case, we can also just switch to Go! I know @sanderjo is looking forward to use it :wink:

**Comment by labrys** [comment]
@Safihre if you use test-driven development, a py3 rewrite would add the tests as you dev killing 2 birds with one stone.

**Comment by Safihre** [comment]
@labrys If I'd ever do a re-write, it would just not be in Python.. It would be in a language that can actually use multithreading like Go/C++/C#/etc. The single-threading of Python, even with the tricks I used in `sabyenc`, is a huge limit in such a performance driven thing as Usenet downloading.
Python is nice because people can easily contribute, but[ that doesn't seem to help SAB a lot..](https://github.com/sabnzbd/sabnzbd/graphs/contributors).

But a re-write would take crazy amounts of time, too much for 1 dev 😢

**Comment by labrys** [comment]
Hehe, I fully understand, but the same principle would apply to any rewrite not just py3.  I understand it's a huge time commitment, just keep in mind currently py 2.7 is scheduled for only 2 more years of LTS (ofc that's always subject to change).

**Comment by Hellowlol** [comment]
Alright, im busy atm but ill help with the convert to py3 in a couple of weeks.

**Comment by Safihre** [comment]
@Hellowlol Looking more into this I think I underestimate the new problems introduced in Python 3.
Indeed the discrepancies between the different releases would still force us to do hacky-tricks. 
@thezoggy's description of this being a complete re-write of the codebase might be very real..
In that case I would again suggest to change to maybe a different language? (far-fetched project, I know)

**Comment by Hellowlol** [comment]
Why support all the versions? just require 3.6 and stick with that.

**Comment by Safihre** [comment]
We can't because on Linux people are stuck to the system version of Python and those are a mix of 3.4 and 3.5.
https://packages.ubuntu.com/search?keywords=python3

**Comment by Hellowlol** [comment]
So they cant install it manually like windows users have to? :P

**Comment by Safihre** [comment]
Nope! Based on the idea that all packages at the release of the OS version can depend on specific other packages to be present.

**Comment by thezoggy** [comment]
you reduce your user base when you start limiting to only specific versions..  lots of people run sab on their nas/linux that arent linux savy.. so installing an ppa or manually is sadly more than they want to do

**Comment by labrys** [comment]
I would limit to python 3.4+ as python 2.7 can be expected to be at or near end-of-life upon completion of a full-rewrite.  If a platform supports py3 it almost definitely has at least py3.4.  If a platform doesn't have py3 they could continue to use the current py2 sab in an end-of-life or lts state.  You simplify a lot by not supporting py2, and for a full rewrite I think py2 support is unnecessary.

**Comment by thezoggy** [comment]
python3 has been very very slow to be adopted.
Python 3.4 is already 3+ years old (March 16, 2014) but yet most nas/linux distros still struggle to even offer py3. I'm not saying python3 is doomed or anything, but I personally think we are better off staying with the devil we know.

https://hynek.me/articles/python3-2016/

**Comment by labrys** [comment]
That same article can be used to support my point of view as well.  A full rewrite (not just compatibility update) could be considered a "new app" and as mentioned in the article most new projects are started in py3.  There's a reason for that, why start a project on something that has a (relatively) soon end-of-life date.  I'm not against python 2.7 support, but if you're planning a full rewrite I don't see a reason to put all that effort and continue py2 support.  There are many quality of life improvements in python 3, the biggest detractor was lack of library support which for all major libraries is no longer really an issue.  The only other major detractor is, in my mind, target audience.  You have to write in a language thats supported on the platform of your users.  I think python 3.4 (or maybe 3.3) reaches the vast majority of those users, especially by the time the rewrite is complete (I would estimate approx 1 year).

**Comment by thezoggy** [comment]
back in the day when sickbeard was in its prime we talked about moving to py3 to stop having to deal with the conversion pains of unicode.. but the libraries we depended on just didnt exist on py3 and we'd have to port those over or use different libs.. which means rewriting more code..  it just snowballs out of control on time you have to spend to get back to the same place you are at now.

**Comment by labrys** [comment]
I guess that depends on how many libs you have that require py2 and if there are suitable replacements.  We've been working towards py3 compatibility for Medusa and very few aren't.  The ones that aren't py3 are mostly unmaintained.

**Comment by Safihre** [comment]
Another possibility would be to adapt the code to work with PyPy for Python 2.
 It seems everything benefits from PyPy, but there are some quirks we would have to account for. It doesn't just work unfortunately.

**Comment by Safihre** [comment]
Reopening this.
Rewriting to a different language is just never going to happen, so Python 3 is the next logical step.
Doing a full rewrite sounds like a great idea, but it's also a bad idea:
If I learned anything in the past months without @shypike's supervision of my changes, is that stuff is in SABnzbd for a reason. On multiple occasions I  removed stuff that I thought was legacy or useless, which turned out to be essential.
So yes, I will have to go over every line of code, but not starting with a blank sheet.

I hope really that some of you might want to join in making unittests for the current sabnzbd (#999, we need that mock NNTP server first, or just use NServe from NZBget, I'm even fine with that now!), so that I can use those to validate SABnzbd 3.0.0? @Hellowlol @Cpuroast @OldskoolOrion @sanderjo @thezoggy

**Comment by Hellowlol** [comment]
Cool, what python 3 version?

**Comment by Safihre** [comment]
3.4 and up, unless we find essential stuff in 3.5.

**Comment by Hellowlol** [comment]
Hmm, I have seen several library's planning to drop 3.4. Aiohttp and home assistant comes to mind. eol for 3.4 is march 2019

**Comment by Safihre** [comment]
I'll start the conversion on 3.6 and then later see which older versions work also.

**Comment by OldskoolOrion** [comment]
Isn't mozilla's fakeserver with it's nntp module very capable of running functional tests ?

that's what I used years ago for testing nntp protocol stuff - back then at least it conformed to all rfc's i needed it to conform to and really easy in usage.. 
it's still in use today and I notice even more adapted towards functional testing of nntp clients -> it's not in python tho.. but does a server-test-tool need to be written in python ? url : https://dxr.mozilla.org/seamonkey/source/mailnews/test/fakeserver/nntpd.js

From what I read over last couple of years, there's also a plethora of nntp tools/servers written in Go, which are easy to deploy on any platform you prefer.. haven't used any NNTPd stuff myself since there was no need last few years, but I know Go is big in webprotocol testing tools.. i have used few functional testing opensource packages from the Go community and have to say it's hella easy to setup.. great logging.. almost plug and play and easy to incorporate since Go basically runs out of the box everywhere, just like python (even easier imo since none of that version difference fogs the go-community)

**Comment by OldskoolOrion** [comment]
https://hg.mozilla.org/comm-central

so u can download latest tree, with fakeserver under test directory (has all files unlike previous link)

**Comment by OldskoolOrion** [comment]
https://developer.mozilla.org/en-US/docs/Mozilla/Projects/MailNews
usefull documentation and examples

**Comment by Safihre** [comment]
@OldskoolOrion Sounds good, let's discuss in #999, and feel free to implement 👍 

Working in the [`py3`](https://github.com/sabnzbd/sabnzbd/tree/py3) branch.
Basic conversion done, the hard part is still to come...

**Comment by Safihre** [comment]
Started the conversion and already made some good progress.
Lots to be done still! So far only starting the software, adding NZB's and basic downloading works.
All post-processing still needs to be done, so very much just a start.
https://github.com/sabnzbd/sabnzbd/tree/py3

**Comment by OldskoolOrion** [comment]
I've read over 1200 pages of information.. and learned A LOT.. in theory :)  - there's so many different tools, methods, "best practices" out there : I actually had no idea XD
Being honest.. I graduated in 1989 from University.. we tested it on paper usually back then, since it was most code on punchcards.. one typo would mean compiling broke and you had to do all over again.. AND wait a full day or more to be helped again by the "system-administrator" who was the only one allowed to lay the cards in the tray.. that was his job.. hehe XD  different times..

But everything I coded after that.. I never actually tested my stuff.. I knew it would run.. and if there's an issue, users tend to tell you hehe - the build process was simpler.. MUCH.. simpler.. packaging ? what ? dos -> copy.. windows -> installer.. bsd -> tar + pack.. done :-)

So I'm really seeing stuff I never seen before.. and spend around 30% of that time starting learning Go.. which I dig sofar!
I'm sure I can spend another 4 years reading up on every "best practice" and opensource tool out there, which is gonna rock my world.. but besides looking stuff up (which is going to be time consuming anyhow), I am actually going to start and get my hands dirty.. I'll learn as I go.. always the best approach: trying to find the 100% solution the first try at it is not realistic anyway.. and I can see why people get overwhelmed.   

a) there's a new programming language every other week... 98% of which will die away because they are just as crap as Java, JS or C#
b) every distro under linux has multiple completely different build tools and packaging tools and they are all the best.. hehe
c) testing.. every blog / whitepaper has best method.. even worse than the packaging drama
d) 1000 services which claim to do the best automation doing everything for you after just 1 simple setup of the workflow.. hehe

Post seems like a rant now.. don't want to give you that impression.. it's not.. i'm actually enjoying myself a damn lot and it gave me the fire to get going :-)

**Comment by thezoggy** [comment]
chechked out that youtube link about python 3 speed improvements.. was shocked to see that python 3.7 is slower than 2.7 still :(

**Comment by Safihre** [comment]
@thezoggy I also saw that, but not sure how many of these tests apply to SABnzbd. 
Just started testing the downloading and it seems to go at the same speed as 2.7 here at my work's Gigabit connection: ~100MB/s, but only did limited testing so far.
Ordered myself a ARM NEO2 to test performance on lower-powered devices later on.

**Comment by Safihre** [comment]
What I did notice is that the API is *much* faster, before response-times were ~25ms on my system, now often around 9ms! Not sure which part got faster, but it's noticeably snappier.

**Comment by labrys** [comment]
Speed tests are notoriously poor indication of actual performance.  There are so many variables (not just of the programming variety :grin: ) that it is hard to get clear results.  

For example `int`s appear to have poorer performance in python 3 than python 2, however in python 3 an `int` is always a `long` where python 2 has separate `int` and `long` types.  Performance of a long in python 3 is actually more than 50% faster than python 2 which is a significant speed improvement, but the python 3 `long` is still slower than a python 2 `int` for reasons that should be obvious.

**Comment by Safihre** [comment]
@thezoggy Do you have a way to automatically apply certain style-guidelines?
For example the quotation-style? It's a mess now of `"` and `'`
And doc-test style, or other stuff, except the max line-width thing, that's a stupid rule 👻 
I found some that detect problems, but don't automatically fix them,

**Comment by Hellowlol** [comment]
Have you looked into tools like yapf or autopep8?

**Comment by thezoggy** [comment]
you can look back at my work with sab on style guide, i used a few different tools to try automate to keep things nice. also have settings so your ide can do it automagically as well. while I use autopep8, you cant just blindly run it..

**Comment by thezoggy** [comment]
python 2.7 end of life is 2020. https://pythonclock.org/
guess we might as well start working towards python3 again..

**Comment by Safihre** [comment]
Feel free to join in! It's a lot of work..

**Comment by thezoggy** [comment]
Intersting read: https://blogs.dropbox.com/tech/2018/09/how-we-rolled-out-one-of-the-largest-python-3-migrations-ever/amp/

**Comment by kitten77** [comment]
how far have you gotten on converting this ?

**Comment by Safihre** [comment]
Quite far. But as the saying goes: the last 10% of the work will take 90% of the time.
So it already runs just fine in Py3, but now every function needs to be double checked and every general try/except statement verified.
Wanna help? :)

**Comment by kitten77** [comment]
:) I will, just need to get all my stuff back home first.
I am doing a complete rebuild of the Sick-Beard, so it fits nicely in with my plans to use sabnzbd. 
freenode #sabnzbd ?

**Comment by Safihre** [comment]
I don't use IRC personally (already have to keep track of all the other SAB-support channels), but can always email me directly at safihre@sabnzbd.org :)

**Comment by eberkund** [comment]
For the versioning issues maybe supporting older versions will be less of an issue with snapd?

> @thezoggy Do you have a way to automatically apply certain style-guidelines?

Snapcraft uses [black](https://github.com/ambv/black) which can apply some changes automatically and can validate code on the CI server as well.

**Comment by Safihre** [comment]
I'm a bit torn right now 😢 This weekend I started work on a new packaging script in `sabbuild` to use PyInstaller to build the Windows and macOS binaries. And to my surprise, the Windows binary works without any problems 🎈 
But: when I downloaded the same NZB with the Python 3 version it was almost 40% slower than 2.3.8 on my Intel i3 NUC. It went from a stable 40MB/s with ~45% CPU usage on 2.3.8 to a wobbly 22-25MB/s on Python 3 version with 65% CPU usage.
I wasn't expecting there to be a performance boost from using Python 3, but not such a _massive_ performance loss. I'm also not even sure what the source of the performance loss is.. SABYenc? Network-IO? Disk-IO? Thread-performance? 

Maybe this is the time to throw in the towel: fork NZBGet and make it user-friendly and find a way to port most of the settings? Rework the whole SABnzbd core to use things like `asyncio` and hope this solves it?

**Comment by Hellowlol** [comment]
Thats a shame, i expected a preformance loss. Was this running from source or using the binarys? Have you done some profiling? It might be some low hanging fruit

**Comment by sanderjo** [comment]
@Safihre 

I tested on Linux on ARM, and thus SAB-from-source, with the 1GB test download:
SAB-py2: Downloaded in 1 min 22 seconds at an average of 12.6 MB/s
SAB-py3: Downloaded in 1 min 2 seconds at an average of 16.6 MB/s

So for me SAB-py3 is faster.

**Comment by thezoggy** [comment]
Imho py3.5 and older is known to be slower than py2. Py3.6 was when they finally started to get speed back.. but 3.7 is honestly what you should test against to see if the performance hit is still there.

**Comment by Safihre** [comment]
I tested with Python 3.7.3, re-tested running from sources and had same result. 
Wonder if it's Windows-specific something? Not sure exactly how to diagnose or profile where the performance hit really is..

**Comment by Hellowlol** [comment]
Can you post the binaries? I would like to test.

**Comment by Safihre** [comment]
https://github.com/sabnzbd/sabbuild/releases/download/py2app-test/SABnzbd-3.0.0-develop-win64-bin.zip

**Comment by Safihre** [comment]
Merged the `py3` branch into `develop`. Hoping for some more feedback!
Will still use the `py3` branch for testing of features before they end up in `develop`.

**Comment by thezoggy** [comment]
https://www.python.org/downloads/release/python-380/

**Comment by jcfp** [comment]
FYI: I've added all of the python packages needed for sab-py3 (gntp, portend, tempora, jaraco.functools) to debian. Sabyenc3 is ready as well, I plan to get that into debian experimental along with sab-py3 once there's a tagged (beta) release for the latter.

**Comment by jcfp** [comment]
> Merged the `py3` branch into `develop`. Hoping for some more feedback!

@Safihre any chance of tagging an alpha release in the foreseeable future?

That would increase feedback, and also help keep sab around in the repos of mainstream distros looking to cull python2.

**Comment by sanderjo** [comment]
> @Safihre any chance of tagging an alpha release in the foreseeable future?

Yes, please, @Safihre . And FWIW: I've using SAB-py3 for some months now for almost all my downloads. I would SAB-py3 is ready for alpha release.
 
> That would increase feedback, and also help keep sab around in the repos of mainstream distros looking to cull python2.

FWIW #2: Ubuntu 20.04: `python` is not a known command and points softly to python3 (not python2, which is not installed by default)

```
sander@witte2004:~$ python

Command 'python' not found, did you mean:

  command 'python3' from deb python3
  command 'python ' from deb python-is-python3

sander@witte2004:~$ python2

Command 'python2' not found, but can be installed with:

sudo apt install python2

sander@witte2004:~$ python3
Python 3.8.2 (default, Mar 13 2020, 10:14:16) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
sander@witte2004:~$ 
```

**Comment by Cpuroast** [comment]
I agree, I think it's time for a Python3 alpha on Linux, Windows and macOS to get the ball rolling and get feedback.

**Comment by jeffgeorge** [comment]
Same! I've been running with Python 3 via [**linuxserver/sabnzbd**'s unstable channel](https://github.com/linuxserver/docker-sabnzbd/tree/unstable) for months now with no problems.

**Comment by Safihre** [comment]
Good to know :) Actually the problems right now are in the MacOS (because Apple is making it really difficult) and Windows releases (Windows-Service support).
I want to fix at least the MacOS installer, just have to get to it 🎈 I even bought a MacbookPro for the task, managed after days of fiddeling to get it to build the application and the installer, just for Apple to tell me apps now need to be [notarized](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution) 😢  After that I gave up for a few weeks.. Will get to it ASAP!

**Comment by Safihre** [comment]
With respect to Windows: I had to switch to PyInstaller to build the Windows application. However, it does not support multiple .exe-files being just linkers for the same program. So before we had "SABnzbd.exe", "SABnzbd-console.exe", "SABnzbd-service.exe" and "SABnzbd-helper.exe" where each had a specific task but were still only a few KB in size. Now with PyInstaller each .exe-file adds 4MB! So the full installer is becoming huge.. Still have to make a discion what to do with that.
For now: probably remove SABnzbd-service.exe, it can be merged in SABnzbd.exe (but all Service-users have to update their whole setup). And considering making the installer 64bit only, since 32bit installations and downloads [are only a few percent anyway](http://www.safihre.com/sabnzbd/showstats.php). We could still provide a 32bit standalone version.

**Comment by NietGiftig** [comment]
For the Linux users the most important is to make the less informed people aware that there is a Python3 version.
I am using opensuse tumbleweed and was kind of forced out Python2.
Not having much git knowledge, and reading the readme.md, I was having only the python 2.7 option.
By accident (i really needed SABnzbd) i tried the dev branch which state no python3 in the readme.md
after fiddling to install some missing parts it is now working  on Tumbleweed, which is a rolling release, with almost always the latest libs e.d.

**Comment by sanderjo** [comment]
> By accident (i really needed SABnzbd) i tried the dev branch which state no python3 in the readme.md

Ah, yes, that's confusing: "python (only 2.7.x and higher, but not 3.x.x)"

> after fiddling to install some missing parts it is now working on Tumbleweed, which is a rolling release, with almost always the latest libs e.d.

https://sabnzbd.org/wiki/extra/python3 has an instruction for Tumbleweed.

**Comment by Cpuroast** [comment]
Just tested the Python 3 macOS build from Feb 28 on macOS 10.9 through 10.15.
10.9 through 10.14 opened it without doing anything special.
10.15 would not launch it until I right-clicked on the app and picked open, it then allowed me to launch it. Also upon launch on 10.15, macOS prompted me to grant SABnzbd access to Downloads.

**Comment by Cpuroast** [comment]
Just wanted to add that from my initial experience with the Feb 28 build on 10.14, everything seems to be more responsive while interacting with the WebUI.

**Comment by Hydranet** [comment]
I came across this issue via the forums, just thought I'd let you know my status of running the py3 branch. I have been running the py3 branch of sabnzbd since September 2019, I had one issue reported it and it was helped test it and it was fixed. Haven't had any issues since, running it under CentOS, as far as my experience goes it that it runs just as stable as the master branch.

**Comment by Cpuroast** [comment]
Indeed, it's really looking good, once the macOS notarization and the Windows service issues are resolved, it really looks ready to go for an official beta.

**Comment by jcfp** [comment]
FYI: the sabnzbdplus package in debian is [now](https://packages.qa.debian.org/s/sabnzbdplus/news/20200410T084903Z.html) based on a git snapshot of the develop branch. Had to push ahead with that or it would have been removed.

**Comment by sanderjo** [comment]
Oh, nice!

That link says

> Version: 3.0.0~0git20200408+dfsg-1
> Distribution: unstable

And unstable is sid, right? So I checked https://packages.debian.org/sid/sabnzbdplus but it says 2.3.6+dfsg-1 

All buster, bullseye and sid have sab-py2

So ... am I doing something wrong? Or should I wait a bit?

**Comment by thezoggy** [comment]
did you apt-get update to get updated info?

**Comment by Cpuroast** [comment]
The Feb 28th build has been great so far, I've been using it exclusively on macOS for a while now.
On Windows, the Glitter-Night theme wasn't working, but you applied a fix a few days ago.

Would it be possible to get an updated build? Or maybe it's time for a public 3.0.0 Alpha 1 build to start getting feedback.

**Comment by sanderjo** [comment]
@Cpuroast Can't you run from github source on macOS? Maybe the instructions for Linux and Windows can help? See https://sabnzbd.org/wiki/extra/python3.html

**Comment by Safihre** [comment]
Updated the release: https://github.com/sabnzbd/sabbuild/releases/tag/py-test-7
Moving towards a release, for now without Windows Service support.
Also removed the 32-bit files from the Windows installer. Now it will show a warning to download the standalone version if executed on a 32-bit system.
Still want to try to get the notarization right for macOS. Otherwise by end of april I will just release it as-is!

**Comment by Cpuroast** [comment]
Instead of bundling both into 1 installer which makes it quite a larger download, how about just make 2 versions of the installer and then people will just pick the right one.

Windows 10 is available in a 32-bit flavor, so I'm pretty sure MS has the intention of supporting 32-bit for quite some time.

**Comment by Safihre** [comment]
Damn, seems there's still a lot of work on the notarization. [Need to sign every single binary, also unrar/7zip/par2 that we include](https://osxapps-ssl.itunes.apple.com/itunes-assets/Enigma113/v4/74/08/be/7408be9e-f11f-b838-3494-4ce63ececee8/developer_log.json?accessKey=1587516732_5372906723932289143_HnXSKZK%2FvQ6s1CFT%2Bw7iAVypl3cQJOuEcx%2BY0biOHZkHWWc1zaR656lFTv3PoUfm98BvkC6bppNE0OOEcjHu9aPleF86yYVmPIaR2rk7Hdz0YV9%2Bi1xTYSzSI8hhbH4ZpBEzwTL6nG7eQmLDOrweh0J4oZvVlrZZnLP3vV24UPo%3D).

**Comment by Safihre** [comment]
@Cpuroast  Think I got it! Could you try [this release](https://github.com/sabnzbd/sabbuild/releases/tag/3.0.0-build-1) once it is [finished building](https://travis-ci.org/github/sabnzbd/sabbuild/builds/677414401)?

**Comment by Cpuroast** [comment]
> @Cpuroast Think I got it! Could you try [this release](https://github.com/sabnzbd/sabbuild/releases/tag/3.0.0-build-1) once it is [finished building](https://travis-ci.org/github/sabnzbd/sabbuild/builds/677414401)?

Loaded on Catalina without the need for the bypass method, seems to have done the trick.
Let me try it on previous versions of macOS.

**Comment by Cpuroast** [comment]
3.0.0-build-1 execution results:

10.9.5: Good
10.10.5: Good
10.11.6: Good
10.12.6: Good
10.13.6: Good
10.14.6: Good
10.15.4: Good

Everything looks good, might just be time for Alpha 1 or Beta 1.

**Comment by Safihre** [comment]
https://sabnzbd.org/downloads Released 3.0.0 Alpha 1!

**Comment by thezoggy** [comment]
ran into issues with windows binary, ssl not working

**Comment by Cpuroast** [comment]
macOS build is also broken with HTTPS:

2020-04-28 14:42:15,904::INFO::[_cplogging:213] [28/Apr/2020:14:42:15] ENGINE Bus STARTING
2020-04-28 14:42:15,907::ERROR::[_cplogging:213] [28/Apr/2020:14:42:15] ENGINE Error in 'start' listener <bound method Server.start of <cherrypy._cpserver.Server object at 0x109f9afd0>>
Traceback (most recent call last):
  File "site-packages/cheroot/server.py", line 2106, in get_ssl_adapter_class
KeyError: 'cheroot.ssl.builtin'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/cherrypy/process/wspbus.py", line 230, in publish
  File "site-packages/cherrypy/_cpserver.py", line 179, in start
  File "site-packages/cherrypy/_cpserver.py", line 170, in httpserver_from_self
  File "site-packages/cherrypy/_cpwsgi_server.py", line 98, in __init__
  File "site-packages/cheroot/server.py", line 2111, in get_ssl_adapter_class
ModuleNotFoundError: No module named 'cheroot.ssl'

2020-04-28 14:42:16,012::INFO::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE Serving on http://127.0.0.1:8080
2020-04-28 14:42:16,013::ERROR::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE Shutting down due to error in start listener:
Traceback (most recent call last):
  File "site-packages/cherrypy/process/wspbus.py", line 268, in start
  File "site-packages/cherrypy/process/wspbus.py", line 248, in publish
cherrypy.process.wspbus.ChannelFailures: ModuleNotFoundError("No module named 'cheroot.ssl'")

2020-04-28 14:42:16,013::INFO::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE Bus STOPPING
2020-04-28 14:42:16,015::INFO::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('127.0.0.1', 8080)) shut down
2020-04-28 14:42:16,015::INFO::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE HTTP Server None already shut down
2020-04-28 14:42:16,015::INFO::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE Bus STOPPED
2020-04-28 14:42:16,015::INFO::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE Bus EXITING
2020-04-28 14:42:16,016::INFO::[_cplogging:213] [28/Apr/2020:14:42:16] ENGINE Bus EXITED
