### ISSUE TITLE
"show interface" from windows tray should open http://localhost if SABnzbd Host is set to localhost

### ISSUE THREAD

**Issue by bughit** [sabnzbd/sabnzbd#946]
sabnzbd 2.1.0 on win7

for certain reasons I need the url to be localhost rather than 127.0.0.1. It seemed like changing the host in the config to localhost from 127.0.0.1 would accomplish that, but it did not.

**Comment by Safihre** [comment]
Sabnzbd will try to find the ip address matching localhost, and use that to launch the browser. The internal lookup should take care of this. 
This is because some users have different setups of what localhost points to.

**Comment by bughit** [comment]
> This is because some users have different setups of what localhost points to.

The browser also "will try to find the ip address matching localhost".

**Comment by Safihre** [comment]
While I agree, I see this was an active decision because when the Specials-setting `ipv6_hosting` is enabled like in your case (it should be disabled by default), SAB will bind both to `::1` and `127.0.0.1` .
So by force-replacing `localhost` by `127.0.0.1` we are certain that the user can connect can the browser won't try to connect to the IPv6 address, which we found not to be always configured correctly.

So simple solution would be for you to disable `ipv6_hosting` if you don't need it.

**Comment by bughit** [comment]
`ipv6_hosting` is not enabled.  You appear to be saying that when it's not enabled there's no reason to force the url to 127.0.0.1, however it's still happening.

**Comment by Safihre** [comment]
I cannot reproduce that. Are you sure you have unchecked `ipv6_hosting` (the value in between the brackets is the default value, not the current setting). You will need to restart SABnzbd after changing that value.
I inspected the code that determines the address to launch, and it seems to stay on `localhost:8080` in that case, except for exotic situations.

If you switch logging to +Debug in the Status window, restart SABnzbd, what does it show in the log?
It should show:
```
2017-06-14 19:39:41,233::INFO::[_cplogging:219] [14/Jun/2017:19:39:41] ENGINE Serving on https://127.0.0.1:8080
```

**Comment by bughit** [comment]
`ipv6_hosting` is unchecked, I never changed it from the default.
`SABsnzbs Host` is `localhost`
`show interface` opens `http://127.0.0.1/sabnzbd`

```
2017-06-14 13:57:48,099::INFO::[_cplogging:219] [14/Jun/2017:13:57:48] ENGINE Serving on http://127.0.0.1
```

**Comment by Safihre** [comment]
I am sorry, I was mixing things up.

By default `ipv6_hosting` is disabled and we only bind to `127.0.0.1`, thus `localhost` might refer to both `::1` and `127.0.0.1` when the browser connects and might not work because it only tries the `::1`, thus we launch with `http://127.0.0.1/sabnzbd`.

But if you **enable** `ipv6_hosting` SAB will listen on both and thus we can launch safely with `http://127.0.0.1/sabnzbd`.
So the solution is to enable it, I was writing it wrongly before!

**Comment by bughit** [comment]
that works, but seems wrong to enable ipv6 just for this, any chance of letting localhost be forced (switch) or allowing the url to be specified (value)?

**Comment by Safihre** [comment]
This case is very very specific to your situation, 127.0.0.1 would normally always work for local users while `localhost` has given us problems before. 
Making a special setting for this would basically be just for you :wink:
