### ISSUE TITLE
subprocess - unicode

### ISSUE THREAD

**Issue by thezoggy** [sabnzbd/sabnzbd#954]
while working on another piece of code I realize the pains of py2 and unicode arguments being passed to process..  

https://stackoverflow.com/questions/1910275/unicode-filenames-on-windows-with-python-subprocess-popen

> http://vaab.blog.kal.fr/2017/03/16/fixing-windows-python-2-7-unicode-issue-with-subprocesss-popen/

something we need to do, to make par/unrar happy with unicode files?

**Comment by Safihre** [comment]
Luckily Unrar/Multipar are aware of this and unless the name is full unicode it will still understand that "blabla??blaa" (where the ?? can be German/Chinese/etc chars) to open them.

Unless you have a filename with only unicode chars, like some test-NZB's @sanderjo made a while ago:
https://nzbindex.nl/search/?q=SpecialCharStuff (the bottom ones)

But since nobody ever complained, we never implemented that fix. It's possible though, but didn't see the need to yet since most filenames will only contain maybe 1 or 2 unicode chars and that will work.

**Comment by thezoggy** [comment]
i cant get this monkey patch to work.. looks like the guy gave up on his 'fix' and just tells people to use python3

**Comment by Safihre** [comment]
> http://vaab.blog.kal.fr/2017/03/16/fixing-windows-python-2-7-unicode-issue-with-subprocesss-popen/

For me this fix is working, I implemented it in SABnzbd as a test:
https://github.com/sabnzbd/sabnzbd/tree/feature/unicode-popen

And now @sanderjo's test-NZB with only unicode chars in the filename actually unpacks like on linux!
https://nzbindex.nl/release/160594248/reftestnzb-e1db68be-234b-11e7-.par2.nzb

This is just a quick-test, but I think it could also solve other problems like long-path. However the parsing of the output still fails because it's printed like this from `unrar`:
```
Extracting from C:\SABnzbd\A?AA?A«A?AÿA?A?A?A?A?A«A?AYA?A?A?A?A?AA?AA?Ar\????.part04.rar
```
So it will try to delete `????.part04.rar`. Probably this can be fixed with some conversion? (@shypike)

**Comment by Safihre** [comment]
Solution found: `RarFile` will give us a list of all the volumes belonging to a set, so need to interpret the data from the console output.

**Comment by Safihre** [comment]
Implemented!

**Comment by thezoggy** [comment]
thanks!
