### ISSUE TITLE
Write article database back to disk when not used

### ISSUE THREAD

**Issue by Safihre** [sabnzbd/sabnzbd#973]
To preserve memory, we should write the article database back to disk when it's not used for a while. 
For example when all jobs in the queue are out of retention of the first server, it will have loaded all articles into memory even though the second server might take ages to reach it. 

- [x] `TryList` can currently not be pickled, it has `Server` objects which in  turn have socket objects. 
- [ ]  Decide when and how to trigger writing the objects back to disk. 
- [ ]  Implement it using clean code.

**Comment by Safihre** [comment]
@puzzledsab this could maybe be interesting one? Seems you like these bigger core problems :)

**Comment by puzzledsab** [comment]
I've been looking into it on and off for a few days already :D

I have some hunches about timestamps on the nzos and swapping out the articles on the nzos that were most recently added, then loading them all back if the nzo is accessed. Maybe you already have better ideas? Problem is I still don't know enough Python or understand SAB well enough to know if it's doable in practice or if there are major show stoppers. I'm digging, though.

I was trying to make the pause on full disk system use the actual complete directory of the nzo instead of the default dir, in order to only pause if the disk it will actually unpack to is full. It seemed simple enough and I even made a more generic caching OO replacement for diskspace(). However, digging through the code I realized that building the path was such a complex operation that it would use a bit much CPU to do it for every file. It can be cached, but then it needs to be cleared if it changes.

**Comment by Safihre** [comment]
Yes, indeed a timestamp on the nzo is also what I was thinking. This can then be checked during a new check in the periodic checks in the main loop in SABnzbd.py for example. Has to be locked with `NZO_LOCK` probably, to avoid competing access.
That's another thing that could be improved, how to use a NZO specific lock instead of 1 lock for all NZO's. 

Feel free to send in draft PR's or send me an email at safihre@sabnzbd.org if you have any questions. I can already recommend PyCharm as an IDE, it opened up a whole new world for me when I started using that, especially the Debugger is amazing for SABnzbd. The community edition is free and has 99% of what you'd need. I have extra PyCharm Professional licenses that we get for free as a bigger open source project, in case you'd need it! 

Interested to see what OO version you made for diskspace, this way I don't have to do it! 😄

**Comment by puzzledsab** [comment]
I've experimented a bit, and it seems that the pickled files and file.articles can be compressed by 60-80%. Maybe we could read the nzb, compress it immediately, attach it to the parent object, and decompress it on the fly when or just before it's needed?

I also noticed that when an nzb is not started at all (0 bytes downloaded), pickling the file object and file.articles results in about the same amount of data. Shortly after it's started, the file object size increases by maybe 75%, while file.articles falls to almost zero. The total is smaller, though, resulting in a smaller memory footprint in total. Do you know why this is? Why not go straight to the mode that uses less memory?

**Comment by Safihre** [comment]
Go ahead! I have never really looked at this so don't have the answers either. Not sure I have a clue why the size would increase so much..

**Comment by puzzledsab** [comment]
Is there any particular reason why you are importing the python based pickle instead of
```
try:
    import cPickle as pickle
except:
    import pickle
```
?

**Comment by Safihre** [comment]
In Python 3 there is no cPickle, it's the default.

**Comment by puzzledsab** [comment]
I have a kind of working version and I could use some feedback: https://github.com/puzzledsab/sabnzbd/tree/feature/pickle

It will import the raw_article_db immediately and then pickle the resulting articles and decodetable. It has some issues, though. It will break the try_list once in a while, which I think is related to letting any server unpickle the articles instead of just the top server here: https://github.com/puzzledsab/sabnzbd/blob/afd59552b58de30351e6448b04ce2cff5d00c2ff/sabnzbd/nzbstuff.py#L1590

I'm not sure if that's the problem, but I did notice that a server far down the priority list suddenly unpickled some files when it wasn't even being used. Do you think it is, and do you have any suggestions on how to fix it?

Another issue is that the fast decoding of articles that are too old for a server needs to be slowed down, otherwise too much will be unpickled too quickly and the pickler can't keep up. I'll use your `server.next_article_search` for that when you merge it.

I'm also hoping to find a way to pickle some file data, otherwise it will use at least as much RAM as today for most users.

It's not currently backwards compatible so you need to start with an empty queue. Don't mind things like the separate thread for calling sabnzbd.NzbQueue.pickle(), it's just a leftover from experimentation.

**Comment by puzzledsab** [comment]
It could also be the handling of the first article in the pickle function. I think it's it's duplicated by the first_article system if I try to pickle it.

**Comment by Safihre** [comment]
Merged my PR and responded to some parts of your commits 👍

**Comment by puzzledsab** [comment]
Thanks for your comments. I've noticed that this line will usually say that the number of servers in try_list is 1 less than the number of active servers: https://github.com/puzzledsab/sabnzbd/blob/1cd21a385af21f82e6f179e7303ccc61b4cccdea/sabnzbd/nzbqueue.py#L964

It's like that even if the file is far into the queue. This seems weird to me, but at the same time it seems like it's supposed to happen. I don't see anything stopping the lower priority servers from overtaking the higher priority ones once the articles are loaded into memory. Is it working as intended or have I broken anything?

**Comment by Safihre** [comment]
You could inspect the servers in the Try list to see if it makes sense.
The thing stopping the lower prio servers taking over is in the get_article of Article object. There we check the priority.

**Comment by puzzledsab** [comment]
I'm working on a simplified version of this that will pause the downloading and swap out everything that is not currently being used when it seems necessary. It will be optional.

**Comment by Safihre** [comment]
Closing this, as @puzzledsab's efforts have shown that it is just too complex to be worth the extra code-burden.
